name: Deploy boxel-host
description: Deploy boxel-host to S3 and Cloudfront

inputs:
  environment:
    description: Deployment environment
    required: true
  discord_webhook:
    description: Discord webhook URL
    required: true
  pnpm_version:
    description: Used by pnpm/action-setup
    default: 7.2.1
    required: false
  node_version:
    description: This controls what version of node first boots pnpm, but pnpm itself will read the .npmrc file and download a different version if they don't match.
    default: 18.6.0
    required: false

runs:
  using: composite
  steps:
    - name: Set up env
      shell: bash
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        if [ "$INPUT_ENVIRONMENT" = "production" ]; then
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ROLE_ARN=arn:aws:iam::120317779495:role/boxel-host" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=cardstack-boxel-host-production" >> $GITHUB_ENV
          echo "AWS_CLOUDFRONT_DISTRIBUTION=E2DDEHLJXF5LQ8" >> $GITHUB_ENV
          echo "OWN_REALM_URL=https://realm-demo.cardstack.com/demo/" >> $GITHUB_ENV
          echo "RESOLVED_BASE_REALM_URL=https://realm-demo.cardstack.com/base/" >> $GITHUB_ENV
        elif [ "$INPUT_ENVIRONMENT" = "staging" ]; then
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ROLE_ARN=arn:aws:iam::680542703984:role/boxel-host" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=cardstack-boxel-host-staging" >> $GITHUB_ENV
          echo "AWS_CLOUDFRONT_DISTRIBUTION=E35TXLK9HIMESQ" >> $GITHUB_ENV
          echo "OWN_REALM_URL=https://realm-demo-staging.stack.cards/demo/" >> $GITHUB_ENV
          echo "RESOLVED_BASE_REALM_URL=https://realm-demo-staging.stack.cards/base/" >> $GITHUB_ENV
        else
          echo "unrecognized environment"
          exit 1;
        fi

    - uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm_version }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: pnpm
    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Build
      shell: bash
      run: pnpm build:boxel-host
    - name: Zip
      shell: bash
      run: zip -r boxel.zip ./dist
      working-directory: packages/host
    - name: Copy zip to s3
      uses: prewk/s3-cp-action@v2
      with:
        source: './packages/host/boxel.zip'
        dest: '${{ env.AWS_S3_BUCKET }}boxel_dist/boxel.zip'
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy
      shell: bash
      run: pnpm deploy:boxel-host ${{ inputs.environment }} --verbose

    - name: Send notification to Discord
      if: ${{ always() }}
      uses: cardstack/cardstack/.github/actions/discord-notification-deploy@main
      with:
        app: boxel-host
        status: ${{ github.action_status }}
        environment: ${{ inputs.environment }}
        webhook: ${{ inputs.discord_webhook }}
