-- This is auto-generated by packages/realm-server/scripts/convert-to-sqlite.ts
-- Please don't directly modify this file

 CREATE TABLE IF NOT EXISTS bot_commands (
   id NOT NULL,
   bot_id NOT NULL,
   command TEXT NOT NULL,
   command_filter BLOB NOT NULL,
   created_at NOT NULL,
   PRIMARY KEY ( id ) 
);

 CREATE TABLE IF NOT EXISTS bot_registrations (
   id NOT NULL,
   username TEXT NOT NULL,
   created_at NOT NULL,
   PRIMARY KEY ( id ) 
);

 CREATE TABLE IF NOT EXISTS boxel_index (
   url TEXT NOT NULL,
   file_alias TEXT NOT NULL,
   type TEXT NOT NULL,
   realm_version INTEGER NOT NULL,
   realm_url TEXT NOT NULL,
   pristine_doc BLOB,
   search_doc BLOB,
   error_doc BLOB,
   deps BLOB DEFAULT '[]',
   types BLOB,
   isolated_html TEXT,
   indexed_at,
   is_deleted BOOLEAN,
   last_modified,
   embedded_html BLOB,
   atom_html TEXT,
   fitted_html BLOB,
   display_names BLOB,
   resource_created_at,
   icon_html TEXT,
   head_html TEXT,
   has_error BOOLEAN DEFAULT false NOT NULL,
   last_known_good_deps BLOB,
   markdown TEXT,
   timing_diagnostics BLOB,
   PRIMARY KEY ( url, realm_url, type ) 
);

 CREATE TABLE IF NOT EXISTS boxel_index_working (
   url TEXT NOT NULL,
   file_alias TEXT NOT NULL,
   type TEXT NOT NULL,
   realm_version INTEGER NOT NULL,
   realm_url TEXT NOT NULL,
   pristine_doc BLOB,
   search_doc BLOB,
   error_doc BLOB,
   deps BLOB DEFAULT '[]',
   types BLOB,
   icon_html TEXT,
   isolated_html TEXT,
   indexed_at,
   is_deleted BOOLEAN,
   last_modified,
   embedded_html BLOB,
   atom_html TEXT,
   fitted_html BLOB,
   display_names BLOB,
   resource_created_at,
   head_html TEXT,
   has_error BOOLEAN DEFAULT false NOT NULL,
   last_known_good_deps BLOB,
   markdown TEXT,
   timing_diagnostics BLOB,
   job_id INTEGER,
   PRIMARY KEY ( url, realm_url, type ) 
);

 CREATE TABLE IF NOT EXISTS incoming_webhooks (
   id NOT NULL,
   username TEXT NOT NULL,
   webhook_path TEXT NOT NULL,
   verification_type TEXT NOT NULL,
   verification_config BLOB NOT NULL,
   signing_secret TEXT NOT NULL,
   created_at NOT NULL,
   updated_at NOT NULL,
   PRIMARY KEY ( id ) 
);

 CREATE TABLE IF NOT EXISTS module_transpile_cache (
   realm_url TEXT NOT NULL,
   canonical_path TEXT NOT NULL,
   body TEXT,
   headers BLOB,
   dependency_keys BLOB,
   generation DEFAULT 0 NOT NULL,
   created_at,
   PRIMARY KEY ( realm_url, canonical_path ) 
);

 CREATE TABLE IF NOT EXISTS modules (
   url TEXT NOT NULL,
   cache_scope TEXT NOT NULL,
   auth_user_id TEXT NOT NULL,
   resolved_realm_url TEXT NOT NULL,
   definitions BLOB,
   deps BLOB,
   error_doc BLOB,
   created_at,
   file_alias TEXT,
   url_hash TEXT GENERATED ALWAYS AS (url) STORED NOT NULL,
   timing_diagnostics BLOB,
   PRIMARY KEY ( url, cache_scope, auth_user_id ) 
);

 CREATE TABLE IF NOT EXISTS realm_file_meta (
   realm_url TEXT NOT NULL,
   file_path TEXT NOT NULL,
   created_at INTEGER NOT NULL,
   content_hash TEXT,
   content_size INTEGER,
   PRIMARY KEY ( realm_url, file_path ) 
);

 CREATE TABLE IF NOT EXISTS realm_meta (
   realm_url TEXT NOT NULL,
   realm_version INTEGER NOT NULL,
   value BLOB NOT NULL,
   indexed_at,
   PRIMARY KEY ( realm_url, realm_version ) 
);

 CREATE TABLE IF NOT EXISTS realm_metadata (
   url TEXT NOT NULL,
   show_as_catalog BOOLEAN,
   publishable BOOLEAN,
   created_at DEFAULT CURRENT_TIMESTAMP NOT NULL,
   updated_at DEFAULT CURRENT_TIMESTAMP NOT NULL,
   PRIMARY KEY ( url ) 
);

 CREATE TABLE IF NOT EXISTS realm_registry (
   id DEFAULT (hex(randomblob(16))) NOT NULL,
   url TEXT NOT NULL,
   kind TEXT NOT NULL,
   disk_id TEXT NOT NULL,
   owner_username TEXT NOT NULL,
   source_url TEXT,
   last_published_at,
   pinned BOOLEAN DEFAULT false NOT NULL,
   created_at DEFAULT CURRENT_TIMESTAMP NOT NULL,
   updated_at DEFAULT CURRENT_TIMESTAMP NOT NULL,
   PRIMARY KEY ( id ) 
);

 CREATE TABLE IF NOT EXISTS realm_user_permissions (
   realm_url TEXT NOT NULL,
   username TEXT NOT NULL,
   read BOOLEAN NOT NULL,
   write BOOLEAN NOT NULL,
   realm_owner BOOLEAN DEFAULT false NOT NULL,
   PRIMARY KEY ( realm_url, username ) 
);

 CREATE TABLE IF NOT EXISTS realm_versions (
   realm_url TEXT NOT NULL,
   current_version INTEGER NOT NULL,
   PRIMARY KEY ( realm_url ) 
);

 CREATE TABLE IF NOT EXISTS webhook_commands (
   id NOT NULL,
   incoming_webhook_id NOT NULL,
   command TEXT NOT NULL,
   command_filter BLOB,
   created_at NOT NULL,
   updated_at NOT NULL,
   PRIMARY KEY ( id ) 
);