#!/bin/sh
#MISE description="Start AI bot for development"
#MISE dir="packages/ai-bot"

MATRIX_URL="${MATRIX_URL_VAL}" \
  NODE_NO_WARNINGS=1 \
  PGPORT="${PGPORT}" \
  PGDATABASE="${PGDATABASE}" \
  exec ts-node --transpileOnly main
