extends: default

rules:
  comments:
    min-spaces-from-content: 1
  line-length: disable
  document-start: disable
  quoted-strings:
    quote-type: double
    required: false
  truthy:
    check-keys: false
