packages:
  - packages/*
  - packages/boxel-motion/*
  - packages/boxel-ui/*
  - vendor/*
catalog:
  "@typescript-eslint/eslint-plugin": ^7.18.0
  "@typescript-eslint/parser": ^7.18.0
  "@types/qunit": 2.11.3
  ember-concurrency: ^4.0.3
  ember-concurrency-ts: ^0.3.1
  ember-qunit: ^8.0.1
  eslint: ^8.57.1
  eslint-config-prettier: ^9.0.0
  eslint-doc-generator: ^1.7.1
  eslint-plugin-ember: ^12.5.0
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-eslint-plugin: ^5.5.1
  eslint-plugin-filenames: ^1.3.2
  eslint-plugin-import: ^2.31.0
  eslint-plugin-markdown: ^5.1.0
  eslint-plugin-n: ^17.17.0
  eslint-plugin-prefer-let: ^3.0.1
  eslint-plugin-prettier: ^5.2.6
  eslint-plugin-qunit: ^8.0.1
  eslint-plugin-qunit-dom: mainmatter/eslint-plugin-qunit-dom#d66c841
  eslint-plugin-simple-import-sort: ^8.0.0
  eslint-plugin-typescript-sort-keys: ^3.2.0
  eslint-plugin-unicorn: ^51.0.1
  glimmer-scoped-css: ^0.8.1
  prettier: ^3.5.3
  prettier-plugin-ember-template-tag: ^1.1.0
  qunit: ^2.24.1
  qunit-dom: ^2.0.0
