packages:
  - packages/*
  - packages/boxel-motion/*
  - packages/boxel-ui/*
  - vendor/*
catalog:
  "@types/qunit": 2.11.3
  ember-concurrency: ^4.0.3
  ember-concurrency-ts: ^0.3.1
  ember-qunit: ^8.0.1
  eslint: ^8.57.1
  eslint-doc-generator: ^1.7.1
  eslint-plugin-qunit: ^8.0.1
  eslint-plugin-qunit-dom: mainmatter/eslint-plugin-qunit-dom#d66c841
  qunit: ^2.24.1
  qunit-dom: ^2.0.0
