packages:
  - packages/*
  - packages/boxel-motion/*
  - packages/boxel-ui/*
  - vendor/*
catalog:
  "@actions/core": ^1.2.6
  "@actions/github": ^4.0.0
  "@aws-crypto/sha256-js": ^5.2.0
  "@babel/core": ^7.26.10
  "@babel/eslint-parser": ^7.27.0
  "@babel/generator": ^7.17.8
  "@babel/helper-module-imports": ^7.18.2
  "@babel/helper-module-transforms": ^7.18.9
  "@babel/helper-plugin-utils": ^7.12.13
  "@babel/parser": ^7.23.3
  "@babel/plugin-proposal-class-properties": ^7.18.6
  "@babel/plugin-proposal-decorators": ^7.23.2
  "@babel/plugin-syntax-class-properties": ^7.12.13
  "@babel/plugin-syntax-decorators": ^7.17.12
  "@babel/plugin-syntax-typescript": ^7.17.12
  "@babel/plugin-transform-class-properties": ^7.22.5
  "@babel/plugin-transform-class-static-block": ^7.22.11
  "@babel/plugin-transform-modules-amd": ^7.13.0
  "@babel/plugin-transform-typescript": ^7.22.15
  "@babel/preset-typescript": ^7.24.7
  "@babel/runtime": ^7.22.11
  "@babel/traverse": ^7.17.9
  "@babel/types": ^7.20.0
  "@cardstack/requirejs-monaco-ember-polyfill": ^0.0.1
  "@ember/optional-features": ^2.0.0
  "@ember/string": ^3.1.1
  "@ember/test-helpers": ^3.3.1
  "@ember/test-waiters": ^3.0.2
  "@embroider/addon-dev": ^5.0.0
  "@embroider/addon-shim": ^1.8.9
  "@embroider/compat": ^3.5.5
  "@embroider/core": ^3.4.14
  "@embroider/macros": ^1.16.5
  "@embroider/test-setup": ^4.0.0
  "@embroider/webpack": ^4.0.4
  "@eslint/eslintrc": ^2.1.4
  "@eslint/js": ^8.57.1
  "@floating-ui/dom": ^1.6.3
  "@glimmer/component": ^1.1.2
  "@glimmer/tracking": ^1.1.2
  "@glint/core": 1.3.0
  "@glint/environment-ember-loose": 1.3.0
  "@glint/environment-ember-template-imports": 1.3.0
  "@glint/template": ^1.3.0
  "@koa/cors": ^4.0.0
  "@koa/router": ^12.0.0
  "@lucide/lab": ^0.1.2
  "@lukeed/uuid": ^2.0.1
  "@percy/cli": ^1.30.10
  "@percy/ember": ^4.2.0
  "@playwright/test": ^1.48.0
  "@rollup/plugin-babel": ^6.0.4
  "@sentry/node": ^8.31.0
  "@simple-dom/interface": ^1.4.0
  "@simple-dom/serializer": ^1.4.0
  "@simple-dom/void-map": ^1.4.0
  "@sinonjs/fake-timers": ^11.2.2
  "@sqlite.org/sqlite-wasm": 3.45.1-build1
  "@tabler/icons": ^3.19.0
  "@tsconfig/ember": ^3.0.4
  "@types/babel__core": ^7.1.19
  "@types/babel__generator": ^7.6.4
  "@types/babel__traverse": ^7.14.2
  "@types/diff": ^5.0.2
  "@types/dompurify": ^3.0.2
  "@types/flat": ^5.0.5
  "@types/fs-extra": ~11.0.4
  "@types/htmlbars-inline-precompile": ^3.0.3
  "@types/indefinite": ^2.3.4
  "@types/js-string-escape": ^1.0.1
  "@types/js-yaml": ^4.0.9
  "@types/jsdom": ^21.1.1
  "@types/jsonwebtoken": ^9.0.5
  "@types/koa": ^2.13.5
  "@types/koa__cors": ^4.0.0
  "@types/koa__router": ^12.0.0
  "@types/koa-compose": ^3.2.5
  "@types/line-column": ^1.0.0
  "@types/lodash": ^4.17.15
  "@types/matrix-js-sdk": ^11.0.1
  "@types/mime-types": ^2.1.1
  "@types/ms": ^0.7.34
  "@types/node": ^18.19.39
  "@types/pg": ^8.11.5
  "@types/pluralize": ^0.0.30
  "@types/qs": ^6.9.17
  "@types/qunit": ^2.19.12
  "@types/rsvp": ^4.0.9
  "@types/sane": ^2.0.1
  "@types/sinon": ^17.0.3
  "@types/sinonjs__fake-timers": ^8.1.5
  "@types/statuses": ^2.0.5
  "@types/stream-chain": ^2.0.1
  "@types/stream-json": ^1.7.3
  "@types/string.prototype.matchall": ^4.0.1
  "@types/supertest": ^2.0.12
  "@types/tmp": ^0.2.3
  "@types/uuid": ^9.0.8
  "@types/vscode": ^1.73.0
  "@types/yargs": ^17.0.10
  "@typescript-eslint/eslint-plugin": ^7.18.0
  "@typescript-eslint/parser": ^7.18.0
  "@vscode/vsce": ^3.1.0
  awesome-phonenumber: ^7.2.0
  babel-eslint: ^10.1.0
  babel-import-util: ^1.2.2
  babel-plugin-dynamic-import-node: ^2.3.3
  babel-plugin-ember-template-compilation: ^2.3.0
  broccoli-asset-rev: ^3.0.0
  broccoli-merge-trees: ^4.2.0
  broccoli-plugin: ^4.0.7
  broccoli-source: ^3.0.1
  broccoli-stew: ^3.0.0
  buffer: ^6.0.3
  camelcase: ^6.3.0
  chess.js: 1.0.0-beta.8
  classnames: ^2.3.2
  concurrently: ^8.2.2
  countries-list: ^3.1.1
  crypto-browserify: ^3.12.0
  date-fns: ^2.28.0
  dayjs: ^1.11.7
  decorator-transforms: ^2.3.0
  diff: ^5.1.0
  dompurify: ^3.0.3
  ember-a11y-testing: ^6.1.1
  ember-async-data: ^1.0.3
  ember-auto-import: ^2.7.2
  ember-basic-dropdown: ^8.0.1
  ember-cli: ^5.4.1
  ember-cli-app-version: ^6.0.1
  ember-cli-babel: ^8.2.0
  ember-cli-babel-plugin-helpers: ^1.1.1
  ember-cli-clean-css: ^3.0.0
  ember-cli-dependency-checker: ^3.3.2
  ember-cli-deploy: ^1.0.2
  ember-cli-deploy-build: ^2.0.0
  ember-cli-deploy-cloudfront: ^5.0.0
  ember-cli-deploy-fastboot-s3: ^0.3.6
  ember-cli-deploy-revision-data: ^2.0.0
  ember-cli-deploy-s3: ^3.1.0
  ember-cli-deploy-smart-compress: ^2.0.0
  ember-cli-deprecation-workflow: ^3.0.2
  ember-cli-fastboot: ^4.1.2
  ember-cli-htmlbars: ^6.3.0
  ember-cli-inject-live-reload: ^2.1.0
  ember-cli-sri: ^2.1.1
  ember-cli-terser: ^4.0.2
  ember-cli-typescript: ^5.2.1
  ember-cli-typescript-blueprints: ^3.0.0
  ember-cli-version-checker: ^5.1.2
  ember-click-outside: ^6.0.1
  ember-concurrency: ^4.0.2
  ember-concurrency-ts: ^0.3.1
  ember-css-url: ^1.0.0
  ember-disable-prototype-extensions: ^1.1.3
  ember-draggable-modifiers: ^1.0.0
  ember-elsewhere: ^2.0.0
  ember-eslint-parser: ^0.5.9
  ember-exam: ^9.0.0
  ember-export-application-global: ^2.0.1
  ember-focus-trap: ^1.0.1
  ember-freestyle: ^0.20.0
  ember-keyboard: ^8.2.1
  ember-lifeline: ^7.0.0
  ember-link: ^2.1.0
  ember-load-initializers: ^2.1.2
  ember-maybe-import-regenerator: ^0.1.6
  ember-modifier: ^4.1.0
  ember-moment: ^10.0.0
  ember-page-title: ^8.2.3
  ember-power-calendar: ^1.2.0
  ember-power-calendar-moment: ^1.0.2
  ember-power-select: ^8.0.0
  ember-provide-consume-context: ^0.7.0
  ember-qunit: ^8.0.1
  ember-resize-modifier: ^0.7.1
  ember-resolver: ^11.0.1
  ember-resources: ^6.5.1
  ember-route-template: ^1.0.3
  ember-set-body-class: ^1.0.2
  ember-sortable: ^5.0.2
  ember-source: ~5.4.1
  ember-source-channel-url: ^3.0.0
  ember-template-imports: ^4.1.1
  ember-template-lint: ^5.11.2
  ember-template-lint-plugin-prettier: ^5.0.0
  ember-template-recast: ^6.1.5
  ember-test-selectors: ^6.0.0
  ember-try: ^2.0.0
  ember-velcro: ^2.1.3
  ember-window-mock: ^1.0.1
  esbuild: ^0.24.0
  eslint: ^8.57.1
  eslint-config-prettier: ^9.0.0
  eslint-doc-generator: ^1.7.1
  eslint-plugin-ember: ^12.5.0
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-eslint-plugin: ^5.5.1
  eslint-plugin-filenames: ^1.3.2
  eslint-plugin-import: ^2.31.0
  eslint-plugin-markdown: ^5.1.0
  eslint-plugin-n: ^17.17.0
  eslint-plugin-node: ^11.1.0
  eslint-plugin-prefer-let: ^3.0.1
  eslint-plugin-prettier: ^5.2.6
  eslint-plugin-qunit: ^8.0.1
  eslint-plugin-simple-import-sort: ^8.0.0
  eslint-plugin-typescript-sort-keys: ^3.2.0
  eslint-plugin-unicorn: ^51.0.1
  ethers: ^6.6.2
  fast-json-stable-stringify: ^2.1.0
  fastboot: ^4.1.0
  file-loader: ^6.2.0
  filesize: ^10.0.12
  flat: ^5.0.2
  focus-trap: ^7.4.3
  fs-extra: ~11.3.0
  glimmer-scoped-css: ^0.6.0
  glob: ^11.0.1
  hcl2-parser: ^1.0.3
  http-server: ^14.1.1
  http-status-codes: ^2.2.0
  ignore: ^5.2.0
  indefinite: ^2.4.3
  js-string-escape: ^1.0.1
  js-yaml: ^4.1.0
  jsdom: ^21.1.1
  json-typescript: ^1.1.2
  jsonwebtoken: ^9.0.2
  koa: ^2.14.1
  koa-compose: ^4.1.0
  koa-proxies: ^0.12.3
  line-column: ^1.0.2
  loader.js: ^4.7.0
  lodash: ^4.17.21
  loglevel: ^1.8.1
  lucide-static: ^0.447.0
  macro-decorators: ^0.1.2
  magic-string: 0.25.9
  marked: ^12.0.1
  matrix-js-sdk: ^31.0.0
  mime-types: ^2.1.35
  moment: ^2.29.4
  moment-locales-webpack-plugin: ^1.2.0
  monaco-editor: ^0.52.2
  monaco-editor-webpack-plugin: ^7.1.0
  ms: ^2.1.3
  node-pg-migrate: ^6.2.2
  normalize.css: 8.0.1
  npm-run-all: ^4.1.5
  openai: 4.86.1
  parse-static-imports: ^1.1.0
  path-browserify: ^1.0.1
  pg: ^8.11.5
  pluralize: ^8.0.0
  prettier: ^3.5.2
  prettier-plugin-ember-template-tag: ^1.1.0
  qs: ^6.13.0
  qunit: ^2.20.0
  qunit-dom: ^2.0.0
  recast: ^0.23.4
  release-it: ^14.2.1
  requireindex: ^1.2.0
  rollup: ^4.18.1
  rollup-plugin-copy: ^3.5.0
  safe-stable-stringify: ^2.4.3
  sane: ^5.0.1
  sinon: ^19.0.2
  sql-parser-cst: ^0.28.0
  start-server-and-test: ^1.14.0
  statuses: ^2.0.1
  stream-browserify: ^3.0.0
  stream-chain: ^2.2.5
  stream-json: ^1.8.0
  string.prototype.matchall: ^4.0.6
  stripe: ^17.2.1
  style-value-types: ^5.1.2
  super-fast-md5: ^1.0.1
  supertest: ^6.2.4
  svgo: 3.0.2
  testem: ^3.10.1
  testem-multi-reporter: ^1.2.0
  tmp: ^0.2.1
  tracked-built-ins: ^3.3.0
  ts-node: ^10.9.2
  typescript: ~5.8.3
  typescript-memoize: ^1.1.1
  uuid: ^9.0.1
  validate-peer-dependencies: ^1.1.0
  vite: ^6.3.2
  vitest: ^2.1.9
  wait-for-localhost-cli: ^3.2.0
  webpack: ^5.99.6
  yaml: ^2.5.1
  yargs: ^17.5.1
