#!/bin/sh
#MISE description="Start services for realm-server test suite (icons + host-dist + dev-minimal services)"
#MISE dir="packages/realm-server"

export PATH="./node_modules/.bin:$PATH"

READY_PATH="_readiness-check?acceptHeader=application%2Fvnd.api%2Bjson"
BASE_REALM_READY="http-get://${REALM_BASE_URL#http://}/base/${READY_PATH}"
NODE_TEST_REALM_READY="http-get://${REALM_TEST_URL#http://}/node-test/${READY_PATH}"

WAIT_ON_TIMEOUT=900000 \
  SKIP_EXPERIMENTS=true \
  SKIP_CATALOG=true \
  SKIP_BOXEL_HOMEPAGE=true \
  SKIP_SUBMISSION=true \
  NODE_NO_WARNINGS=1 \
  start-server-and-test \
    'run-p -ln start:icons start:host-dist start:pg start:prerender-dev start:prerender-manager-dev start:matrix start:smtp start:worker-development start:development' \
    "${BASE_REALM_READY}|http-get://${REALM_BASE_URL#http://}/software-factory/${READY_PATH}|${MATRIX_URL_VAL}|http://localhost:5001|${ICONS_URL}|${HOST_URL}" \
    'run-p -ln start:worker-test start:test-realms' \
    "${NODE_TEST_REALM_READY}" \
    'wait'
