import type { ReadableSchema } from '../src/index.js';

export interface BxlExample {
  id: number;
  level: string;
  name: string;
  expression: string;
  expected: unknown;
  compiled: string;
}

export const bxlExampleSchema: ReadableSchema = {
  fields: [
    { key: 'invoiceNumber', label: 'Invoice Number' },
    { key: 'status', label: 'Status' },
    { key: 'subtotal', label: 'Subtotal' },
    { key: 'discountRate', label: 'Discount Rate' },
    { key: 'discountAmount', label: 'Discount Amount' },
    { key: 'taxRate', label: 'Tax Rate' },
    { key: 'taxAmount', label: 'Tax Amount' },
    { key: 'shipping', label: 'Shipping' },
    { key: 'total', label: 'Total' },
    { key: 'dueDays', label: 'Due Days' },
    { key: 'currency', label: 'Currency' },
    { key: 'createdAt', label: 'Created At' },
    {
      key: 'customer',
      label: 'Customer',
      kind: 'object',
      fields: [
        { key: 'name', label: 'Name' },
        { key: 'tier', label: 'Tier' },
        { key: 'countryCode', label: 'Country Code' },
        { key: 'region', label: 'Region' },
        { key: 'creditLimit', label: 'Credit Limit' },
      ],
    },
    {
      key: 'owner',
      label: 'Owner',
      kind: 'object',
      fields: [
        { key: 'name', label: 'Name' },
        { key: 'email', label: 'Email' },
        { key: 'active', label: 'Active' },
      ],
    },
    {
      key: 'lineItems',
      label: 'Line Item',
      kind: 'array',
      item: {
        fields: [
          { key: 'sku', label: 'SKU' },
          { key: 'description', label: 'Description' },
          { key: 'category', label: 'Category' },
          { key: 'quantity', label: 'Quantity' },
          { key: 'unitPrice', label: 'Unit Price' },
          { key: 'discount', label: 'Discount' },
          { key: 'lineTotal', label: 'Line Total' },
          { key: 'taxable', label: 'Taxable' },
          { key: 'warehouse', label: 'Warehouse' },
        ],
      },
    },
    {
      key: 'payments',
      label: 'Payment',
      kind: 'array',
      item: {
        fields: [
          { key: 'method', label: 'Method' },
          { key: 'amount', label: 'Amount' },
          { key: 'status', label: 'Status' },
          { key: 'daysLate', label: 'Days Late' },
          { key: 'reference', label: 'Reference' },
        ],
      },
    },
    {
      key: 'shipments',
      label: 'Shipment',
      kind: 'array',
      item: {
        fields: [
          { key: 'carrier', label: 'Carrier' },
          { key: 'tracking', label: 'Tracking' },
          { key: 'cost', label: 'Cost' },
          { key: 'days', label: 'Days' },
          { key: 'delivered', label: 'Delivered' },
        ],
      },
    },
  ],
};

export const bxlExampleInput = {
  invoiceNumber: 'INV-1001',
  status: 'open',
  subtotal: 80,
  discountRate: 0.1,
  discountAmount: 8,
  taxRate: 8.25,
  taxAmount: 4.54,
  shipping: 12.5,
  total: 89.04,
  dueDays: 30,
  currency: 'USD',
  createdAt: '2026-04-22',
  customer: {
    name: 'Acme Legal',
    tier: 'gold',
    countryCode: 'US',
    region: 'North America',
    creditLimit: 500,
  },
  owner: {
    name: 'Morgan Lee',
    email: 'morgan@example.test',
    active: true,
  },
  lineItems: [
    {
      sku: 'PAPER-01',
      description: 'Office Paper',
      category: 'Supplies',
      quantity: 2,
      unitPrice: 5,
      discount: 0,
      lineTotal: 10,
      taxable: true,
      warehouse: 'East',
    },
    {
      sku: 'BRAND-RED',
      description: 'Red Brand Kit',
      category: 'Marketing',
      quantity: 5,
      unitPrice: 2,
      discount: 0,
      lineTotal: 10,
      taxable: false,
      warehouse: 'West',
    },
    {
      sku: 'COPY-03',
      description: 'Copy Toner',
      category: 'Supplies',
      quantity: 3,
      unitPrice: 4,
      discount: 0,
      lineTotal: 12,
      taxable: true,
      warehouse: 'East',
    },
    {
      sku: 'COPY-04',
      description: 'Copy Desk Service',
      category: 'Service',
      quantity: 9,
      unitPrice: 2,
      discount: 0,
      lineTotal: 18,
      taxable: true,
      warehouse: 'North',
    },
    {
      sku: 'SRV-01',
      description: 'Setup Service',
      category: 'Service',
      quantity: 1,
      unitPrice: 15,
      discount: 0,
      lineTotal: 15,
      taxable: false,
      warehouse: 'North',
    },
    {
      sku: 'HARD-02',
      description: 'Laptop Stand',
      category: 'Hardware',
      quantity: 2,
      unitPrice: 7.5,
      discount: 0,
      lineTotal: 15,
      taxable: true,
      warehouse: 'West',
    },
  ],
  payments: [
    {
      method: 'card',
      amount: 30,
      status: 'captured',
      daysLate: 0,
      reference: 'PAY-1',
    },
    {
      method: 'ach',
      amount: 25,
      status: 'pending',
      daysLate: 2,
      reference: 'PAY-2',
    },
    {
      method: 'check',
      amount: 10,
      status: 'failed',
      daysLate: 15,
      reference: 'PAY-3',
    },
  ],
  shipments: [
    {
      carrier: 'UPS',
      tracking: '1Z100',
      cost: 7.5,
      days: 2,
      delivered: true,
    },
    {
      carrier: 'FedEx',
      tracking: 'FX200',
      cost: 5,
      days: 5,
      delivered: false,
    },
    {
      carrier: 'Courier',
      tracking: 'CO300',
      cost: 0,
      days: 0,
      delivered: false,
    },
  ],
};

export const bxlExamples: BxlExample[] = [
  { id: 1, level: '01 scalar', name: 'invoice number label', expression: '"Invoice Number"', expected: 'INV-1001', compiled: ".invoiceNumber" },
  { id: 2, level: '01 scalar', name: 'bare status label', expression: 'Status', expected: 'open', compiled: ".status" },
  { id: 3, level: '01 scalar', name: 'bare subtotal label', expression: 'Subtotal', expected: 80, compiled: ".subtotal" },
  { id: 4, level: '01 scalar', name: 'quoted tax rate label', expression: '"Tax Rate"', expected: 8.25, compiled: ".taxRate" },
  { id: 5, level: '01 scalar', name: 'quoted discount amount label', expression: '"Discount Amount"', expected: 8, compiled: ".discountAmount" },
  { id: 6, level: '01 scalar', name: 'quoted shipping label', expression: 'Shipping', expected: 12.5, compiled: ".shipping" },
  { id: 7, level: '01 scalar', name: 'bare total label', expression: 'Total', expected: 89.04, compiled: ".total" },
  { id: 8, level: '01 scalar', name: 'due days label', expression: '"Due Days"', expected: 30, compiled: ".dueDays" },
  { id: 9, level: '01 scalar', name: 'currency label', expression: 'Currency', expected: 'USD', compiled: ".currency" },
  { id: 10, level: '01 scalar', name: 'created date label', expression: '"Created At"', expected: '2026-04-22', compiled: ".createdAt" },
  { id: 11, level: '02 nested object', name: 'customer name', expression: 'Customer.Name', expected: 'Acme Legal', compiled: ".customer.name" },
  { id: 12, level: '02 nested object', name: 'customer tier', expression: 'Customer.Tier', expected: 'gold', compiled: ".customer.tier" },
  { id: 13, level: '02 nested object', name: 'customer country code', expression: 'Customer."Country Code"', expected: 'US', compiled: ".customer.countryCode" },
  { id: 14, level: '02 nested object', name: 'customer region', expression: 'Customer.Region', expected: 'North America', compiled: ".customer.region" },
  { id: 15, level: '02 nested object', name: 'customer credit limit', expression: 'Customer."Credit Limit"', expected: 500, compiled: ".customer.creditLimit" },
  { id: 16, level: '02 nested object', name: 'owner name', expression: 'Owner.Name', expected: 'Morgan Lee', compiled: ".owner.name" },
  { id: 17, level: '02 nested object', name: 'owner email', expression: 'Owner.Email', expected: 'morgan@example.test', compiled: ".owner.email" },
  { id: 18, level: '02 nested object', name: 'owner active flag', expression: 'Owner.Active', expected: true, compiled: ".owner.active" },
  { id: 19, level: '02 nested object', name: 'nested equality true', expression: 'Customer.Tier == "gold"', expected: true, compiled: ".customer.tier == \"gold\"" },
  { id: 20, level: '02 nested object', name: 'nested equality false', expression: 'Owner.Active == false', expected: false, compiled: ".owner.active == false" },
  { id: 21, level: '03 row access', name: 'first row sku by row', expression: '"Line Item"[row 1].SKU', expected: 'PAPER-01', compiled: ".lineItems[0].sku" },
  { id: 22, level: '03 row access', name: 'second row sku by row', expression: '"Line Item"[row 2].SKU', expected: 'BRAND-RED', compiled: ".lineItems[1].sku" },
  { id: 23, level: '03 row access', name: 'third row description', expression: '"Line Item"[row 3].Description', expected: 'Copy Toner', compiled: ".lineItems[2].description" },
  { id: 24, level: '03 row access', name: 'fourth row quantity', expression: '"Line Item"[row 4].Quantity', expected: 9, compiled: ".lineItems[3].quantity" },
  { id: 25, level: '03 row access', name: 'fifth row category', expression: '"Line Item"[row 5].Category', expected: 'Service', compiled: ".lineItems[4].category" },
  { id: 26, level: '03 row access', name: 'sixth row unit price', expression: '"Line Item"[row 6]."Unit Price"', expected: 7.5, compiled: ".lineItems[5].unitPrice" },
  { id: 27, level: '03 row access', name: 'hash one-based first row', expression: '"Line Item"[#1].SKU', expected: 'PAPER-01', compiled: ".lineItems[0].sku" },
  { id: 28, level: '03 row access', name: 'hash one-based fourth row', expression: '"Line Item"[#4].SKU', expected: 'COPY-04', compiled: ".lineItems[3].sku" },
  { id: 29, level: '03 row access', name: 'last selector sku', expression: '"Line Item"[#last].SKU', expected: 'HARD-02', compiled: ".lineItems[-1].sku" },
  { id: 30, level: '03 row access', name: 'last minus one sku', expression: '"Line Item"[#last-1].SKU', expected: 'SRV-01', compiled: ".lineItems[-2].sku" },
  { id: 31, level: '04 positional selectors', name: 'first selector sku', expression: '"Line Item"[#first].SKU', expected: 'PAPER-01', compiled: ".lineItems[0].sku" },
  { id: 32, level: '04 positional selectors', name: 'last selector sku', expression: '"Line Item"[#last].SKU', expected: 'HARD-02', compiled: ".lineItems[-1].sku" },
  { id: 33, level: '04 positional selectors', name: 'third selector sku', expression: '"Line Item"[#3].SKU', expected: 'COPY-03', compiled: ".lineItems[2].sku" },
  { id: 34, level: '04 positional selectors', name: 'last element via negative selector', expression: '"Line Item"[#-1].SKU', expected: 'HARD-02', compiled: ".lineItems[-1].sku" },
  { id: 35, level: '04 positional selectors', name: 'second from end selector', expression: '"Line Item"[#last-1].SKU', expected: 'SRV-01', compiled: ".lineItems[-2].sku" },
  { id: 36, level: '04 positional selectors', name: 'first line total', expression: '"Line Item"[#first]."Line Total"', expected: 10, compiled: ".lineItems[0].lineTotal" },
  { id: 37, level: '04 positional selectors', name: 'last line total', expression: '"Line Item"[#last]."Line Total"', expected: 15, compiled: ".lineItems[-1].lineTotal" },
  { id: 38, level: '04 positional selectors', name: 'fourth selector quantity', expression: '"Line Item"[#4].Quantity', expected: 9, compiled: ".lineItems[3].quantity" },
  { id: 39, level: '04 positional selectors', name: 'second payment method', expression: 'Payment[#2].Method', expected: 'ach', compiled: ".payments[1].method" },
  { id: 40, level: '04 positional selectors', name: 'last shipment carrier', expression: 'Shipment[#last].Carrier', expected: 'Courier', compiled: ".shipments[-1].carrier" },
  { id: 41, level: '05 materialized arrays', name: 'all skus', expression: '"Line Item"[all].SKU', expected: ['PAPER-01', 'BRAND-RED', 'COPY-03', 'COPY-04', 'SRV-01', 'HARD-02'], compiled: "[.lineItems[].sku]" },
  { id: 42, level: '05 materialized arrays', name: 'all quantities', expression: '"Line Item"[all].Quantity', expected: [2, 5, 3, 9, 1, 2], compiled: "[.lineItems[].quantity]" },
  { id: 43, level: '05 materialized arrays', name: 'all line totals', expression: '"Line Item"[all]."Line Total"', expected: [10, 10, 12, 18, 15, 15], compiled: "[.lineItems[].lineTotal]" },
  { id: 44, level: '05 materialized arrays', name: 'all categories', expression: '"Line Item"[all].Category', expected: ['Supplies', 'Marketing', 'Supplies', 'Service', 'Service', 'Hardware'], compiled: "[.lineItems[].category]" },
  { id: 45, level: '05 materialized arrays', name: 'all taxable flags', expression: '"Line Item"[all].Taxable', expected: [true, false, true, true, false, true], compiled: "[.lineItems[].taxable]" },
  { id: 46, level: '05 materialized arrays', name: 'all warehouses', expression: '"Line Item"[all].Warehouse', expected: ['East', 'West', 'East', 'North', 'North', 'West'], compiled: "[.lineItems[].warehouse]" },
  { id: 47, level: '05 materialized arrays', name: 'all payment amounts', expression: 'Payment[all].Amount', expected: [30, 25, 10], compiled: "[.payments[].amount]" },
  { id: 48, level: '05 materialized arrays', name: 'all payment statuses', expression: 'Payment[all].Status', expected: ['captured', 'pending', 'failed'], compiled: "[.payments[].status]" },
  { id: 49, level: '05 materialized arrays', name: 'all shipment costs', expression: 'Shipment[all].Cost', expected: [7.5, 5, 0], compiled: "[.shipments[].cost]" },
  { id: 50, level: '05 materialized arrays', name: 'all shipment delivered flags', expression: 'Shipment[all].Delivered', expected: [true, false, false], compiled: "[.shipments[].delivered]" },
  { id: 51, level: '06 ranges and slices', name: 'first two row skus', expression: '"Line Item"[row 1..2].SKU', expected: ['PAPER-01', 'BRAND-RED'], compiled: "[(.lineItems) as $__seq | $__seq[0:2][].sku]" },
  { id: 52, level: '06 ranges and slices', name: 'middle row skus', expression: '"Line Item"[row 2..4].SKU', expected: ['BRAND-RED', 'COPY-03', 'COPY-04'], compiled: "[(.lineItems) as $__seq | $__seq[1:4][].sku]" },
  { id: 53, level: '06 ranges and slices', name: 'last two via canonical slice', expression: '"Line Item"[4:6].SKU', expected: ['SRV-01', 'HARD-02'], compiled: "[(.lineItems) as $__seq | $__seq[4:6][].sku]" },
  { id: 54, level: '06 ranges and slices', name: 'first three quantities', expression: '"Line Item"[row 1..3].Quantity', expected: [2, 5, 3], compiled: "[(.lineItems) as $__seq | $__seq[0:3][].quantity]" },
  { id: 55, level: '06 ranges and slices', name: 'service rows totals by range', expression: '"Line Item"[row 4..5]."Line Total"', expected: [18, 15], compiled: "[(.lineItems) as $__seq | $__seq[3:5][].lineTotal]" },
  { id: 56, level: '06 ranges and slices', name: 'payment first two amounts', expression: 'Payment[row 1..2].Amount', expected: [30, 25], compiled: "[(.payments) as $__seq | $__seq[0:2][].amount]" },
  { id: 57, level: '06 ranges and slices', name: 'shipment first two carriers', expression: 'Shipment[row 1..2].Carrier', expected: ['UPS', 'FedEx'], compiled: "[(.shipments) as $__seq | $__seq[0:2][].carrier]" },
  { id: 58, level: '06 ranges and slices', name: 'line items canonical slice length', expression: '"Line Item"[1:4] | length', expected: 3, compiled: "[(.lineItems) as $__seq | $__seq[1:4][]] | length" },
  { id: 59, level: '06 ranges and slices', name: 'payment range length', expression: 'Payment[row 1..3] | length', expected: 3, compiled: "[(.payments) as $__seq | $__seq[0:3][]] | length" },
  { id: 60, level: '06 ranges and slices', name: 'shipment range days', expression: 'Shipment[row 1..2].Days', expected: [2, 5], compiled: "[(.shipments) as $__seq | $__seq[0:2][].days]" },
  { id: 61, level: '07 predicates', name: 'sku equality quantity', expression: '"Line Item"[SKU = "COPY-04"].Quantity', expected: 9, compiled: "first(.lineItems[] | select(.sku == \"COPY-04\")).quantity" },
  { id: 62, level: '07 predicates', name: 'category equality sku', expression: '"Line Item"[Category = "Hardware"].SKU', expected: 'HARD-02', compiled: "first(.lineItems[] | select(.category == \"Hardware\")).sku" },
  { id: 63, level: '07 predicates', name: 'warehouse equality sku', expression: '"Line Item"[Warehouse = "North"].SKU', expected: 'COPY-04', compiled: "first(.lineItems[] | select(.warehouse == \"North\")).sku" },
  { id: 64, level: '07 predicates', name: 'quantity greater sku', expression: '"Line Item"[Quantity > 4].SKU', expected: 'BRAND-RED', compiled: "first(.lineItems[] | select(.quantity > 4)).sku" },
  { id: 65, level: '07 predicates', name: 'line total greater sku', expression: '"Line Item"["Line Total" > 14].SKU', expected: 'COPY-04', compiled: "first(.lineItems[] | select(.lineTotal > 14)).sku" },
  { id: 66, level: '07 predicates', name: 'taxable true sku', expression: '"Line Item"[Taxable = true].SKU', expected: 'PAPER-01', compiled: "first(.lineItems[] | select(.taxable == true)).sku" },
  { id: 67, level: '07 predicates', name: 'taxable false sku', expression: '"Line Item"[Taxable = false].SKU', expected: 'BRAND-RED', compiled: "first(.lineItems[] | select(.taxable == false)).sku" },
  { id: 68, level: '07 predicates', name: 'payment captured amount', expression: 'Payment[Status = "captured"].Amount', expected: 30, compiled: "first(.payments[] | select(.status == \"captured\")).amount" },
  { id: 69, level: '07 predicates', name: 'payment late greater reference', expression: 'Payment["Days Late" > 10].Reference', expected: 'PAY-3', compiled: "first(.payments[] | select(.daysLate > 10)).reference" },
  { id: 70, level: '07 predicates', name: 'shipment not delivered carrier', expression: 'Shipment[Delivered = false].Carrier', expected: 'FedEx', compiled: "first(.shipments[] | select(.delivered == false)).carrier" },
  { id: 71, level: '08 string predicates', name: 'sku starts with copy pipe', expression: '"Line Item"[SKU | startswith("COPY")].SKU', expected: 'COPY-03', compiled: "first(.lineItems[] | select(.sku | startswith(\"COPY\"))).sku" },
  { id: 72, level: '08 string predicates', name: 'sku starts with brand pipe', expression: '"Line Item"[SKU | startswith("BRAND")].SKU', expected: 'BRAND-RED', compiled: "first(.lineItems[] | select(.sku | startswith(\"BRAND\"))).sku" },
  { id: 73, level: '08 string predicates', name: 'sku ends with red pipe', expression: '"Line Item"[SKU | endswith("RED")].SKU', expected: 'BRAND-RED', compiled: "first(.lineItems[] | select(.sku | endswith(\"RED\"))).sku" },
  { id: 74, level: '08 string predicates', name: 'owner email ends with test pipe', expression: 'Owner.Email | endswith(".test")', expected: true, compiled: ".owner.email | endswith(\".test\")" },
  { id: 75, level: '08 string predicates', name: 'description contains service pipe', expression: '"Line Item"[Description | contains("Service")].SKU', expected: 'COPY-04', compiled: "first(.lineItems[] | select(.description | contains(\"Service\"))).sku" },
  { id: 76, level: '08 string predicates', name: 'customer name contains legal pipe', expression: 'Customer.Name | contains("Legal")', expected: true, compiled: ".customer.name | contains(\"Legal\")" },
  { id: 77, level: '08 string predicates', name: 'payment reference starts with pay pipe', expression: 'Payment[Reference | startswith("PAY")].Method', expected: 'card', compiled: "first(.payments[] | select(.reference | startswith(\"PAY\"))).method" },
  { id: 78, level: '08 string predicates', name: 'shipment tracking starts with fx pipe', expression: 'Shipment[Tracking | startswith("FX")].Carrier', expected: 'FedEx', compiled: "first(.shipments[] | select(.tracking | startswith(\"FX\"))).carrier" },
  { id: 79, level: '08 string predicates', name: 'customer name contains legal', expression: 'Customer.Name | contains("Legal")', expected: true, compiled: ".customer.name | contains(\"Legal\")" },
  { id: 80, level: '08 string predicates', name: 'owner email ends with test', expression: 'Owner.Email | endswith(".test")', expected: true, compiled: ".owner.email | endswith(\".test\")" },
  { id: 81, level: '09 arithmetic', name: 'subtotal plus shipping', expression: 'Subtotal + Shipping', expected: 92.5, compiled: ".subtotal + .shipping" },
  { id: 82, level: '09 arithmetic', name: 'subtotal minus discount', expression: 'Subtotal - "Discount Amount"', expected: 72, compiled: ".subtotal - .discountAmount" },
  { id: 83, level: '09 arithmetic', name: 'total recompute simple', expression: 'Subtotal - "Discount Amount" + "Tax Amount" + Shipping', expected: 89.04, compiled: ".subtotal - .discountAmount + .taxAmount + .shipping" },
  { id: 84, level: '09 arithmetic', name: 'first row extended price', expression: '"Line Item"[row 1].Quantity * "Line Item"[row 1]."Unit Price"', expected: 10, compiled: ".lineItems[0].quantity * .lineItems[0].unitPrice" },
  { id: 85, level: '09 arithmetic', name: 'fourth row extended price', expression: '"Line Item"[row 4].Quantity * "Line Item"[row 4]."Unit Price"', expected: 18, compiled: ".lineItems[3].quantity * .lineItems[3].unitPrice" },
  { id: 86, level: '09 arithmetic', name: 'payment balance simple', expression: 'ROUND(Total - Payment[Status = "captured"].Amount, 2)', expected: 59.04, compiled: "ROUND(.total - first(.payments[] | select(.status == \"captured\")).amount; 2)" },
  { id: 87, level: '09 arithmetic', name: 'shipping per shipment', expression: 'Shipping / (Shipment[all] | length)', expected: 4.166666666666667, compiled: ".shipping /([.shipments[]] | length)" },
  { id: 88, level: '09 arithmetic', name: 'discount percent as whole number', expression: '"Discount Rate" * 100', expected: 10, compiled: ".discountRate * 100" },
  { id: 89, level: '09 arithmetic', name: 'credit remaining', expression: 'Customer."Credit Limit" - Total', expected: 410.96, compiled: ".customer.creditLimit - .total" },
  { id: 90, level: '09 arithmetic', name: 'due days plus grace', expression: '"Due Days" + 5', expected: 35, compiled: ".dueDays + 5" },
  { id: 91, level: '10 formulas and aggregations', name: 'sum line totals', expression: '"Line Item"[all]."Line Total" | add', expected: 80, compiled: "[.lineItems[].lineTotal] | add" },
  { id: 92, level: '10 formulas and aggregations', name: 'sum quantities', expression: '"Line Item"[all].Quantity | add', expected: 22, compiled: "[.lineItems[].quantity] | add" },
  { id: 93, level: '10 formulas and aggregations', name: 'count line items', expression: '"Line Item"[all] | length', expected: 6, compiled: "[.lineItems[]] | length" },
  { id: 94, level: '10 formulas and aggregations', name: 'count payments', expression: 'Payment[all] | length', expected: 3, compiled: "[.payments[]] | length" },
  { id: 95, level: '10 formulas and aggregations', name: 'count shipments', expression: 'Shipment[all] | length', expected: 3, compiled: "[.shipments[]] | length" },
  { id: 96, level: '10 formulas and aggregations', name: 'max line total', expression: '"Line Item"[all]."Line Total" | max', expected: 18, compiled: "[.lineItems[].lineTotal] | max" },
  { id: 97, level: '10 formulas and aggregations', name: 'min unit price', expression: '"Line Item"[all]."Unit Price" | min', expected: 2, compiled: "[.lineItems[].unitPrice] | min" },
  { id: 98, level: '10 formulas and aggregations', name: 'average quantity', expression: '("Line Item"[all].Quantity | add) / ("Line Item"[all] | length)', expected: 3.6666666666666665, compiled: "([.lineItems[].quantity] | add) /([.lineItems[]] | length)" },
  { id: 99, level: '10 formulas and aggregations', name: 'round average quantity', expression: 'ROUND(("Line Item"[all].Quantity | add) / ("Line Item"[all] | length), 2)', expected: 3.67, compiled: "ROUND(([.lineItems[].quantity] | add) /([.lineItems[]] | length); 2)" },
  { id: 100, level: '10 formulas and aggregations', name: 'round taxable amount', expression: 'ROUND(("Line Item"[Taxable = true]."Line Total" + "Line Item"[SKU = "COPY-03"]."Line Total" + "Line Item"[SKU = "COPY-04"]."Line Total" + "Line Item"[SKU = "HARD-02"]."Line Total") * "Tax Rate" / 100, 2)', expected: 4.54, compiled: "ROUND((first(.lineItems[] | select(.taxable == true)).lineTotal + first(.lineItems[] | select(.sku == \"COPY-03\")).lineTotal + first(.lineItems[] | select(.sku == \"COPY-04\")).lineTotal + first(.lineItems[] | select(.sku == \"HARD-02\")).lineTotal) * .taxRate / 100; 2)" },
  { id: 101, level: '11 comparisons', name: 'subtotal matches line total sum', expression: '"Line Item"[all]."Line Total" | add == Subtotal', expected: true, compiled: ". as $root | [.lineItems[].lineTotal] | add == $root.subtotal" },
  { id: 102, level: '11 comparisons', name: 'total matches recompute rounded', expression: 'ROUND(Subtotal - "Discount Amount" + "Tax Amount" + Shipping, 2) == Total', expected: true, compiled: "ROUND(.subtotal - .discountAmount + .taxAmount + .shipping; 2) == .total" },
  { id: 103, level: '11 comparisons', name: 'customer credit covers total', expression: 'Customer."Credit Limit" > Total', expected: true, compiled: ".customer.creditLimit > .total" },
  { id: 104, level: '11 comparisons', name: 'tax rate greater than zero', expression: '"Tax Rate" > 0', expected: true, compiled: ".taxRate > 0" },
  { id: 105, level: '11 comparisons', name: 'discount rate below twenty percent', expression: '"Discount Rate" < 0.2', expected: true, compiled: ".discountRate < 0.2" },
  { id: 106, level: '11 comparisons', name: 'shipping above shipment costs', expression: 'Shipping >= (Shipment[all].Cost | add)', expected: true, compiled: ".shipping >=([.shipments[].cost] | add)" },
  { id: 107, level: '11 comparisons', name: 'captured payment less than total', expression: 'Payment[Status = "captured"].Amount < Total', expected: true, compiled: "first(.payments[] | select(.status == \"captured\")).amount < .total" },
  { id: 108, level: '11 comparisons', name: 'failed payment late check', expression: 'Payment[Status = "failed"]."Days Late" >= 15', expected: true, compiled: "first(.payments[] | select(.status == \"failed\")).daysLate >= 15" },
  { id: 109, level: '11 comparisons', name: 'line count equals six', expression: '("Line Item"[all] | length) == 6', expected: true, compiled: "([.lineItems[]] | length) == 6" },
  { id: 110, level: '11 comparisons', name: 'shipment count equals three', expression: '(Shipment[all] | length) == 3', expected: true, compiled: "([.shipments[]] | length) == 3" },
  { id: 111, level: '12 logic', name: 'open gold customer', expression: 'Status == "open" and Customer.Tier == "gold"', expected: true, compiled: ".status == \"open\" and .customer.tier == \"gold\"" },
  { id: 112, level: '12 logic', name: 'owner active and us customer', expression: 'Owner.Active and Customer."Country Code" == "US"', expected: true, compiled: ".owner.active and .customer.countryCode == \"US\"" },
  { id: 113, level: '12 logic', name: 'high total or gold tier', expression: 'Total > 100 or Customer.Tier == "gold"', expected: true, compiled: ".total > 100 or .customer.tier == \"gold\"" },
  { id: 114, level: '12 logic', name: 'not closed', expression: 'Status != "closed"', expected: true, compiled: ".status != \"closed\"" },
  { id: 115, level: '12 logic', name: 'discounted and taxable', expression: '"Discount Amount" > 0 and "Tax Amount" > 0', expected: true, compiled: ".discountAmount > 0 and .taxAmount > 0" },
  { id: 116, level: '12 logic', name: 'shipping required', expression: 'Shipping > 0 and (Shipment[all] | length) > 0', expected: true, compiled: ".shipping > 0 and ([.shipments[]] | length) > 0" },
  { id: 117, level: '12 logic', name: 'no over credit', expression: 'not (Total > Customer."Credit Limit")', expected: true, compiled: "((.total > .customer.creditLimit) | not)" },
  { id: 118, level: '12 logic', name: 'pending or failed payment exists', expression: 'Payment[Status = "pending"].Amount > 0 or Payment[Status = "failed"].Amount > 0', expected: true, compiled: "first(.payments[] | select(.status == \"pending\")).amount > 0 or first(.payments[] | select(.status == \"failed\")).amount > 0" },
  { id: 119, level: '12 logic', name: 'copy item and service item exist', expression: '"Line Item"[SKU | startswith("COPY")].Quantity > 0 and "Line Item"[Category = "Service"].Quantity > 0', expected: true, compiled: "first(.lineItems[] | select(.sku | startswith(\"COPY\"))).quantity > 0 and first(.lineItems[] | select(.category == \"Service\")).quantity > 0" },
  { id: 120, level: '12 logic', name: 'delivered shipment exists', expression: 'Shipment[Delivered = true].Days > 0', expected: true, compiled: "first(.shipments[] | select(.delivered == true)).days > 0" },
  { id: 121, level: '13 all and any', name: 'all quantities positive', expression: 'all("Line Item"[], Quantity > 0)', expected: true, compiled: "all(.lineItems[]; .quantity > 0)" },
  { id: 122, level: '13 all and any', name: 'all totals non-negative', expression: 'all("Line Item"[], "Line Total" >= 0)', expected: true, compiled: "all(.lineItems[]; .lineTotal >= 0)" },
  { id: 123, level: '13 all and any', name: 'any copy sku', expression: 'any("Line Item"[], SKU | startswith("COPY"))', expected: true, compiled: "any(.lineItems[]; .sku | startswith(\"COPY\"))" },
  { id: 124, level: '13 all and any', name: 'any hardware category', expression: 'any("Line Item"[], Category = "Hardware")', expected: true, compiled: "any(.lineItems[]; .category == \"Hardware\")" },
  { id: 125, level: '13 all and any', name: 'all payment amounts positive', expression: 'all(Payment[], Amount > 0)', expected: true, compiled: "all(.payments[]; .amount > 0)" },
  { id: 126, level: '13 all and any', name: 'any pending payment', expression: 'any(Payment[], Status = "pending")', expected: true, compiled: "any(.payments[]; .status == \"pending\")" },
  { id: 127, level: '13 all and any', name: 'any failed payment late', expression: 'any(Payment[], Status = "failed" and "Days Late" > 10)', expected: true, compiled: "any(.payments[]; (.status == \"failed\") and (.daysLate > 10))" },
  { id: 128, level: '13 all and any', name: 'all shipment costs nonnegative', expression: 'all(Shipment[], Cost >= 0)', expected: true, compiled: "all(.shipments[]; .cost >= 0)" },
  { id: 129, level: '13 all and any', name: 'any undelivered shipment', expression: 'any(Shipment[], Delivered = false)', expected: true, compiled: "any(.shipments[]; .delivered == false)" },
  { id: 130, level: '13 all and any', name: 'all shipment days under week', expression: 'all(Shipment[], Days <= 5)', expected: true, compiled: "all(.shipments[]; .days <= 5)" },
  { id: 131, level: '14 construction', name: 'invoice summary object', expression: '{ invoice: "Invoice Number", status: Status, total: Total }', expected: { invoice: 'INV-1001', status: 'open', total: 89.04 }, compiled: "{invoice:.invoiceNumber, status:.status, total:.total}" },
  { id: 132, level: '14 construction', name: 'customer summary object', expression: '{ customer: Customer.Name, tier: Customer.Tier, country: Customer."Country Code" }', expected: { customer: 'Acme Legal', tier: 'gold', country: 'US' }, compiled: "{customer:.customer.name, tier:.customer.tier, country:.customer.countryCode}" },
  { id: 133, level: '14 construction', name: 'owner summary object', expression: '{ owner: Owner.Name, email: Owner.Email, active: Owner.Active }', expected: { owner: 'Morgan Lee', email: 'morgan@example.test', active: true }, compiled: "{owner:.owner.name, email:.owner.email, active:.owner.active}" },
  { id: 134, level: '14 construction', name: 'totals object', expression: '{ subtotal: Subtotal, discount: "Discount Amount", tax: "Tax Amount", shipping: Shipping, total: Total }', expected: { subtotal: 80, discount: 8, tax: 4.54, shipping: 12.5, total: 89.04 }, compiled: "{subtotal:.subtotal, discount:.discountAmount, tax:.taxAmount, shipping:.shipping, total:.total}" },
  { id: 135, level: '14 construction', name: 'first item object', expression: '{ sku: "Line Item"[#first].SKU, quantity: "Line Item"[#first].Quantity, total: "Line Item"[#first]."Line Total" }', expected: { sku: 'PAPER-01', quantity: 2, total: 10 }, compiled: "{sku:.lineItems[0].sku, quantity:.lineItems[0].quantity, total:.lineItems[0].lineTotal}" },
  { id: 136, level: '14 construction', name: 'last item object', expression: '{ sku: "Line Item"[#last].SKU, category: "Line Item"[#last].Category, warehouse: "Line Item"[#last].Warehouse }', expected: { sku: 'HARD-02', category: 'Hardware', warehouse: 'West' }, compiled: "{sku:.lineItems[-1].sku, category:.lineItems[-1].category, warehouse:.lineItems[-1].warehouse}" },
  { id: 137, level: '14 construction', name: 'selected item object', expression: '{ sku: "Line Item"[SKU = "COPY-04"].SKU, quantity: "Line Item"[SKU = "COPY-04"].Quantity, total: "Line Item"[SKU = "COPY-04"]."Line Total" }', expected: { sku: 'COPY-04', quantity: 9, total: 18 }, compiled: "{sku:first(.lineItems[] | select(.sku == \"COPY-04\")).sku, quantity:first(.lineItems[] | select(.sku == \"COPY-04\")).quantity, total:first(.lineItems[] | select(.sku == \"COPY-04\")).lineTotal}" },
  { id: 138, level: '14 construction', name: 'payment object', expression: '{ method: Payment[Status = "captured"].Method, amount: Payment[Status = "captured"].Amount }', expected: { method: 'card', amount: 30 }, compiled: "{method:first(.payments[] | select(.status == \"captured\")).method, amount:first(.payments[] | select(.status == \"captured\")).amount}" },
  { id: 139, level: '14 construction', name: 'shipment object', expression: '{ carrier: Shipment[Delivered = true].Carrier, cost: Shipment[Delivered = true].Cost }', expected: { carrier: 'UPS', cost: 7.5 }, compiled: "{carrier:first(.shipments[] | select(.delivered == true)).carrier, cost:first(.shipments[] | select(.delivered == true)).cost}" },
  { id: 140, level: '14 construction', name: 'array of headline values', expression: '["Invoice Number", Customer.Name, Total]', expected: ['INV-1001', 'Acme Legal', 89.04], compiled: "[.invoiceNumber, .customer.name, .total]" },
  { id: 141, level: '15 control flow', name: 'status badge', expression: 'if Status == "open" then "needs payment" else "done" end', expected: 'needs payment', compiled: "if .status == \"open\" then \"needs payment\" else \"done\" end" },
  { id: 142, level: '15 control flow', name: 'tier badge', expression: 'if Customer.Tier == "gold" then "priority" else "standard" end', expected: 'priority', compiled: "if .customer.tier == \"gold\" then \"priority\" else \"standard\" end" },
  { id: 143, level: '15 control flow', name: 'credit decision', expression: 'if Total <= Customer."Credit Limit" then "approved" else "hold" end', expected: 'approved', compiled: "if .total <= .customer.creditLimit then \"approved\" else \"hold\" end" },
  { id: 144, level: '15 control flow', name: 'payment decision', expression: 'if Payment[Status = "failed"].Amount > 0 then "investigate" else "ok" end', expected: 'investigate', compiled: "if first(.payments[] | select(.status == \"failed\")).amount > 0 then \"investigate\" else \"ok\" end" },
  { id: 145, level: '15 control flow', name: 'shipping decision', expression: 'if any(Shipment[], Delivered = false) then "in transit" else "complete" end', expected: 'in transit', compiled: "if any(.shipments[]; .delivered == false) then \"in transit\" else \"complete\" end" },
  { id: 146, level: '15 composed', name: 'computed grand total object', expression: '{ invoice: "Invoice Number", computed: ROUND(Subtotal - "Discount Amount" + "Tax Amount" + Shipping, 2), stored: Total, matches: ROUND(Subtotal - "Discount Amount" + "Tax Amount" + Shipping, 2) == Total }', expected: { invoice: 'INV-1001', computed: 89.04, stored: 89.04, matches: true }, compiled: "{invoice:.invoiceNumber, computed:ROUND(.subtotal - .discountAmount + .taxAmount + .shipping; 2), stored:.total, matches:ROUND(.subtotal - .discountAmount + .taxAmount + .shipping; 2) == .total}" },
  { id: 147, level: '15 composed', name: 'receivables object', expression: '{ total: Total, captured: Payment[Status = "captured"].Amount, balance: ROUND(Total - Payment[Status = "captured"].Amount, 2) }', expected: { total: 89.04, captured: 30, balance: 59.04 }, compiled: "{total:.total, captured:first(.payments[] | select(.status == \"captured\")).amount, balance:ROUND(.total - first(.payments[] | select(.status == \"captured\")).amount; 2)}" },
  { id: 148, level: '15 composed', name: 'line health object', expression: '{ count: ("Line Item"[all] | length), quantityTotal: ("Line Item"[all].Quantity | add), allPositive: all("Line Item"[], Quantity > 0), anyCopy: any("Line Item"[], SKU | startswith("COPY")) }', expected: { count: 6, quantityTotal: 22, allPositive: true, anyCopy: true }, compiled: "{count:([.lineItems[]] | length), quantityTotal:([.lineItems[].quantity] | add), allPositive:all(.lineItems[]; .quantity > 0), anyCopy:any(.lineItems[]; .sku | startswith(\"COPY\"))}" },
  { id: 149, level: '15 composed', name: 'fulfillment health object', expression: '{ shipmentCount: (Shipment[all] | length), shippedCost: (Shipment[all].Cost | add), anyOpen: any(Shipment[], Delivered = false), firstCarrier: Shipment[#first].Carrier }', expected: { shipmentCount: 3, shippedCost: 12.5, anyOpen: true, firstCarrier: 'UPS' }, compiled: "{shipmentCount:([.shipments[]] | length), shippedCost:([.shipments[].cost] | add), anyOpen:any(.shipments[]; .delivered == false), firstCarrier:.shipments[0].carrier}" },
  { id: 150, level: '15 composed', name: 'full invoice audit object', expression: '{ invoice: "Invoice Number", customer: Customer.Name, status: Status, subtotalMatches: ("Line Item"[all]."Line Total" | add) == Subtotal, totalMatches: ROUND(Subtotal - "Discount Amount" + "Tax Amount" + Shipping, 2) == Total, needsFollowup: Payment[Status = "failed"].Amount > 0 or any(Shipment[], Delivered = false) }', expected: { invoice: 'INV-1001', customer: 'Acme Legal', status: 'open', subtotalMatches: true, totalMatches: true, needsFollowup: true }, compiled: "{invoice:.invoiceNumber, customer:.customer.name, status:.status, subtotalMatches:([.lineItems[].lineTotal] | add) == .subtotal, totalMatches:ROUND(.subtotal - .discountAmount + .taxAmount + .shipping; 2) == .total, needsFollowup:first(.payments[] | select(.status == \"failed\")).amount > 0 or any(.shipments[]; .delivered == false)}" },
];

if (bxlExamples.length !== 150) {
  throw new Error(`Expected 150 BXL examples, found ${bxlExamples.length}`);
}
