#!/bin/sh

set -eu

TEST_MODULE=""
FILTER="Integration | Catalog | runner"
NO_RUN="false"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --test-module)
      TEST_MODULE="${2:-}"
      shift 2
      ;;
    --filter)
      FILTER="${2:-}"
      shift 2
      ;;
    --no-run)
      NO_RUN="true"
      shift 1
      ;;
    *)
      echo "[catalog-runner] Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [ -z "$TEST_MODULE" ]; then
  echo "[catalog-runner] Missing --test-module <path-to-test-module.gts|ts|js>" >&2
  exit 1
fi

ROOT_DIR="$(pwd)"
SOURCE_PATH="$ROOT_DIR/$TEST_MODULE"

if [ ! -f "$SOURCE_PATH" ]; then
  echo "[catalog-runner] Test module not found: $SOURCE_PATH" >&2
  exit 1
fi

GENERATED_DIR="$ROOT_DIR/tests/integration/catalog/generated"
GENERATED_MODULE_PATH="$GENERATED_DIR/test-module.gts"

mkdir -p "$GENERATED_DIR"

{
  echo "// Auto-generated by scripts/run-catalog-runner.sh"
  echo "// Source: $SOURCE_PATH"
  echo
  cat "$SOURCE_PATH"
} > "$GENERATED_MODULE_PATH"

echo "[catalog-runner] Wrote $GENERATED_MODULE_PATH"

if [ "$NO_RUN" = "true" ]; then
  exit 0
fi

echo "[catalog-runner] Running ember test --filter \"$FILTER\""
pnpm exec ember test --filter "$FILTER"
