// AUTO-GENERATED by scripts/codemods/qunit-to-vitest.ts. Run codemod again instead of editing by hand.
import {
  describe,
  it,
  expect,
  beforeAll,
  beforeEach,
  afterAll,
  afterEach,
} from 'vitest';
import supertest from 'supertest';
import type { Test, SuperTest } from 'supertest';
import { join } from 'path';
import { dirSync } from 'tmp';
import type {
  LooseSingleCardDocument,
  QueuePublisher,
  QueueRunner,
  Realm,
} from '@cardstack/runtime-common';
import type { FederatedCardTypeSummaryEntry } from '@cardstack/runtime-common/document-types';
import type { PgAdapter } from '@cardstack/postgres';
import { resetCatalogRealms } from '../../handlers/handle-fetch-catalog-realms';
import {
  closeServer,
  createVirtualNetwork,
  setupDB,
  matrixURL,
  realmSecretSeed,
  runTestRealmServerWithRealms,
} from '../helpers';
import { createJWT as createRealmServerJWT } from '../../utils/jwt';
import type { Server } from 'http';
interface FederatedTypesResponse {
  data: FederatedCardTypeSummaryEntry[];
  meta: {
    page: {
      total: number;
    };
  };
}
describe('server-endpoints/federated-types-test.ts', function () {
  const _hooks = {
    before: beforeAll,
    after: afterAll,
    beforeEach,
    afterEach,
  };
  describe('Realm Server Endpoints | /_federated-types', function () {
    const hooks = {
      before: beforeAll,
      after: afterAll,
      beforeEach,
      afterEach,
    };
    let testRealm: Realm;
    let secondaryRealm: Realm;
    let request: SuperTest<Test>;
    let dbAdapter: PgAdapter;
    let testRealmHttpServer: Server;
    let ownerUserId = '@mango:localhost';
    let realmFileSystem: Record<string, string | LooseSingleCardDocument> = {
      'test-card.json': {
        data: {
          type: 'card',
          attributes: {
            cardInfo: {
              name: 'Test Card',
            },
          },
          meta: {
            adoptsFrom: {
              module: 'https://cardstack.com/base/card-api',
              name: 'CardDef',
            },
          },
        },
      },
    };
    async function startTypesRealmServer({
      dbAdapter,
      publisher,
      runner,
    }: {
      dbAdapter: PgAdapter;
      publisher: QueuePublisher;
      runner: QueueRunner;
    }) {
      let virtualNetwork = createVirtualNetwork();
      let dir = dirSync();
      let testRealmURL = new URL('http://127.0.0.1:4444/test/');
      let secondaryRealmURL = new URL('http://127.0.0.1:4444/secondary/');
      let result = await runTestRealmServerWithRealms({
        virtualNetwork,
        realmsRootPath: join(dir.name, 'realm_server_1'),
        realms: [
          {
            realmURL: testRealmURL,
            fileSystem: {
              '.realm.json': JSON.stringify({ name: 'Primary Realm' }),
              ...realmFileSystem,
            },
            permissions: {
              '*': ['read'],
              [ownerUserId]: ['read', 'write', 'realm-owner'],
            },
          },
          {
            realmURL: secondaryRealmURL,
            fileSystem: {
              '.realm.json': JSON.stringify({ name: 'Secondary Realm' }),
              ...realmFileSystem,
            },
            permissions: {
              [ownerUserId]: ['read', 'write', 'realm-owner'],
            },
          },
        ],
        dbAdapter,
        publisher,
        runner,
        matrixURL,
      });
      testRealmHttpServer = result.testRealmHttpServer;
      request = supertest(result.testRealmHttpServer);
      testRealm = result.realms.find(
        (realm) => realm.url === testRealmURL.href,
      )!;
      secondaryRealm = result.realms.find(
        (realm) => realm.url === secondaryRealmURL.href,
      )!;
    }
    async function stopTypesRealmServer() {
      testRealm.unsubscribe();
      secondaryRealm.unsubscribe();
      await closeServer(testRealmHttpServer);
      resetCatalogRealms();
    }
    setupDB(hooks, {
      beforeEach: async (_dbAdapter, publisher, runner) => {
        dbAdapter = _dbAdapter;
        await startTypesRealmServer({ dbAdapter, publisher, runner });
      },
      afterEach: async () => {
        await stopTypesRealmServer();
      },
    });
    function makeAuthenticatedRequest(
      realms: string[],
      extra?: Record<string, unknown>,
    ) {
      let realmServerToken = createRealmServerJWT(
        { user: ownerUserId, sessionRoom: 'session-room-test' },
        realmSecretSeed,
      );
      return request
        .post('/_federated-types')
        .set('X-HTTP-Method-Override', 'QUERY')
        .set('Accept', 'application/json')
        .set('Authorization', `Bearer ${realmServerToken}`)
        .send({ realms, ...extra });
    }
    it('QUERY /_federated-types returns flat type summaries from multiple realms', async function () {
      let response = await makeAuthenticatedRequest([
        testRealm.url,
        secondaryRealm.url,
      ]);
      expect(response.status).toBe(200);
      let body = response.body as FederatedTypesResponse;
      expect(Array.isArray(body.data)).toBeTruthy();
      expect(body.data.length > 0).toBeTruthy();
      let primaryEntries = body.data.filter(
        (entry) => entry.meta.realmURL === testRealm.url,
      );
      let secondaryEntries = body.data.filter(
        (entry) => entry.meta.realmURL === secondaryRealm.url,
      );
      expect(primaryEntries.length > 0).toBeTruthy();
      expect(secondaryEntries.length > 0).toBeTruthy();
      expect(body.data[0].type).toBe('card-type-summary');
      expect(body.data[0].meta.realmURL).toBeTruthy();
      expect(body.data[0].attributes.displayName).toBeTruthy();
      expect(typeof body.data[0].attributes.total).toBe('number');
      expect(body.meta.page.total).toBe(body.data.length);
      let publicHeader =
        response.headers['x-boxel-realms-public-readable'] ?? '';
      expect(publicHeader).toBeTruthy();
      let publicRealms = publicHeader
        .split(',')
        .map((value: string) => value.trim());
      expect(publicRealms.includes(testRealm.url)).toBeTruthy();
      expect(publicRealms.includes(secondaryRealm.url)).toBeFalsy();
    });
    it('QUERY /_federated-types returns 401 for unauthenticated request to non-public realm', async function () {
      let response = await request
        .post('/_federated-types')
        .set('X-HTTP-Method-Override', 'QUERY')
        .set('Accept', 'application/json')
        .send({ realms: [secondaryRealm.url] });
      expect(response.status).toBe(401);
      expect(
        response.body.errors?.[0]?.includes(secondaryRealm.url),
      ).toBeTruthy();
    });
    it('QUERY /_federated-types returns 403 for authenticated request to non-public realm without read permission', async function () {
      let unauthorizedToken = createRealmServerJWT(
        { user: 'unauthorized-user', sessionRoom: 'session-room-test' },
        realmSecretSeed,
      );
      let response = await request
        .post('/_federated-types')
        .set('X-HTTP-Method-Override', 'QUERY')
        .set('Accept', 'application/json')
        .set('Authorization', `Bearer ${unauthorizedToken}`)
        .send({ realms: [secondaryRealm.url] });
      expect(response.status).toBe(403);
      expect(
        response.body.errors?.[0]?.includes(secondaryRealm.url),
      ).toBeTruthy();
    });
    it('QUERY /_federated-types returns 400 when realms are missing', async function () {
      let response = await request
        .post('/_federated-types')
        .set('X-HTTP-Method-Override', 'QUERY')
        .set('Accept', 'application/json')
        .send({});
      expect(response.status).toBe(400);
      expect(
        response.body.errors?.[0]?.includes(
          'realms must be supplied in request body',
        ),
      ).toBeTruthy();
    });
    it('QUERY /_federated-types returns type summaries for public realm without auth', async function () {
      let response = await request
        .post('/_federated-types')
        .set('X-HTTP-Method-Override', 'QUERY')
        .set('Accept', 'application/json')
        .send({ realms: [testRealm.url] });
      expect(response.status).toBe(200);
      let body = response.body as FederatedTypesResponse;
      expect(Array.isArray(body.data)).toBeTruthy();
      expect(body.data.length > 0).toBeTruthy();
      expect(body.data[0].meta.realmURL).toBe(testRealm.url);
    });
    it('QUERY /_federated-types with pagination returns limited results', async function () {
      let response = await makeAuthenticatedRequest(
        [testRealm.url, secondaryRealm.url],
        { page: { number: 0, size: 1 } },
      );
      expect(response.status).toBe(200);
      let body = response.body as FederatedTypesResponse;
      expect(body.data.length).toBe(1);
      expect(body.meta.page.total > 1).toBeTruthy();
    });
    it('QUERY /_federated-types pagination page 2 returns different items', async function () {
      let page0Response = await makeAuthenticatedRequest(
        [testRealm.url, secondaryRealm.url],
        { page: { number: 0, size: 1 } },
      );
      let page1Response = await makeAuthenticatedRequest(
        [testRealm.url, secondaryRealm.url],
        { page: { number: 1, size: 1 } },
      );
      let page0Body = page0Response.body as FederatedTypesResponse;
      let page1Body = page1Response.body as FederatedTypesResponse;
      expect(page0Body.data.length).toBe(1);
      expect(page1Body.data.length).toBe(1);
      let page0Id = `${page0Body.data[0].id}-${page0Body.data[0].meta.realmURL}`;
      let page1Id = `${page1Body.data[0].id}-${page1Body.data[0].meta.realmURL}`;
      expect(page0Id).not.toBe(page1Id);
      expect(page0Body.meta.page.total).toBe(page1Body.meta.page.total);
    });
    it('QUERY /_federated-types without pagination returns all items', async function () {
      let allResponse = await makeAuthenticatedRequest([
        testRealm.url,
        secondaryRealm.url,
      ]);
      let paginatedResponse = await makeAuthenticatedRequest(
        [testRealm.url, secondaryRealm.url],
        { page: { number: 0, size: 1 } },
      );
      let allBody = allResponse.body as FederatedTypesResponse;
      let paginatedBody = paginatedResponse.body as FederatedTypesResponse;
      expect(allBody.data.length).toBe(allBody.meta.page.total);
      expect(allBody.meta.page.total).toBe(paginatedBody.meta.page.total);
    });
    it('QUERY /_federated-types with searchKey filters results', async function () {
      let allResponse = await makeAuthenticatedRequest([testRealm.url]);
      let allBody = allResponse.body as FederatedTypesResponse;
      // Use a displayName or code_ref substring from the actual results
      let firstEntry = allBody.data[0];
      let searchTerm = firstEntry.attributes.displayName.substring(0, 4);
      let searchResponse = await makeAuthenticatedRequest([testRealm.url], {
        searchKey: searchTerm,
      });
      let searchBody = searchResponse.body as FederatedTypesResponse;
      expect(searchBody.data.length > 0).toBeTruthy();
      expect(
        searchBody.data.every(
          (entry) =>
            entry.attributes.displayName
              .toLowerCase()
              .includes(searchTerm.toLowerCase()) ||
            entry.id.toLowerCase().includes(searchTerm.toLowerCase()),
        ),
      ).toBeTruthy();
      expect(searchBody.meta.page.total).toBe(searchBody.data.length);
    });
    it('QUERY /_federated-types with searchKey and pagination combined', async function () {
      let allResponse = await makeAuthenticatedRequest([testRealm.url]);
      let allBody = allResponse.body as FederatedTypesResponse;
      let firstEntry = allBody.data[0];
      let searchTerm = firstEntry.attributes.displayName.substring(0, 3);
      let response = await makeAuthenticatedRequest([testRealm.url], {
        searchKey: searchTerm,
        page: { number: 0, size: 1 },
      });
      let body = response.body as FederatedTypesResponse;
      expect(body.data.length).toBe(1);
      let matchesDisplayName = body.data[0].attributes.displayName
        .toLowerCase()
        .includes(searchTerm.toLowerCase());
      let matchesCodeRef = body.data[0].id
        .toLowerCase()
        .includes(searchTerm.toLowerCase());
      let matchesSearch = matchesDisplayName || matchesCodeRef;
      expect(matchesSearch).toBeTruthy();
      expect(body.meta.page.total >= 1).toBeTruthy();
    });
    it('QUERY /_federated-types with searchKey that matches nothing returns empty data', async function () {
      let response = await makeAuthenticatedRequest([testRealm.url], {
        searchKey: 'zzzzNonExistentTypezzzzz',
      });
      expect(response.status).toBe(200);
      let body = response.body as FederatedTypesResponse;
      expect(body.data.length).toBe(0);
      expect(body.meta.page.total).toBe(0);
    });
    it('QUERY /_federated-types searchKey is case-insensitive', async function () {
      let allResponse = await makeAuthenticatedRequest([testRealm.url]);
      let allBody = allResponse.body as FederatedTypesResponse;
      let firstEntry = allBody.data[0];
      let searchTerm = firstEntry.attributes.displayName
        .toUpperCase()
        .substring(0, 4);
      let response = await makeAuthenticatedRequest([testRealm.url], {
        searchKey: searchTerm,
      });
      let body = response.body as FederatedTypesResponse;
      expect(body.data.length > 0).toBeTruthy();
    });
    it('QUERY /_federated-types each item has meta.realmURL', async function () {
      let response = await makeAuthenticatedRequest([
        testRealm.url,
        secondaryRealm.url,
      ]);
      let body = response.body as FederatedTypesResponse;
      expect(
        body.data.every(
          (entry) =>
            typeof entry.meta.realmURL === 'string' &&
            entry.meta.realmURL.length > 0,
        ),
      ).toBeTruthy();
      let realmURLs = new Set(body.data.map((entry) => entry.meta.realmURL));
      expect(realmURLs.has(testRealm.url)).toBeTruthy();
      expect(realmURLs.has(secondaryRealm.url)).toBeTruthy();
    });
    it('QUERY /_federated-types pagination beyond range returns empty data', async function () {
      let response = await makeAuthenticatedRequest([testRealm.url], {
        page: { number: 9999, size: 50 },
      });
      expect(response.status).toBe(200);
      let body = response.body as FederatedTypesResponse;
      expect(body.data.length).toBe(0);
      expect(body.meta.page.total > 0).toBeTruthy();
    });
  });
});
