// AUTO-GENERATED by scripts/codemods/qunit-to-vitest.ts. Run codemod again instead of editing by hand.
import { describe, it, expect, beforeAll, beforeEach, afterAll, afterEach } from "vitest";
import supertest from 'supertest';
import type { Test, SuperTest } from 'supertest';
import { join } from 'path';
import { dirSync } from 'tmp';
import type { QueuePublisher, QueueRunner, Realm, } from '@cardstack/runtime-common';
import type { PgAdapter } from '@cardstack/postgres';
import { resetCatalogRealms } from '../../handlers/handle-fetch-catalog-realms';
import { closeServer, createVirtualNetwork, setupDB, matrixURL, realmSecretSeed, runTestRealmServerWithRealms, } from '../helpers';
import { createJWT as createRealmServerJWT } from '../../utils/jwt';
import type { Server } from 'http';
describe("server-endpoints/info-test.ts", function () {
    const _hooks = {
        before: beforeAll,
        after: afterAll,
        beforeEach,
        afterEach
    };
    describe('Realm Server Endpoints | /_federated-info', function () {
        const hooks = {
            before: beforeAll,
            after: afterAll,
            beforeEach,
            afterEach
        };
        let testRealm: Realm;
        let secondaryRealm: Realm;
        let request: SuperTest<Test>;
        let dbAdapter: PgAdapter;
        let testRealmHttpServer: Server;
        let ownerUserId = '@mango:localhost';
        async function startInfoRealmServer({ dbAdapter, publisher, runner, }: {
            dbAdapter: PgAdapter;
            publisher: QueuePublisher;
            runner: QueueRunner;
        }) {
            let virtualNetwork = createVirtualNetwork();
            let dir = dirSync();
            let testRealmURL = new URL('http://127.0.0.1:4444/test/');
            let secondaryRealmURL = new URL('http://127.0.0.1:4444/secondary/');
            let result = await runTestRealmServerWithRealms({
                virtualNetwork,
                realmsRootPath: join(dir.name, 'realm_server_1'),
                realms: [
                    {
                        realmURL: testRealmURL,
                        fileSystem: {
                            '.realm.json': JSON.stringify({ name: 'Primary Realm' }),
                        },
                        permissions: {
                            '*': ['read'],
                            [ownerUserId]: ['read', 'write', 'realm-owner'],
                        },
                    },
                    {
                        realmURL: secondaryRealmURL,
                        fileSystem: {
                            '.realm.json': JSON.stringify({ name: 'Secondary Realm' }),
                        },
                        permissions: {
                            [ownerUserId]: ['read', 'write', 'realm-owner'],
                        },
                    },
                ],
                dbAdapter,
                publisher,
                runner,
                matrixURL,
            });
            testRealmHttpServer = result.testRealmHttpServer;
            request = supertest(result.testRealmHttpServer);
            testRealm = result.realms.find((realm) => realm.url === testRealmURL.href)!;
            secondaryRealm = result.realms.find((realm) => realm.url === secondaryRealmURL.href)!;
        }
        async function stopInfoRealmServer() {
            testRealm.unsubscribe();
            secondaryRealm.unsubscribe();
            await closeServer(testRealmHttpServer);
            resetCatalogRealms();
        }
        setupDB(hooks, {
            beforeEach: async (_dbAdapter, publisher, runner) => {
                dbAdapter = _dbAdapter;
                await startInfoRealmServer({ dbAdapter, publisher, runner });
            },
            afterEach: async () => {
                await stopInfoRealmServer();
            },
        });
        it('QUERY /_federated-info federates info across realms and includes public list header', async function () {
            let realmServerToken = createRealmServerJWT({ user: ownerUserId, sessionRoom: 'session-room-test' }, realmSecretSeed);
            let response = await request
                .post('/_federated-info')
                .set('X-HTTP-Method-Override', 'QUERY')
                .set('Accept', 'application/vnd.api+json')
                .set('Authorization', `Bearer ${realmServerToken}`)
                .send({ realms: [testRealm.url, secondaryRealm.url] });
            expect(response.status).toBe(200);
            let { data } = response.body as {
                data: {
                    id: string;
                    type: string;
                    attributes: {
                        name: string;
                    };
                }[];
            };
            expect(data.length).toBe(2);
            let dataById = new Map(data.map((entry) => [entry.id, entry]));
            expect(dataById.get(testRealm.url)?.attributes.name).toBe('Primary Realm');
            expect(dataById.get(secondaryRealm.url)?.attributes.name).toBe('Secondary Realm');
            let publicHeader = response.headers['x-boxel-realms-public-readable'] ?? '';
            expect(publicHeader).toBeTruthy();
            let publicRealms = publicHeader
                .split(',')
                .map((value: string) => value.trim());
            expect(publicRealms.includes(testRealm.url)).toBeTruthy();
            expect(publicRealms.includes(secondaryRealm.url)).toBeFalsy();
        });
        it('QUERY /_federated-info returns 403 when user lacks read access', async function () {
            let realmServerToken = createRealmServerJWT({ user: '@rando:localhost', sessionRoom: 'session-room-test' }, realmSecretSeed);
            let response = await request
                .post('/_federated-info')
                .set('X-HTTP-Method-Override', 'QUERY')
                .set('Accept', 'application/vnd.api+json')
                .set('Authorization', `Bearer ${realmServerToken}`)
                .send({ realms: [testRealm.url, secondaryRealm.url] });
            expect(response.status).toBe(403);
            expect(response.body.errors?.[0]?.includes(secondaryRealm.url)).toBeTruthy();
        });
        it('QUERY /_federated-info returns 401 when unauthenticated user requests non-public realm', async function () {
            let response = await request
                .post('/_federated-info')
                .set('X-HTTP-Method-Override', 'QUERY')
                .set('Accept', 'application/vnd.api+json')
                .send({ realms: [secondaryRealm.url] });
            expect(response.status).toBe(401);
            expect(response.body.errors?.[0]?.includes(secondaryRealm.url)).toBeTruthy();
        });
        it('QUERY /_federated-info returns 400 when realms are missing', async function () {
            let response = await request
                .post('/_federated-info')
                .set('X-HTTP-Method-Override', 'QUERY')
                .set('Accept', 'application/vnd.api+json')
                .send({});
            expect(response.status).toBe(400);
            expect(response.body.errors?.[0]?.includes('realms must be supplied in request body')).toBeTruthy();
        });
        it('QUERY /_federated-info returns info for a public realm without auth when realms body is provided', async function () {
            // This tests the scenario where a subdomain-based realm at root path
            // (e.g. http://hi.localhost:4201/) sends QUERY to /_federated-info. The path /_federated-info
            // matches the server-level route (not the realm's own handler), so the
            // request body with realms array is required.
            let response = await request
                .post('/_federated-info')
                .set('X-HTTP-Method-Override', 'QUERY')
                .set('Accept', 'application/vnd.api+json')
                .send({ realms: [testRealm.url] });
            expect(response.status).toBe(200);
            let { data } = response.body as {
                data: {
                    id: string;
                    type: string;
                    attributes: {
                        name: string;
                    };
                }[];
            };
            expect(data.length).toBe(1);
            expect(data[0].id).toBe(testRealm.url);
            expect(data[0].attributes.name).toBe('Primary Realm');
        });
    });
});
