// AUTO-GENERATED by scripts/codemods/qunit-to-vitest.ts. Run codemod again instead of editing by hand.
import { createVitestNestedHooksAdapter } from "../helpers/qunit-hooks-adapter";
import { describe, it, expect } from "vitest";
import { join } from 'path';
import { existsSync, readJSONSync } from 'fs-extra';
import { v4 as uuidv4 } from 'uuid';
import type { Query } from '@cardstack/runtime-common/query';
import { baseCardRef, fetchRealmPermissions, userInitiatedPriority, } from '@cardstack/runtime-common';
import type { SingleCardDocument } from '@cardstack/runtime-common';
import type { CardCollectionDocument } from '@cardstack/runtime-common/document-types';
import { cardSrc } from '@cardstack/runtime-common/etc/test-fixtures';
import { closeServer, createJWT, realmSecretSeed, testRealmInfo, } from '../helpers';
import { createJWT as createRealmServerJWT } from '../../utils/jwt';
import { setupServerEndpointsTest, testRealm2URL } from './helpers';
import '@cardstack/runtime-common/helpers/code-equality-assertion';
describe("server-endpoints/realm-lifecycle-test.ts", function () {
    describe('Realm Server Endpoints (not specific to one realm)', function () {
        const hooks = createVitestNestedHooksAdapter() as any;
        let context = setupServerEndpointsTest(hooks);
        it('POST /_create-realm', async function () {
            // we randomize the realm and owner names so that we can isolate matrix
            // test state--there is no "delete user" matrix API
            let endpoint = `test-realm-${uuidv4()}`;
            let owner = 'mango';
            let ownerUserId = '@mango:localhost';
            let response = await context.request2
                .post('/_create-realm')
                .set('Accept', 'application/vnd.api+json')
                .set('Content-Type', 'application/json')
                .set('Authorization', `Bearer ${createRealmServerJWT({ user: ownerUserId, sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                .send(JSON.stringify({
                data: {
                    type: 'realm',
                    attributes: {
                        ...testRealmInfo,
                        endpoint,
                        backgroundURL: 'http://example.com/background.jpg',
                        iconURL: 'http://example.com/icon.jpg',
                    },
                },
            }));
            expect(response.status).toBe(201);
            let json = response.body;
            expect(json).toEqual({
                data: {
                    type: 'realm',
                    id: `${testRealm2URL.origin}/${owner}/${endpoint}/`,
                    attributes: {
                        ...testRealmInfo,
                        endpoint,
                        backgroundURL: 'http://example.com/background.jpg',
                        iconURL: 'http://example.com/icon.jpg',
                        publishable: true,
                    },
                },
            });
            let realmPath = join(context.dir.name, 'realm_server_2', owner, endpoint);
            let realmJSON = readJSONSync(join(realmPath, '.realm.json'));
            expect(realmJSON).toEqual({
                name: 'Test Realm',
                backgroundURL: 'http://example.com/background.jpg',
                iconURL: 'http://example.com/icon.jpg',
                publishable: true,
            });
            expect(existsSync(join(realmPath, 'index.json'))).toBeTruthy();
            let job = (await context.dbAdapter.execute(`SELECT priority FROM jobs WHERE job_type = 'from-scratch-index' AND args->>'realmURL' = '${json.data.id}' ORDER BY created_at DESC LIMIT 1`)) as {
                priority: number;
            }[];
            expect(job[0]).toBeTruthy();
            expect(job[0].priority).toBe(userInitiatedPriority);
            let permissions = await fetchRealmPermissions(context.dbAdapter, new URL(json.data.id));
            expect(permissions).toEqual({
                [ownerUserId]: ['read', 'write', 'realm-owner'],
            });
            let id: string;
            let realm = context.testRealmServer2.testingOnlyRealms.find((r) => r.url === json.data.id)!;
            {
                // owner can create an instance
                let response = await context.request2
                    .post(`/${owner}/${endpoint}/`)
                    .send({
                    data: {
                        type: 'card',
                        attributes: { cardInfo: { name: 'Test Card' } },
                        meta: {
                            adoptsFrom: {
                                module: 'https://cardstack.com/base/card-api',
                                name: 'CardDef',
                            },
                        },
                    },
                })
                    .set('Accept', 'application/vnd.card+json')
                    .set('Authorization', `Bearer ${createJWT(realm, ownerUserId, [
                    'read',
                    'write',
                    'realm-owner',
                ])}`);
                expect(response.status).toBe(201);
                let doc = response.body as SingleCardDocument;
                id = doc.data.id!;
            }
            {
                // owner can get an instance
                let response = await context.request2
                    .get(new URL(id).pathname)
                    .set('Accept', 'application/vnd.card+json')
                    .set('Authorization', `Bearer ${createJWT(realm, ownerUserId, [
                    'read',
                    'write',
                    'realm-owner',
                ])}`);
                expect(response.status).toBe(200);
                let doc = response.body as SingleCardDocument;
                expect(doc.data.attributes?.cardTitle).toBe('Test Card');
            }
            {
                // owner can search in the realm
                let response = await context.request2
                    .post(`${new URL(realm.url).pathname}_search`)
                    .set('Accept', 'application/vnd.card+json')
                    .set('X-HTTP-Method-Override', 'QUERY')
                    .set('Authorization', `Bearer ${createJWT(realm, ownerUserId, [
                    'read',
                    'write',
                    'realm-owner',
                ])}`)
                    .send({
                    filter: {
                        on: baseCardRef,
                        eq: {
                            cardTitle: 'Test Card',
                        },
                    },
                } as Query);
                expect(response.status).toBe(200);
                let results = response.body as CardCollectionDocument;
                (expect(results.data.length).toBe(1),
                    'correct number of search results');
            }
        });
        it('dynamically created realms are not publicly readable or writable', async function () {
            let endpoint = `test-realm-${uuidv4()}`;
            let owner = 'mango';
            let ownerUserId = '@mango:localhost';
            let response = await context.request2
                .post('/_create-realm')
                .set('Accept', 'application/vnd.api+json')
                .set('Content-Type', 'application/json')
                .set('Authorization', `Bearer ${createRealmServerJWT({ user: ownerUserId, sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                .send(JSON.stringify({
                data: {
                    type: 'realm',
                    attributes: {
                        name: 'Test Realm',
                        endpoint,
                    },
                },
            }));
            let realmURL = response.body.data.id;
            expect(response.status).toBe(201);
            let realm = context.testRealmServer2.testingOnlyRealms.find((r) => r.url === realmURL)!;
            {
                let response = await context.request2
                    .post(`${new URL(realmURL).pathname}_search`)
                    .set('Accept', 'application/vnd.card+json')
                    .set('X-HTTP-Method-Override', 'QUERY')
                    .set('Authorization', `Bearer ${createJWT(realm, 'rando')}`)
                    .send({
                    filter: {
                        on: baseCardRef,
                        eq: {
                            cardTitle: 'Test Card',
                        },
                    },
                } as Query);
                expect(response.status).toBe(403);
                response = await context.request2
                    .post(`/${owner}/${endpoint}/`)
                    .send({
                    data: {
                        type: 'card',
                        attributes: {
                            cardTitle: 'Test Card',
                        },
                        meta: {
                            adoptsFrom: {
                                module: 'https://cardstack.com/base/card-api',
                                name: 'CardDef',
                            },
                        },
                    },
                })
                    .set('Accept', 'application/vnd.card+json')
                    .set('Authorization', `Bearer ${createJWT(realm, 'rando')}`);
                expect(response.status).toBe(403);
            }
        });
        it('can restart a realm that was created dynamically', async function () {
            let endpoint = `test-realm-${uuidv4()}`;
            let owner = 'mango';
            let ownerUserId = '@mango:localhost';
            let realmURL: string;
            {
                let response = await context.request2
                    .post('/_create-realm')
                    .set('Accept', 'application/vnd.api+json')
                    .set('Content-Type', 'application/json')
                    .set('Authorization', `Bearer ${createRealmServerJWT({
                    user: '@mango:localhost',
                    sessionRoom: 'session-room-test',
                }, realmSecretSeed)}`)
                    .send(JSON.stringify({
                    data: {
                        type: 'realm',
                        attributes: {
                            name: 'Test Realm',
                            endpoint,
                        },
                    },
                }));
                expect(response.status).toBe(201);
                realmURL = response.body.data.id;
            }
            let id: string;
            let realm = context.testRealmServer2.testingOnlyRealms.find((r) => r.url === realmURL)!;
            {
                let response = await context.request2
                    .post(`/${owner}/${endpoint}/`)
                    .send({
                    data: {
                        type: 'card',
                        attributes: { cardInfo: { name: 'Test Card' } },
                        meta: {
                            adoptsFrom: {
                                module: 'https://cardstack.com/base/card-api',
                                name: 'CardDef',
                            },
                        },
                    },
                })
                    .set('Accept', 'application/vnd.card+json')
                    .set('Authorization', `Bearer ${createJWT(realm, ownerUserId, [
                    'read',
                    'write',
                    'realm-owner',
                ])}`);
                expect(response.status).toBe(201);
                id = response.body.data.id;
            }
            let jobsBeforeRestart = await context.dbAdapter.execute('select * from jobs');
            // Stop and restart the server
            context.testRealmServer2.testingOnlyUnmountRealms();
            await closeServer(context.testRealmHttpServer2);
            await context.startRealmServer();
            await context.testRealmServer2.start();
            let jobsAfterRestart = await context.dbAdapter.execute('select * from jobs');
            expect(jobsBeforeRestart.length).toBe(jobsAfterRestart.length);
            {
                let response = await context.request2
                    .get(new URL(id).pathname)
                    .set('Accept', 'application/vnd.card+json')
                    .set('Authorization', `Bearer ${createJWT(realm, ownerUserId, [
                    'read',
                    'write',
                    'realm-owner',
                ])}`);
                expect(response.status).toBe(200);
                let doc = response.body as SingleCardDocument;
                expect(doc.data.attributes?.cardTitle).toBe('Test Card');
            }
        });
        it('POST /_create-realm without JWT', async function () {
            let endpoint = `test-realm-${uuidv4()}`;
            let response = await context.request2
                .post('/_create-realm')
                .set('Accept', 'application/vnd.api+json')
                .set('Content-Type', 'application/json')
                .send(JSON.stringify({
                data: {
                    type: 'realm',
                    attributes: {
                        name: 'Test Realm',
                        endpoint,
                    },
                },
            }));
            expect(response.status).toBe(401);
            let error = response.body.errors[0];
            expect(error).toBe('Missing Authorization header');
        });
        it('POST /_create-realm with invalid JWT', async function () {
            let endpoint = `test-realm-${uuidv4()}`;
            let response = await context.request2
                .post('/_create-realm')
                .set('Accept', 'application/vnd.api+json')
                .set('Content-Type', 'application/json')
                .set('Authorization', 'Bearer invalid-jwt')
                .send(JSON.stringify({
                data: {
                    type: 'realm',
                    attributes: {
                        name: 'Test Realm',
                        endpoint,
                    },
                },
            }));
            expect(response.status).toBe(401);
            let error = response.body.errors[0];
            expect(error).toBe('Token invalid');
        });
        it('POST /_create-realm with invalid JSON', async function () {
            let response = await context.request2
                .post('/_create-realm')
                .set('Accept', 'application/vnd.api+json')
                .set('Content-Type', 'application/json')
                .set('Authorization', `Bearer ${createRealmServerJWT({ user: '@mango:localhost', sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                .send('make a new realm please!');
            expect(response.status).toBe(400);
            let error = response.body.errors[0];
            expect(error.match(/not valid JSON-API/)).toBeTruthy();
        });
        it('POST /_create-realm with bad JSON-API', async function () {
            let response = await context.request2
                .post('/_create-realm')
                .set('Accept', 'application/vnd.api+json')
                .set('Content-Type', 'application/json')
                .set('Authorization', `Bearer ${createRealmServerJWT({ user: '@mango:localhost', sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                .send(JSON.stringify({
                name: 'mango-realm',
            }));
            expect(response.status).toBe(400);
            let error = response.body.errors[0];
            expect(error.match(/not valid JSON-API/)).toBeTruthy();
        });
        it('POST /_create-realm without a realm endpoint', async function () {
            let response = await context.request2
                .post('/_create-realm')
                .set('Accept', 'application/vnd.api+json')
                .set('Content-Type', 'application/json')
                .set('Authorization', `Bearer ${createRealmServerJWT({ user: '@mango:localhost', sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                .send(JSON.stringify({
                data: {
                    type: 'realm',
                    attributes: {
                        name: 'Test Realm',
                    },
                },
            }));
            expect(response.status).toBe(400);
            let error = response.body.errors[0];
            expect(error.match(/endpoint is required and must be a string/)).toBeTruthy();
        });
        it('POST /_create-realm without a realm name', async function () {
            let endpoint = `test-realm-${uuidv4()}`;
            let response = await context.request2
                .post('/_create-realm')
                .set('Accept', 'application/vnd.api+json')
                .set('Content-Type', 'application/json')
                .set('Authorization', `Bearer ${createRealmServerJWT({ user: '@mango:localhost', sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                .send(JSON.stringify({
                data: {
                    type: 'realm',
                    attributes: {
                        endpoint,
                    },
                },
            }));
            expect(response.status).toBe(400);
            let error = response.body.errors[0];
            expect(error.match(/name is required and must be a string/)).toBeTruthy();
        });
        it('cannot create a realm on a realm server that has a realm mounted at the origin', async function () {
            let response = await context.request
                .post('/_create-realm')
                .set('Accept', 'application/vnd.api+json')
                .set('Content-Type', 'application/json')
                .set('Authorization', `Bearer ${createRealmServerJWT({ user: '@mango:localhost', sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                .send(JSON.stringify({
                data: {
                    type: 'realm',
                    attributes: {
                        endpoint: 'mango-realm',
                        name: 'Test Realm',
                    },
                },
            }));
            expect(response.status).toBe(400);
            let error = response.body.errors[0];
            expect(error.match(/a realm is already mounted at the origin of this server/)).toBeTruthy();
        });
        it('cannot create a new realm that collides with an existing realm', async function () {
            let endpoint = `test-realm-${uuidv4()}`;
            let ownerUserId = '@mango:localhost';
            let response = await context.request2
                .post('/_create-realm')
                .set('Accept', 'application/vnd.api+json')
                .set('Content-Type', 'application/json')
                .set('Authorization', `Bearer ${createRealmServerJWT({ user: ownerUserId, sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                .send(JSON.stringify({
                data: {
                    type: 'realm',
                    attributes: {
                        endpoint,
                        name: 'Test Realm',
                    },
                },
            }));
            expect(response.status).toBe(201);
            {
                let response = await context.request2
                    .post('/_create-realm')
                    .set('Accept', 'application/vnd.api+json')
                    .set('Content-Type', 'application/json')
                    .set('Authorization', `Bearer ${createRealmServerJWT({ user: ownerUserId, sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                    .send(JSON.stringify({
                    data: {
                        type: 'realm',
                        attributes: {
                            endpoint,
                            name: 'Another Test Realm',
                        },
                    },
                }));
                expect(response.status).toBe(400);
                let error = response.body.errors[0];
                expect(error.match(/already exists on this server/)).toBeTruthy();
            }
        });
        it('cannot create a realm with invalid characters in endpoint', async function () {
            let ownerUserId = '@mango:localhost';
            {
                let response = await context.request2
                    .post('/_create-realm')
                    .set('Accept', 'application/vnd.api+json')
                    .set('Content-Type', 'application/json')
                    .set('Authorization', `Bearer ${createRealmServerJWT({ user: ownerUserId, sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                    .send(JSON.stringify({
                    data: {
                        type: 'realm',
                        attributes: {
                            endpoint: 'invalid_realm_endpoint',
                            name: 'Test Realm',
                        },
                    },
                }));
                expect(response.status).toBe(400);
                let error = response.body.errors[0];
                expect(error.match(/contains invalid characters/)).toBeTruthy();
            }
            {
                let response = await context.request2
                    .post('/_create-realm')
                    .set('Accept', 'application/vnd.api+json')
                    .set('Content-Type', 'application/json')
                    .set('Authorization', `Bearer ${createRealmServerJWT({ user: ownerUserId, sessionRoom: 'session-room-test' }, realmSecretSeed)}`)
                    .send(JSON.stringify({
                    data: {
                        type: 'realm',
                        attributes: {
                            endpoint: 'invalid realm endpoint',
                            name: 'Test Realm',
                        },
                    },
                }));
                expect(response.status).toBe(400);
                let error = response.body.errors[0];
                expect(error.match(/contains invalid characters/)).toBeTruthy();
            }
        });
        it('can create instance in private realm using card def from a different private realm both owned by the same user', async function () {
            let owner = 'mango';
            let ownerUserId = '@mango:localhost';
            let providerEndpoint = `test-realm-provider-${uuidv4()}`;
            let providerRealmURL: string;
            {
                let response = await context.request2
                    .post('/_create-realm')
                    .set('Accept', 'application/vnd.api+json')
                    .set('Content-Type', 'application/json')
                    .set('Authorization', `Bearer ${createRealmServerJWT({
                    user: '@mango:localhost',
                    sessionRoom: 'session-room-test',
                }, realmSecretSeed)}`)
                    .send(JSON.stringify({
                    data: {
                        type: 'realm',
                        attributes: {
                            name: 'Test Provider Realm',
                            endpoint: providerEndpoint,
                        },
                    },
                }));
                expect(response.status).toBe(201);
                providerRealmURL = response.body.data.id;
            }
            let providerRealm = context.testRealmServer2.testingOnlyRealms.find((r) => r.url === providerRealmURL)!;
            {
                // create a card def
                let response = await context.request2
                    .post(`/${owner}/${providerEndpoint}/test-card.gts`)
                    .set('Accept', 'application/vnd.card+source')
                    .set('Authorization', `Bearer ${createJWT(providerRealm, ownerUserId, [
                    'read',
                    'write',
                    'realm-owner',
                ])}`)
                    .send(cardSrc);
                expect(response.status).toBe(204);
            }
            let consumerEndpoint = `test-realm-consumer-${uuidv4()}`;
            let consumerRealmURL: string;
            {
                let response = await context.request2
                    .post('/_create-realm')
                    .set('Accept', 'application/vnd.api+json')
                    .set('Content-Type', 'application/json')
                    .set('Authorization', `Bearer ${createRealmServerJWT({
                    user: '@mango:localhost',
                    sessionRoom: 'session-room-test',
                }, realmSecretSeed)}`)
                    .send(JSON.stringify({
                    data: {
                        type: 'realm',
                        attributes: {
                            name: 'Test Consumer Realm',
                            endpoint: consumerEndpoint,
                        },
                    },
                }));
                expect(response.status).toBe(201);
                consumerRealmURL = response.body.data.id;
            }
            let consumerRealm = context.testRealmServer2.testingOnlyRealms.find((r) => r.url === consumerRealmURL)!;
            let id: string;
            {
                // create an instance using card def in different private realm
                let response = await context.request2
                    .post(`/${owner}/${consumerEndpoint}/`)
                    .send({
                    data: {
                        type: 'card',
                        attributes: {
                            firstName: 'Mango',
                        },
                        meta: {
                            adoptsFrom: {
                                module: `${providerRealmURL}test-card`,
                                name: 'Person',
                            },
                        },
                    },
                })
                    .set('Accept', 'application/vnd.card+json')
                    .set('Authorization', `Bearer ${createJWT(consumerRealm, ownerUserId, [
                    'read',
                    'write',
                    'realm-owner',
                ])}`);
                expect(response.status).toBe(201);
                let doc = response.body as SingleCardDocument;
                id = doc.data.id!;
            }
            {
                // get the instance
                let response = await context.request2
                    .get(new URL(id).pathname)
                    .set('Accept', 'application/vnd.card+json')
                    .set('Authorization', `Bearer ${createJWT(consumerRealm, ownerUserId, [
                    'read',
                    'write',
                    'realm-owner',
                ])}`);
                expect(response.status).toBe(200);
                let doc = response.body as SingleCardDocument;
                expect(doc.data.attributes?.firstName).toBe('Mango');
            }
        });
    });
});
