// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-case-snake-upper'
    viewBox='0 0 24 24'
    ...attributes
  ><path
      d='M2 16v-5.5a2.5 2.5 0 0 1 5 0V16M7 13H2M11 16h2M17 12h3a2 2 0 1 1 0 4h-3V8h2.5a2 2 0 0 1 .1 4'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'case-snake-upper';
export default IconComponent;
