// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-clock-arrow-up'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='M13.228 21.925a10 10 0 1 1 8.766-9.587' /><path
      d='M12 6v6l1.562.781M14 18l4-4 4 4M18 22v-8'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'clock-arrow-up';
export default IconComponent;
