// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-closed-caption'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='M10 9.17a3 3 0 1 0 0 5.66M17 9.17a3 3 0 1 0 0 5.66' /><rect
      width='20'
      height='14'
      x='2'
      y='5'
      rx='2'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'closed-caption';
export default IconComponent;
