// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-cone'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='m20.9 18.55-8-15.98a1 1 0 0 0-1.8 0l-8 15.98' /><ellipse
      cx='12'
      cy='19'
      rx='9'
      ry='3'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'cone';
export default IconComponent;
