// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-file-stack'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='M21 7h-3a2 2 0 0 1-2-2V2' /><path
      d='M21 6v6.5c0 .8-.7 1.5-1.5 1.5h-7c-.8 0-1.5-.7-1.5-1.5v-9c0-.8.7-1.5 1.5-1.5H17Z'
    /><path d='M7 8v8.8c0 .3.2.6.4.8.2.2.5.4.8.4H15' /><path
      d='M3 12v8.8c0 .3.2.6.4.8.2.2.5.4.8.4H11'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'file-stack';
export default IconComponent;
