// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='icon icon-tabler icons-tabler-outline icon-tabler-filter-2-dollar'
    viewBox='0 0 24 24'
    ...attributes
  ><path stroke='none' d='M0 0h24v24H0z' /><path
      d='M4 6h16M6 12h10M9 18h4M21 15h-2m-2 6h2m0 0v1m0-1h.5a1.503 1.503 0 0 0 1.5-1.5 1.503 1.503 0 0 0-1.5-1.5h-1a1.503 1.503 0 0 1-1.5-1.5 1.503 1.503 0 0 1 1.5-1.5h.5m0-1v1'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'filter-2-dollar';
export default IconComponent;
