// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-olive'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='m10 10 4-3M10 7l4 3' /><ellipse
      cx='12'
      cy='12'
      rx='9'
      ry='10'
    /><path d='m2 22 5-5M18.69 5.31 22 2' /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'olive';
export default IconComponent;
