// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-repeat'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='m17 2 4 4-4 4' /><path
      d='M3 11v-1a4 4 0 0 1 4-4h14M7 22l-4-4 4-4'
    /><path d='M21 13v1a4 4 0 0 1-4 4H3' /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'repeat';
export default IconComponent;
