// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='icon icon-tabler icons-tabler-outline icon-tabler-skateboarding'
    viewBox='0 0 24 24'
    ...attributes
  ><path stroke='none' d='M0 0h24v24H0z' /><path
      d='M16 4a1 1 0 1 0 2 0 1 1 0 0 0-2 0M5.5 15H9l.75-1.5M14 19v-5l-2.5-3L14 7'
    /><path d='m8 8 3-1h4l1 3h3' /><path
      fill='currentColor'
      d='M17.5 21a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1z'
    /><path d='M3 18c0 .552.895 1 2 1h14c1.105 0 2-.448 2-1' /><path
      fill='currentColor'
      d='M6.5 21a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1z'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'skateboarding';
export default IconComponent;
