// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-speaker'
    viewBox='0 0 24 24'
    ...attributes
  ><rect width='16' height='20' x='4' y='2' rx='2' /><path
      d='M12 6h.01'
    /><circle cx='12' cy='14' r='4' /><path d='M12 14h.01' /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'speaker';
export default IconComponent;
