// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-squares-intersect'
    viewBox='0 0 24 24'
    ...attributes
  ><path
      d='M10 22a2 2 0 0 1-2-2M14 2a2 2 0 0 1 2 2M16 22h-2M2 10V8M2 4a2 2 0 0 1 2-2M20 8a2 2 0 0 1 2 2M22 14v2M22 20a2 2 0 0 1-2 2M4 16a2 2 0 0 1-2-2M8 10a2 2 0 0 1 2-2h5a1 1 0 0 1 1 1v5a2 2 0 0 1-2 2H9a1 1 0 0 1-1-1zM8 2h2'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'squares-intersect';
export default IconComponent;
