// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-target-arrow'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='M19 2v3h3M13.4 10.6 22 2' /><circle cx='12' cy='12' r='2' /><path
      d='M12.3 6H12a6 6 0 1 0 6 6v-.3'
    /><path
      d='M15 2.5A9.93 9.93 0 1 0 21.5 9M5.3 19.4 4 22M18.7 19.4 20 22'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'target-arrow';
export default IconComponent;
