// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='icon icon-tabler icons-tabler-outline icon-tabler-topology-ring-2'
    viewBox='0 0 24 24'
    ...attributes
  ><path stroke='none' d='M0 0h24v24H0z' /><path
      d='M14 6a2 2 0 1 0-4 0 2 2 0 0 0 4 0zM7 18a2 2 0 1 0-4 0 2 2 0 0 0 4 0zM21 18a2 2 0 1 0-4 0 2 2 0 0 0 4 0zM7 18h10M18 16l-5-8M11 8l-5 8'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'topology-ring-2';
export default IconComponent;
