// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-triangle-dashed'
    viewBox='0 0 24 24'
    ...attributes
  ><path
      d='M10.17 4.193a2 2 0 0 1 3.666.013M14 21h2M15.874 7.743l1 1.732M18.849 12.952l1 1.732M21.824 18.18a2 2 0 0 1-1.835 2.824M4.024 21a2 2 0 0 1-1.839-2.839M5.136 12.952l-1 1.732M8 21h2M8.102 7.743l-1 1.732'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'triangle-dashed';
export default IconComponent;
