// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from '../types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-user-circle-2'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='M17.925 20.056a6 6 0 0 0-11.851.001' /><circle
      cx='12'
      cy='11'
      r='4'
    /><circle cx='12' cy='12' r='10' /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'user-circle-2';
export default IconComponent;
