/*! wavesurfer.js 7.12.11 — SPDX-License-Identifier: BSD-3-Clause — Copyright (c) 2012-2023, katspaugh and contributors. All rights reserved. Redistributions must retain this notice; neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. Full text in ./LICENSE. Includes the regions plugin. */
function D(h,t,e,i){return new(e||(e=Promise))((function(n,r){function s(o){try{a(i.next(o))}catch(d){r(d)}}function l(o){try{a(i.throw(o))}catch(d){r(d)}}function a(o){var d;o.done?n(o.value):(d=o.value,d instanceof e?d:new e((function(p){p(d)}))).then(s,l)}a((i=i.apply(h,t||[])).next())}))}var A=class{constructor(){this.listeners={}}on(t,e,i){if(this.listeners[t]||(this.listeners[t]=new Set),i?.once){let n=(...r)=>{this.un(t,n),e(...r)};return this.listeners[t].add(n),()=>this.un(t,n)}return this.listeners[t].add(e),()=>this.un(t,e)}un(t,e){var i;(i=this.listeners[t])===null||i===void 0||i.delete(e)}once(t,e){return this.on(t,e,{once:!0})}unAll(){this.listeners={}}emit(t,...e){this.listeners[t]&&this.listeners[t].forEach((i=>i(...e)))}},$={decode:function(h,t){return D(this,void 0,
void 0,(function*(){let e=new AudioContext({sampleRate:t});try{return yield e.decodeAudioData(h)}finally{e.state!=="closed"&&(yield e.close().catch((()=>{})))}}))},createBuffer:function(h,t){if(!h||h.length===0)throw new Error("channelData must be a non-empty array");if(t<=0)throw new Error("duration must be greater than 0");if(typeof h[0]=="number"&&(h=[h]),!h[0]||h[0].length===0)throw new Error("channelData must contain non-empty channel arrays");(function(i){let n=i[0];if(n.some((r=>r>1||r<-1))){
let r=n.length,s=0;for(let l=0;l<r;l++){let a=Math.abs(n[l]);a>s&&(s=a)}for(let l of i)for(let a=0;a<r;a++)l[a]/=s}})(h);let e=h.map((i=>i instanceof Float32Array?i:Float32Array.from(i)));return{duration:t,length:e[0].length,sampleRate:e[0].length/t,numberOfChannels:e.length,getChannelData:i=>{let n=e[i];if(!n)throw new Error(`Channel ${i} not found`);return n},copyFromChannel:AudioBuffer.prototype.copyFromChannel,copyToChannel:AudioBuffer.prototype.copyToChannel}}};function rt(h,t){let e=t.xmlns?
document.createElementNS(t.xmlns,h):document.createElement(h);for(let[i,n]of Object.entries(t))if(i==="children"&&n)for(let[r,s]of Object.entries(n))s instanceof Node?e.appendChild(s):typeof s=="string"?e.appendChild(document.createTextNode(s)):e.appendChild(rt(r,s));else i==="style"?Object.assign(e.style,n):i==="textContent"?e.textContent=n:e.setAttribute(i,n.toString());return e}function et(h,t,e){let i=rt(h,t||{});return e?.appendChild(i),i}function ot(h){return h instanceof HTMLElement||typeof h==
"object"&&h!==null&&h.nodeType===Node.ELEMENT_NODE&&typeof h.style=="object"}var pt=Object.freeze({__proto__:null,createElement:et,default:et,isHTMLElement:ot}),mt={fetchBlob:function(h,t,e){return D(this,void 0,void 0,(function*(){var i;let n=yield fetch(h,e);if(n.status>=400)throw new Error(`Failed to fetch ${h}: ${n.status} (${n.statusText})`);return(function(r,s,l){D(this,void 0,void 0,(function*(){var a;if(!r.body||!r.headers)return;let o=r.body.getReader(),d=Number(r.headers.get("Content-L\
ength"))||0,p=0,u=()=>{o.cancel()};if(l){if(l.aborted)return void o.cancel();l.addEventListener("abort",u,{once:!0})}try{for(;;){let m=yield o.read();if(m.done)break;if(p+=((a=m.value)===null||a===void 0?void 0:a.length)||0,d>0){let c=Math.round(p/d*100);s(c)}}}catch(m){if(m instanceof DOMException&&m.name==="AbortError")return;console.warn("Progress tracking error:",m)}finally{l&&l.removeEventListener("abort",u)}}))})(n.clone(),t,(i=e?.signal)!==null&&i!==void 0?i:void 0),n.blob()}))}};function P(h){
let t=h,e=new Set;return{get value(){return t},set(i){Object.is(t,i)||(t=i,e.forEach((n=>n(t))))},update(i){this.set(i(t))},subscribe:i=>(e.add(i),()=>e.delete(i))}}function z(h,t){let e=P(h());return t.forEach((i=>i.subscribe((()=>{let n=h();Object.is(e.value,n)||e.set(n)})))),{get value(){return e.value},subscribe:i=>e.subscribe(i)}}function _(h,t){let e,i=()=>{e&&(e(),e=void 0),e=h()},n=t.map((r=>r.subscribe(i)));return i(),()=>{e&&(e(),e=void 0),n.forEach((r=>r()))}}var q=class extends A{get isPlayingSignal(){
return this._isPlaying}get currentTimeSignal(){return this._currentTime}get durationSignal(){return this._duration}get volumeSignal(){return this._volume}get mutedSignal(){return this._muted}get playbackRateSignal(){return this._playbackRate}get seekingSignal(){return this._seeking}constructor(t){super(),this.isExternalMedia=!1,this._ownBlobUrl=null,this.reactiveMediaEventCleanups=[],t.media?(this.media=t.media,this.isExternalMedia=!0):this.media=document.createElement("audio"),this._isPlaying=P(
!1),this._currentTime=P(0),this._duration=P(0),this._volume=P(this.media.volume),this._muted=P(this.media.muted),this._playbackRate=P(this.media.playbackRate||1),this._seeking=P(!1),this.setupReactiveMediaEvents(),t.mediaControls&&(this.media.controls=!0),t.autoplay&&(this.media.autoplay=!0),t.playbackRate!=null&&this.onMediaEvent("canplay",(()=>{t.playbackRate!=null&&(this.media.playbackRate=t.playbackRate)}),{once:!0})}setupReactiveMediaEvents(){this.reactiveMediaEventCleanups.push(this.onMediaEvent(
"play",(()=>{this._isPlaying.set(!0)}))),this.reactiveMediaEventCleanups.push(this.onMediaEvent("pause",(()=>{this._isPlaying.set(!1)}))),this.reactiveMediaEventCleanups.push(this.onMediaEvent("ended",(()=>{this._isPlaying.set(!1)}))),this.reactiveMediaEventCleanups.push(this.onMediaEvent("timeupdate",(()=>{this._currentTime.set(this.media.currentTime)}))),this.reactiveMediaEventCleanups.push(this.onMediaEvent("durationchange",(()=>{this._duration.set(this.media.duration||0)}))),this.reactiveMediaEventCleanups.
push(this.onMediaEvent("loadedmetadata",(()=>{this._duration.set(this.media.duration||0)}))),this.reactiveMediaEventCleanups.push(this.onMediaEvent("seeking",(()=>{this._seeking.set(!0)}))),this.reactiveMediaEventCleanups.push(this.onMediaEvent("seeked",(()=>{this._seeking.set(!1)}))),this.reactiveMediaEventCleanups.push(this.onMediaEvent("volumechange",(()=>{this._volume.set(this.media.volume),this._muted.set(this.media.muted)}))),this.reactiveMediaEventCleanups.push(this.onMediaEvent("ratechan\
ge",(()=>{this._playbackRate.set(this.media.playbackRate)})))}onMediaEvent(t,e,i){return this.media.addEventListener(t,e,i),()=>this.media.removeEventListener(t,e,i)}getSrc(){return this.media.currentSrc||this.media.src||""}revokeSrc(){this._ownBlobUrl&&(URL.revokeObjectURL(this._ownBlobUrl),this._ownBlobUrl=null)}canPlayType(t){return this.media.canPlayType(t)!==""}setSrc(t,e){let i=this.getSrc();if(t&&i===t)return;this.revokeSrc();let n=e instanceof Blob&&(this.canPlayType(e.type)||!t)?URL.createObjectURL(
e):t;if(n!==t&&(this._ownBlobUrl=n),i&&this.media.removeAttribute("src"),n||t)try{this.media.src=n}catch{this.media.src=t}}destroy(){this.reactiveMediaEventCleanups.forEach((t=>t())),this.reactiveMediaEventCleanups=[],this.revokeSrc(),this.unAll(),this.isExternalMedia||(this.media.pause(),this.media.removeAttribute("src"),this.media.load(),this.media.remove())}setMediaElement(t){this.reactiveMediaEventCleanups.forEach((e=>e())),this.reactiveMediaEventCleanups=[],this.media=t,this.setupReactiveMediaEvents()}play(){
return D(this,void 0,void 0,(function*(){try{return yield this.media.play()}catch(t){if(t instanceof DOMException&&t.name==="AbortError")return;throw t}}))}pause(){this.media.pause()}isPlaying(){return!this.media.paused&&!this.media.ended}setTime(t){this.media.currentTime=Math.max(0,Math.min(t,this.getDuration()))}getDuration(){return this.media.duration}getCurrentTime(){return this.media.currentTime}getVolume(){return this.media.volume}setVolume(t){this.media.volume=t}getMuted(){return this.media.
muted}setMuted(t){this.media.muted=t}getPlaybackRate(){return this.media.playbackRate}isSeeking(){return this.media.seeking}setPlaybackRate(t,e){e!=null&&(this.media.preservesPitch=e),this.media.playbackRate=t}getMediaElement(){return this.media}setSinkId(t){return this.media.setSinkId(t)}};function gt({maxTop:h,maxBottom:t,halfHeight:e,vScale:i,barMinHeight:n=0,barAlign:r}){let s=Math.round(h*e*i),l=s+Math.round(t*e*i)||1;return l<n&&(l=n,r||(s=l/2)),{topHeight:s,totalHeight:l}}function vt({barAlign:h,
halfHeight:t,topHeight:e,totalHeight:i,canvasHeight:n}){return h==="top"?0:h==="bottom"?n-i:t-e}function it(h,t,e){let i=t-h.left,n=e-h.top;return[i/h.width,n/h.height]}function at(h){return!!(h.barWidth||h.barGap||h.barAlign)}function nt(h,t){if(!at(t))return h;let e=t.barWidth||.5,i=e+(t.barGap||e/2);return i===0?h:Math.floor(h/i)*i}function st({scrollLeft:h,totalWidth:t,numCanvases:e}){if(t===0)return[0];let i=h/t,n=Math.floor(i*e);return[n-1,n,n+1]}function lt(h){let t=h._cleanup;typeof t=="\
function"&&t()}function ft(h){let t=P({scrollLeft:h.scrollLeft,scrollWidth:h.scrollWidth,clientWidth:h.clientWidth}),e=z((()=>(function(r){let{scrollLeft:s,scrollWidth:l,clientWidth:a}=r;if(l===0)return{startX:0,endX:1};let o=s/l,d=(s+a)/l;return{startX:Math.max(0,Math.min(1,o)),endX:Math.max(0,Math.min(1,d))}})(t.value)),[t]),i=z((()=>(function(r){return{left:r.scrollLeft,right:r.scrollLeft+r.clientWidth}})(t.value)),[t]),n=()=>{t.set({scrollLeft:h.scrollLeft,scrollWidth:h.scrollWidth,clientWidth:h.
clientWidth})};return h.addEventListener("scroll",n,{passive:!0}),{scrollData:t,percentages:e,bounds:i,cleanup:()=>{h.removeEventListener("scroll",n),lt(t)}}}var Y=class extends A{constructor(t,e){super(),this.timeouts=[],this.isScrollable=!1,this.audioData=null,this.resizeObserver=null,this.lastContainerWidth=0,this.isDragging=!1,this.subscriptions=[],this.unsubscribeOnScroll=[],this.dragStream=null,this.scrollStream=null,this.containerInlinePadding=0,this.onClickWrapper=s=>{let l=this.wrapper.
getBoundingClientRect(),[a,o]=it(l,s.clientX,s.clientY);this.emit("click",a,o)},this.onDblClickWrapper=s=>{let l=this.wrapper.getBoundingClientRect(),[a,o]=it(l,s.clientX,s.clientY);this.emit("dblclick",a,o)},this.subscriptions=[],this.options=t;let i=this.parentFromOptionsContainer(t.container);this.parent=i;let[n,r]=this.initHtml();i.appendChild(n),this.container=n,this.scrollContainer=r.querySelector(".scroll"),this.wrapper=r.querySelector(".wrapper"),this.canvasWrapper=r.querySelector(".canv\
ases"),this.progressWrapper=r.querySelector(".progress"),this.cursor=r.querySelector(".cursor"),this.calculateInlinePadding(),e&&r.appendChild(e),this.initEvents()}parentFromOptionsContainer(t){let e;if(typeof t=="string"?e=document.querySelector(t):ot(t)&&(e=t),!e)throw new Error("Container not found");return e}initEvents(){this.wrapper.addEventListener("click",this.onClickWrapper),this.wrapper.addEventListener("dblclick",this.onDblClickWrapper),this.options.dragToSeek!==!0&&typeof this.options.
dragToSeek!="object"||this.initDrag(),this.scrollStream=ft(this.scrollContainer);let t=_((()=>{let{startX:e,endX:i}=this.scrollStream.percentages.value,{left:n,right:r}=this.scrollStream.bounds.value;this.emit("scroll",e,i,n,r)}),[this.scrollStream.percentages,this.scrollStream.bounds]);if(this.subscriptions.push(t),typeof ResizeObserver=="function"){let e=this.createDelay(100);this.resizeObserver=new ResizeObserver((()=>{e().then((()=>this.onContainerResize())).catch((()=>{}))})),this.resizeObserver.
observe(this.scrollContainer)}}onContainerResize(){let t=this.parent.clientWidth;this.calculateInlinePadding(),t===this.lastContainerWidth&&this.options.height!=="auto"||(this.lastContainerWidth=t,this.reRender(),this.emit("resize"))}initDrag(){if(this.dragStream)return;this.dragStream=(function(e,i={}){let{threshold:n=3,mouseButton:r=0,touchDelay:s=100}=i,l=P(null),a=new Map,o=matchMedia("(pointer: coarse)").matches,d=()=>{},p=u=>{if(u.button!==r||a.has(u.pointerId)||(a.set(u.pointerId,u),a.size>
1))return;let m=u.pointerId,c=u.clientX,v=u.clientY,g=!1,C=Date.now(),x=e.getBoundingClientRect(),{left:M,top:E}=x,S=f=>{if(f.pointerId!==m||f.defaultPrevented||a.size>1||o&&Date.now()-C<s)return;let T=f.clientX,L=f.clientY,W=T-c,y=L-v;(g||Math.abs(W)>n||Math.abs(y)>n)&&(f.preventDefault(),f.stopPropagation(),g||(l.set({type:"start",x:c-M,y:v-E}),g=!0),l.set({type:"move",x:T-M,y:L-E,deltaX:W,deltaY:y}),c=T,v=L)},w=f=>{if(a.delete(f.pointerId)){if(f.pointerId===m&&g){let T=f.clientX,L=f.clientY;l.
set({type:"end",x:T-M,y:L-E})}a.size===0&&d()}},k=f=>{f.relatedTarget&&f.relatedTarget!==document.documentElement||w(f)},b=f=>{g&&(f.stopPropagation(),f.preventDefault())},R=f=>{f.defaultPrevented||a.size>1||g&&f.preventDefault()};document.addEventListener("pointermove",S),document.addEventListener("pointerup",w),document.addEventListener("pointerout",k),document.addEventListener("pointercancel",k),document.addEventListener("touchmove",R,{passive:!1}),document.addEventListener("click",b,{capture:!0}),
d=()=>{document.removeEventListener("pointermove",S),document.removeEventListener("pointerup",w),document.removeEventListener("pointerout",k),document.removeEventListener("pointercancel",k),document.removeEventListener("touchmove",R),setTimeout((()=>{document.removeEventListener("click",b,{capture:!0})}),10)}};return e.addEventListener("pointerdown",p),{signal:l,cleanup:()=>{d(),e.removeEventListener("pointerdown",p),a.clear(),lt(l)}}})(this.wrapper);let t=_((()=>{let e=this.dragStream.signal.value;
if(!e)return;let i=this.wrapper.getBoundingClientRect().width,n=(r=e.x/i)<0?0:r>1?1:r;var r;e.type==="start"?(this.isDragging=!0,this.emit("dragstart",n)):e.type==="move"?this.emit("drag",n):e.type==="end"&&(this.isDragging=!1,this.emit("dragend",n))}),[this.dragStream.signal]);this.subscriptions.push(t)}calculateInlinePadding(){let{paddingLeft:t,paddingRight:e}=getComputedStyle(this.scrollContainer),i=parseFloat(t)+parseFloat(e);this.containerInlinePadding=Number.isNaN(i)?0:i}initHtml(){let t=document.
createElement("div"),e=t.attachShadow({mode:"open"}),i=this.options.cspNonce&&typeof this.options.cspNonce=="string"?this.options.cspNonce.replace(/"/g,""):"";return e.innerHTML=`
      <style${i?` nonce="${i}"`:""}>
        :host {
          user-select: none;
          min-width: 1px;
        }
        :host audio {
          display: block;
          width: 100%;
        }
        :host .scroll {
          overflow-x: auto;
          overflow-y: hidden;
          width: 100%;
          position: relative;
        }
        :host .noScrollbar {
          scrollbar-color: transparent;
          scrollbar-width: none;
        }
        :host .noScrollbar::-webkit-scrollbar {
          display: none;
          -webkit-appearance: none;
        }
        :host .wrapper {
          position: relative;
          overflow: visible;
          z-index: 2;
        }
        :host .canvases {
          min-height: ${this.getHeight(this.options.height,this.options.splitChannels)}px;
          pointer-events: none;
        }
        :host .canvases > div {
          position: relative;
        }
        :host canvas {
          display: block;
          position: absolute;
          top: 0;
          image-rendering: pixelated;
        }
        :host .progress {
          pointer-events: none;
          position: absolute;
          z-index: 2;
          top: 0;
          left: 0;
          width: 0;
          height: 100%;
          overflow: hidden;
        }
        :host .progress > div {
          position: relative;
        }
        :host .cursor {
          pointer-events: none;
          position: absolute;
          z-index: 5;
          top: 0;
          left: 0;
          height: 100%;
          border-radius: 2px;
        }
      </style>

      <div class="scroll" part="scroll">
        <div class="wrapper" part="wrapper">
          <div class="canvases" part="canvases"></div>
          <div class="progress" part="progress"></div>
          <div class="cursor" part="cursor"></div>
        </div>
      </div>
    `,[t,e]}setOptions(t){var e;if(this.options.container!==t.container){let i=this.parentFromOptionsContainer(t.container);i.appendChild(this.container),this.parent=i}t.dragToSeek===!0||typeof this.options.dragToSeek=="object"?this.initDrag():((e=this.dragStream)===null||e===void 0||e.cleanup(),this.dragStream=null),this.options=t,this.reRender()}getWrapper(){return this.wrapper}getWidth(){return this.scrollContainer.clientWidth-this.containerInlinePadding}getScroll(){return this.scrollContainer.
scrollLeft}setScroll(t){this.scrollContainer.scrollLeft=t}setScrollPercentage(t){let{scrollWidth:e}=this.scrollContainer,i=e*t;this.setScroll(i)}destroy(){var t;this.wrapper.removeEventListener("click",this.onClickWrapper),this.wrapper.removeEventListener("dblclick",this.onDblClickWrapper),this.timeouts.forEach((e=>e())),this.timeouts=[],this.subscriptions.forEach((e=>e())),this.container.remove(),this.resizeObserver&&(this.resizeObserver.disconnect(),this.resizeObserver=null),(t=this.unsubscribeOnScroll)===
null||t===void 0||t.forEach((e=>e())),this.unsubscribeOnScroll=[],this.dragStream&&(this.dragStream.cleanup(),this.dragStream=null),this.scrollStream&&(this.scrollStream.cleanup(),this.scrollStream=null)}createDelay(t=10){let e,i,n=()=>{e&&(clearTimeout(e),e=void 0),i&&(i(),i=void 0)};return this.timeouts.push(n),()=>new Promise(((r,s)=>{n(),i=s,e=setTimeout((()=>{e=void 0,i=void 0,r()}),t)}))}getHeight(t,e){var i;let n=((i=this.audioData)===null||i===void 0?void 0:i.numberOfChannels)||1;return(function({
optionsHeight:r,optionsSplitChannels:s,parentHeight:l,numberOfChannels:a,defaultHeight:o=128}){if(r==null)return o;let d=Number(r);if(!isNaN(d))return d;if(r==="auto"){let p=l||o;return s?.every((u=>!u.overlay))?p/a:p}return o})({optionsHeight:t,optionsSplitChannels:e,parentHeight:this.parent.clientHeight,numberOfChannels:n,defaultHeight:128})}convertColorValues(t,e){return(function(i,n,r){if(!Array.isArray(i))return i||"";if(i.length===0)return"#999";if(i.length<2)return i[0]||"";let s=document.
createElement("canvas"),l=s.getContext("2d");if(!l)return i[0]||"";let a=r||s.height*n,o=l.createLinearGradient(0,0,0,a),d=1/(i.length-1);return i.forEach(((p,u)=>{o.addColorStop(u*d,p)})),o})(t,this.getPixelRatio(),e?.canvas.height)}getPixelRatio(){return t=window.devicePixelRatio,Math.max(1,t||1);var t}renderBarWaveform(t,e,i,n){let{width:r,height:s}=i.canvas,{halfHeight:l,barWidth:a,barRadius:o,barIndexScale:d,barSpacing:p,barMinHeight:u}=(function({width:c,height:v,length:g,options:C,pixelRatio:x}){
let M=v/2,E=C.barWidth?C.barWidth*x:1,S=C.barGap?C.barGap*x:C.barWidth?E/2:0,w=E+S||1;return{halfHeight:M,barWidth:E,barGap:S,barRadius:C.barRadius||0,barMinHeight:C.barMinHeight?C.barMinHeight*x:0,barIndexScale:g>0?c/w/g:0,barSpacing:w}})({width:r,height:s,length:(t[0]||[]).length,options:e,pixelRatio:this.getPixelRatio()}),m=(function({channelData:c,barIndexScale:v,barSpacing:g,barWidth:C,halfHeight:x,vScale:M,canvasHeight:E,barAlign:S,barMinHeight:w}){let k=c[0]||[],b=c[1]||k,R=k.length,f=[],
T=0,L=0,W=0;for(let y=0;y<=R;y++){let O=Math.round(y*v);if(O>T){let{topHeight:ct,totalHeight:tt}=gt({maxTop:L,maxBottom:W,halfHeight:x,vScale:M,barMinHeight:w,barAlign:S}),ut=vt({barAlign:S,halfHeight:x,topHeight:ct,totalHeight:tt,canvasHeight:E});f.push({x:T*g,y:ut,width:C,height:tt}),T=O,L=0,W=0}let K=Math.abs(k[y]||0),Q=Math.abs(b[y]||0);K>L&&(L=K),Q>W&&(W=Q)}return f})({channelData:t,barIndexScale:d,barSpacing:p,barWidth:a,halfHeight:l,vScale:n,canvasHeight:s,barAlign:e.barAlign,barMinHeight:u});
i.beginPath();for(let c of m)o&&"roundRect"in i?i.roundRect(c.x,c.y,c.width,c.height,o):i.rect(c.x,c.y,c.width,c.height);i.fill(),i.closePath()}renderLineWaveform(t,e,i,n){let{width:r,height:s}=i.canvas,l=(function({channelData:a,width:o,height:d,vScale:p}){let u=d/2,m=a[0]||[];return[m,a[1]||m].map(((c,v)=>{let g=c.length,C=g?o/g:0,x=u,M=v===0?-1:1,E=[{x:0,y:x}],S=0,w=0;for(let k=0;k<=g;k++){let b=Math.round(k*C);if(b>S){let f=x+(Math.round(w*u*p)||1)*M;E.push({x:S,y:f}),S=b,w=0}let R=Math.abs(
c[k]||0);R>w&&(w=R)}return E.push({x:S,y:x}),E}))})({channelData:t,width:r,height:s,vScale:n});i.beginPath();for(let a of l)if(a.length){i.moveTo(a[0].x,a[0].y);for(let o=1;o<a.length;o++){let d=a[o];i.lineTo(d.x,d.y)}}i.fill(),i.closePath()}renderWaveform(t,e,i){if(i.fillStyle=this.convertColorValues(e.waveColor,i),e.renderFunction)return void e.renderFunction(t,i);let n=(function({channelData:r,barHeight:s,normalize:l,maxPeak:a}){var o;let d=s||1;if(!l)return d;let p=r[0];if(!p||p.length===0)return d;
let u=a??0;if(!a)for(let m=0;m<p.length;m++){let c=(o=p[m])!==null&&o!==void 0?o:0,v=Math.abs(c);v>u&&(u=v)}return u?d/u:d})({channelData:t,barHeight:e.barHeight,normalize:e.normalize,maxPeak:e.maxPeak});at(e)?this.renderBarWaveform(t,e,i,n):this.renderLineWaveform(t,e,i,n)}renderSingleCanvas(t,e,i,n,r,s,l){let a=this.getPixelRatio(),o=document.createElement("canvas");o.width=Math.round(i*a),o.height=Math.round(n*a),o.style.width=`${i}px`,o.style.height=`${n}px`,o.style.left=`${Math.round(r)}px`,
s.appendChild(o);let d=o.getContext("2d");if(e.renderFunction?(d.fillStyle=this.convertColorValues(e.waveColor,d),e.renderFunction(t,d)):this.renderWaveform(t,e,d),o.width>0&&o.height>0){let p=o.cloneNode(),u=p.getContext("2d");u.drawImage(o,0,0),u.globalCompositeOperation="source-in",u.fillStyle=this.convertColorValues(e.progressColor,u),u.fillRect(0,0,o.width,o.height),l.appendChild(p)}}renderMultiCanvas(t,e,i,n,r,s){let l=this.getPixelRatio(),{clientWidth:a}=this.scrollContainer,o=i/l,d=(function({
clientWidth:c,totalWidth:v,options:g}){return nt(Math.min(8e3,c,v),g)})({clientWidth:a,totalWidth:o,options:e}),p={};if(d===0)return;let u=c=>{if(c<0||c>=m||p[c])return;p[c]=!0;let v=c*d,g=Math.min(o-v,d);if(g=nt(g,e),g<=0)return;let C=(function({channelData:x,offset:M,clampedWidth:E,totalWidth:S}){return x.map((w=>{let k=Math.floor(M/S*w.length),b=Math.floor((M+E)/S*w.length);return w.slice(k,b)}))})({channelData:t,offset:v,clampedWidth:g,totalWidth:o});this.renderSingleCanvas(C,e,g,n,v,r,s)},m=Math.
ceil(o/d);if(!this.isScrollable){for(let c=0;c<m;c++)u(c);return}if(st({scrollLeft:this.scrollContainer.scrollLeft,totalWidth:o,numCanvases:m}).forEach((c=>u(c))),m>1){let c=this.on("scroll",(()=>{let{scrollLeft:v}=this.scrollContainer;Object.keys(p).length>10&&(r.innerHTML="",s.innerHTML="",p={}),st({scrollLeft:v,totalWidth:o,numCanvases:m}).forEach((g=>u(g)))}));this.unsubscribeOnScroll.push(c)}}renderChannel(t,e,i,n){var{overlay:r}=e,s=(function(d,p){var u={};for(var m in d)Object.prototype.hasOwnProperty.
call(d,m)&&p.indexOf(m)<0&&(u[m]=d[m]);if(d!=null&&typeof Object.getOwnPropertySymbols=="function"){var c=0;for(m=Object.getOwnPropertySymbols(d);c<m.length;c++)p.indexOf(m[c])<0&&Object.prototype.propertyIsEnumerable.call(d,m[c])&&(u[m[c]]=d[m[c]])}return u})(e,["overlay"]);let l=document.createElement("div"),a=this.getHeight(s.height,s.splitChannels);l.style.height=`${a}px`,r&&n>0&&(l.style.marginTop=`-${a}px`),this.canvasWrapper.style.minHeight=`${a}px`,this.canvasWrapper.appendChild(l);let o=l.
cloneNode();this.progressWrapper.appendChild(o),this.renderMultiCanvas(t,s,i,a,l,o)}render(t){return D(this,void 0,void 0,(function*(){var e;this.timeouts.forEach((o=>o())),this.timeouts=[],this.unsubscribeOnScroll.forEach((o=>o())),this.unsubscribeOnScroll=[],this.canvasWrapper.innerHTML="",this.progressWrapper.innerHTML="",this.options.width!=null&&(this.scrollContainer.style.width=typeof this.options.width=="number"?`${this.options.width}px`:this.options.width);let i=this.getPixelRatio(),n=this.
scrollContainer.clientWidth-this.containerInlinePadding,{scrollWidth:r,isScrollable:s,useParentWidth:l,width:a}=(function({duration:o,minPxPerSec:d=0,parentWidth:p,fillParent:u,pixelRatio:m}){let c=Math.ceil(o*d),v=c>p,g=!!(u&&!v);return{scrollWidth:c,isScrollable:v,useParentWidth:g,width:(g?p:c)*m}})({duration:t.duration,minPxPerSec:this.options.minPxPerSec||0,parentWidth:n,fillParent:this.options.fillParent,pixelRatio:i});if(this.isScrollable=s,this.wrapper.style.width=l?"100%":`${r}px`,this.scrollContainer.
style.overflowX=this.isScrollable?"auto":"hidden",this.scrollContainer.classList.toggle("noScrollbar",!!this.options.hideScrollbar),this.cursor.style.backgroundColor=`${this.options.cursorColor||this.options.progressColor}`,this.cursor.style.width=`${this.options.cursorWidth}px`,this.audioData=t,this.emit("render"),this.options.splitChannels)for(let o=0;o<t.numberOfChannels;o++){let d=Object.assign(Object.assign({},this.options),(e=this.options.splitChannels)===null||e===void 0?void 0:e[o]);this.
renderChannel([t.getChannelData(o)],d,a,o)}else{let o=[t.getChannelData(0)];t.numberOfChannels>1&&o.push(t.getChannelData(1)),this.renderChannel(o,this.options,a,0)}Promise.resolve().then((()=>this.emit("rendered")))}))}reRender(){if(this.unsubscribeOnScroll.forEach((i=>i())),this.unsubscribeOnScroll=[],!this.audioData)return;let{scrollWidth:t}=this.scrollContainer,{right:e}=this.progressWrapper.getBoundingClientRect();if(this.render(this.audioData),!this.isScrollable&&this.scrollContainer.scrollLeft)
this.scrollContainer.scrollLeft=0;else if(this.isScrollable&&t!==this.scrollContainer.scrollWidth){let{right:i}=this.progressWrapper.getBoundingClientRect(),n=(function(r){let s=2*r;return(s<0?Math.floor(s):Math.ceil(s))/2})(i-e);this.scrollContainer.scrollLeft+=n}}zoom(t){this.options.minPxPerSec=t,this.reRender()}scrollIntoView(t,e=!1){var i;let{scrollLeft:n,scrollWidth:r,clientWidth:s}=this.scrollContainer,l=t*r,a=n,o=n+s,d=s/2;if(this.isDragging)l+30>o?this.scrollContainer.scrollLeft+=30:l-30<
a&&(this.scrollContainer.scrollLeft-=30);else{(l<a||l>o)&&(this.scrollContainer.scrollLeft=l-(this.options.autoCenter?d:0));let p=l-n-d;if(e&&this.options.autoCenter&&p>0){let u=(i=this.audioData)===null||i===void 0?void 0:i.duration;if(u===void 0||u<=0)return void(this.scrollContainer.scrollLeft+=p);let m=r/u;this.scrollContainer.scrollLeft+=m<=600?Math.min(p,10):p}}}renderProgress(t,e){if(isNaN(t))return;let i=100*t;this.canvasWrapper.style.clipPath=`polygon(${i}% 0%, 100% 0%, 100% 100%, ${i}%\
 100%)`,this.progressWrapper.style.width=`${i}%`,this.cursor.style.left=`${i}%`,this.cursor.style.transform=this.options.cursorWidth?`translateX(-${t*this.options.cursorWidth}px)`:"",this.isScrollable&&this.options.autoScroll&&this.audioData&&this.audioData.duration>0&&this.scrollIntoView(t,e)}exportImage(t,e,i){return D(this,void 0,void 0,(function*(){let n=this.canvasWrapper.querySelectorAll("canvas");if(!n.length)throw new Error("No waveform data");if(i==="dataURL"){let r=Array.from(n).map((s=>s.
toDataURL(t,e)));return Promise.resolve(r)}return Promise.all(Array.from(n).map((r=>new Promise(((s,l)=>{r.toBlob((a=>{a?s(a):l(new Error("Could not export image"))}),t,e)})))))}))}},G=class extends A{constructor(){super(...arguments),this.animationFrameId=null,this.isRunning=!1}start(){if(this.isRunning)return;this.isRunning=!0;let t=()=>{this.isRunning&&(this.emit("tick"),this.animationFrameId=requestAnimationFrame(t))};t()}stop(){this.isRunning=!1,this.animationFrameId!==null&&(cancelAnimationFrame(
this.animationFrameId),this.animationFrameId=null)}destroy(){this.stop(),this.unAll()}},I=class extends A{constructor(t){super(),this.bufferNode=null,this.playStartTime=0,this.playbackPosition=0,this._muted=!1,this._playbackRate=1,this._duration=void 0,this.buffer=null,this.currentSrc="",this.paused=!0,this.crossOrigin=null,this.seeking=!1,this.autoplay=!1,this.addEventListener=this.on,this.removeEventListener=this.un,this._destroyed=!1,(function(){let e=globalThis.navigator;if(e?.audioSession)try{
e.audioSession.type="playback"}catch(i){console.warn("Setting navigator.audioSession.type failed:",i)}})(),this.audioContext=t||new AudioContext,this.gainNode=this.audioContext.createGain(),this.gainNode.connect(this.audioContext.destination)}load(){return D(this,void 0,void 0,(function*(){}))}remove(){this.destroy()}destroy(){if(!this._destroyed){if(this._destroyed=!0,this.currentSrc="",this.bufferNode){this.bufferNode.onended=null;try{this.bufferNode.stop()}catch{}this.bufferNode.disconnect(),
this.bufferNode=null}this.gainNode.disconnect(),typeof this.audioContext.close=="function"&&Promise.resolve(this.audioContext.close.call(this.audioContext)).catch((()=>{})),this.buffer=null,this.unAll()}}get src(){return this.currentSrc}set src(t){if(this.currentSrc=t,this._duration=void 0,!t)return this.buffer=null,void this.emit("emptied");fetch(t).then((e=>{if(e.status>=400)throw new Error(`Failed to fetch ${t}: ${e.status} (${e.statusText})`);return e.arrayBuffer()})).then((e=>this.currentSrc!==
t?null:this.audioContext.decodeAudioData(e))).then((e=>{this.currentSrc===t&&(this.buffer=e,this.emit("loadedmetadata"),this.emit("canplay"),this.autoplay&&this.play())})).catch((e=>{console.error("WebAudioPlayer load error:",e)}))}_play(){if(!this.paused)return;this.paused=!1,this.bufferNode&&(this.bufferNode.onended=null,this.bufferNode.disconnect()),this.bufferNode=this.audioContext.createBufferSource(),this.buffer&&(this.bufferNode.buffer=this.buffer),this.bufferNode.playbackRate.value=this.
_playbackRate,this.bufferNode.connect(this.gainNode);let t=this.playbackPosition;(t>=this.duration||t<0)&&(t=0,this.playbackPosition=0),this.bufferNode.start(this.audioContext.currentTime,t),this.playStartTime=this.audioContext.currentTime,this.bufferNode.onended=()=>{!this.paused&&this.duration-this.currentTime<.01&&(this.pause(),this.emit("ended"))}}_pause(){if(this.paused=!0,this.bufferNode){this.bufferNode.onended=null;try{this.bufferNode.stop()}catch{}}this.playbackPosition+=(this.audioContext.
currentTime-this.playStartTime)*this._playbackRate}play(){return D(this,void 0,void 0,(function*(){this.paused&&(this._play(),this.emit("play"))}))}pause(){this.paused||(this._pause(),this.emit("pause"))}stopAt(t){let e=(t-this.currentTime)/this._playbackRate,i=this.bufferNode;i?.stop(this.audioContext.currentTime+e),i?.addEventListener("ended",(()=>{i===this.bufferNode&&(this.bufferNode=null,this.pause(),this.playbackPosition=Math.min(t,this.duration),this.emit("timeupdate"))}),{once:!0})}setSinkId(t){
return D(this,void 0,void 0,(function*(){return this.audioContext.setSinkId(t)}))}get playbackRate(){return this._playbackRate}set playbackRate(t){let e=!this.paused;e&&this._pause(),this._playbackRate=t,e&&this._play(),this.bufferNode&&(this.bufferNode.playbackRate.value=t)}get currentTime(){return this.paused?this.playbackPosition:this.playbackPosition+(this.audioContext.currentTime-this.playStartTime)*this._playbackRate}set currentTime(t){let e=!this.paused;e&&this._pause(),this.playbackPosition=
t,e&&this._play(),this.emit("seeking"),this.emit("timeupdate")}get duration(){var t,e;return(t=this._duration)!==null&&t!==void 0?t:((e=this.buffer)===null||e===void 0?void 0:e.duration)||0}set duration(t){this._duration=t}get volume(){return this.gainNode.gain.value}set volume(t){this.gainNode.gain.value=t,this.emit("volumechange")}get muted(){return this._muted}set muted(t){this._muted!==t&&(this._muted=t,this._muted?this.gainNode.disconnect():this.gainNode.connect(this.audioContext.destination))}canPlayType(t){
return/^(audio|video)\//.test(t)}getGainNode(){return this.gainNode}getChannelData(){let t=[];if(!this.buffer)return t;let e=this.buffer.numberOfChannels;for(let i=0;i<e;i++)t.push(this.buffer.getChannelData(i));return t}removeAttribute(t){switch(t){case"src":this.src="";break;case"playbackRate":this.playbackRate=0;break;case"currentTime":this.currentTime=0;break;case"duration":this.duration=0;break;case"volume":this.volume=0;break;case"muted":this.muted=!1}}},bt={waveColor:"#999",progressColor:"\
#555",cursorWidth:1,minPxPerSec:0,fillParent:!0,interact:!0,dragToSeek:!1,autoScroll:!0,autoCenter:!0,sampleRate:8e3},H=class h extends q{static create(t){return new h(t)}getState(){return this.wavesurferState}getRenderer(){return this.renderer}constructor(t){let e=t.media||(t.backend==="WebAudio"?new I:void 0);super({media:e,mediaControls:t.mediaControls,autoplay:t.autoplay,playbackRate:t.audioRate}),this.plugins=[],this.decodedData=null,this.stopAtPosition=null,this.subscriptions=[],this.mediaSubscriptions=
[],this.abortController=null,this._isDestroyed=!1,this._loadVersion=0,this.reactiveCleanups=[],this.options=Object.assign({},bt,t);let{state:i,actions:n}=(function(l){var a,o,d,p,u,m;let c=(a=l?.currentTime)!==null&&a!==void 0?a:P(0),v=(o=l?.duration)!==null&&o!==void 0?o:P(0),g=(d=l?.isPlaying)!==null&&d!==void 0?d:P(!1),C=(p=l?.isSeeking)!==null&&p!==void 0?p:P(!1),x=(u=l?.volume)!==null&&u!==void 0?u:P(1),M=(m=l?.playbackRate)!==null&&m!==void 0?m:P(1),E=P(null),S=P(null),w=P(""),k=P(0),b=P(0),
R=z((()=>!g.value),[g]),f=z((()=>E.value!==null),[E]),T=z((()=>f.value&&v.value>0),[f,v]),L=z((()=>c.value),[c]),W=z((()=>v.value>0?c.value/v.value:0),[c,v]);return{state:{currentTime:c,duration:v,isPlaying:g,isPaused:R,isSeeking:C,volume:x,playbackRate:M,audioBuffer:E,peaks:S,url:w,zoom:k,scrollPosition:b,canPlay:f,isReady:T,progress:L,progressPercent:W},actions:{setCurrentTime:y=>{let O=Math.max(0,Math.min(v.value||1/0,y));c.set(O)},setDuration:y=>{v.set(Math.max(0,y))},setPlaying:y=>{g.set(y)},
setSeeking:y=>{C.set(y)},setVolume:y=>{let O=Math.max(0,Math.min(1,y));x.set(O)},setPlaybackRate:y=>{let O=Math.max(.1,Math.min(16,y));M.set(O)},setAudioBuffer:y=>{E.set(y),y&&v.set(y.duration)},setPeaks:y=>{S.set(y)},setUrl:y=>{w.set(y)},setZoom:y=>{k.set(Math.max(0,y))},setScrollPosition:y=>{b.set(Math.max(0,y))}}}})({isPlaying:this.isPlayingSignal,currentTime:this.currentTimeSignal,duration:this.durationSignal,volume:this.volumeSignal,playbackRate:this.playbackRateSignal,isSeeking:this.seekingSignal});
this.wavesurferState=i,this.wavesurferActions=n,this.timer=new G;let r=e?void 0:this.getMediaElement();this.renderer=new Y(this.options,r),this.initPlayerEvents(),this.initRendererEvents(),this.initTimerEvents(),this.initReactiveState(),this.initPlugins();let s=this.options.url||this.getSrc()||"";Promise.resolve().then((()=>{this.emit("init");let{peaks:l,duration:a}=this.options;(s||l&&a)&&this.load(s,l,a).catch((()=>{}))}))}updateProgress(t=this.getCurrentTime()){return this.renderer.renderProgress(
t/this.getDuration(),this.isPlaying()),t}initTimerEvents(){this.subscriptions.push(this.timer.on("tick",(()=>{if(!this.isSeeking()){let t=this.updateProgress();if(this.emit("timeupdate",t),this.emit("audioprocess",t),this.stopAtPosition!=null&&this.isPlaying()&&t>=this.stopAtPosition){let e=this.stopAtPosition;this.pause(),this.setTime(e)}}})))}initReactiveState(){this.reactiveCleanups.push((function(t,e){let i=[];i.push(_((()=>{let s=t.isPlaying.value;e.emit(s?"play":"pause")}),[t.isPlaying])),
i.push(_((()=>{let s=t.currentTime.value;e.emit("timeupdate",s),t.isPlaying.value&&e.emit("audioprocess",s)}),[t.currentTime,t.isPlaying])),i.push(_((()=>{t.isSeeking.value&&e.emit("seeking",t.currentTime.value)}),[t.isSeeking,t.currentTime]));let n=!1;i.push(_((()=>{t.isReady.value&&!n&&(n=!0,e.emit("ready",t.duration.value))}),[t.isReady,t.duration])),i.push(_((()=>{t.audioBuffer.value===null&&(n=!1)}),[t.audioBuffer]));let r=!1;return i.push(_((()=>{let s=t.isPlaying.value,l=t.currentTime.value,
a=t.duration.value,o=a>0&&l>=a;r&&!s&&o&&e.emit("finish"),r=s&&o}),[t.isPlaying,t.currentTime,t.duration])),i.push(_((()=>{let s=t.zoom.value;s>0&&e.emit("zoom",s)}),[t.zoom])),()=>{i.forEach((s=>s()))}})(this.wavesurferState,{emit:this.emit.bind(this)}))}initPlayerEvents(){this.isPlaying()&&(this.emit("play"),this.timer.start()),this.mediaSubscriptions.push(this.onMediaEvent("timeupdate",(()=>{let t=this.updateProgress();this.emit("timeupdate",t)})),this.onMediaEvent("play",(()=>{this.emit("pla\
y"),this.timer.start()})),this.onMediaEvent("pause",(()=>{this.emit("pause"),this.timer.stop(),this.stopAtPosition=null})),this.onMediaEvent("emptied",(()=>{this.timer.stop(),this.stopAtPosition=null})),this.onMediaEvent("ended",(()=>{this.emit("timeupdate",this.getDuration()),this.emit("finish"),this.stopAtPosition=null})),this.onMediaEvent("seeking",(()=>{this.emit("seeking",this.getCurrentTime())})),this.onMediaEvent("error",(()=>{var t;this.emit("error",(t=this.getMediaElement().error)!==null&&
t!==void 0?t:new Error("Media error")),this.stopAtPosition=null})))}initRendererEvents(){this.subscriptions.push(this.renderer.on("click",((t,e)=>{this.options.interact&&(this.seekTo(t),this.emit("interaction",t*this.getDuration()),this.emit("click",t,e))})),this.renderer.on("dblclick",((t,e)=>{this.emit("dblclick",t,e)})),this.renderer.on("scroll",((t,e,i,n)=>{let r=this.getDuration();this.emit("scroll",t*r,e*r,i,n)})),this.renderer.on("render",(()=>{this.emit("redraw")})),this.renderer.on("ren\
dered",(()=>{this.emit("redrawcomplete")})),this.renderer.on("dragstart",(t=>{this.emit("dragstart",t)})),this.renderer.on("dragend",(t=>{this.emit("dragend",t)})),this.renderer.on("resize",(()=>{this.emit("resize")})));{let t,e=this.renderer.on("drag",(i=>{var n;if(!this.options.interact)return;this.renderer.renderProgress(i),clearTimeout(t);let r=0,s=this.options.dragToSeek;this.isPlaying()?r=0:s===!0?r=200:s&&typeof s=="object"&&(r=(n=s.debounceTime)!==null&&n!==void 0?n:200),t=setTimeout((()=>{
this.seekTo(i)}),r),this.emit("interaction",i*this.getDuration()),this.emit("drag",i)}));this.subscriptions.push((()=>{clearTimeout(t),e()}))}}initPlugins(){var t;!((t=this.options.plugins)===null||t===void 0)&&t.length&&this.options.plugins.forEach((e=>{this.registerPlugin(e)}))}unsubscribePlayerEvents(){this.mediaSubscriptions.forEach((t=>t())),this.mediaSubscriptions=[]}setOptions(t){this.options=Object.assign({},this.options,t),t.duration&&!t.peaks&&(this.decodedData=$.createBuffer(this.exportPeaks(),
t.duration)),t.peaks&&t.duration&&(this.decodedData=$.createBuffer(t.peaks,t.duration)),this.renderer.setOptions(this.options),t.audioRate&&this.setPlaybackRate(t.audioRate),t.mediaControls!=null&&(this.getMediaElement().controls=t.mediaControls)}registerPlugin(t){if(this.plugins.includes(t))return t;t._init(this),this.plugins.push(t);let e=t.once("destroy",(()=>{this.plugins=this.plugins.filter((i=>i!==t)),this.subscriptions=this.subscriptions.filter((i=>i!==e))}));return this.subscriptions.push(
e),t}unregisterPlugin(t){this.plugins=this.plugins.filter((e=>e!==t)),t.destroy()}getWrapper(){return this.renderer.getWrapper()}getWidth(){return this.renderer.getWidth()}getScroll(){return this.renderer.getScroll()}setScroll(t){return this.renderer.setScroll(t)}setScrollTime(t){let e=t/this.getDuration();this.renderer.setScrollPercentage(e)}getActivePlugins(){return this.plugins}loadAudio(t,e,i,n){return D(this,void 0,void 0,(function*(){var r;let s=++this._loadVersion;if(this._isDestroyed=!1,
this.emit("load",t),!this.options.media&&this.isPlaying()&&this.pause(),this.decodedData=null,this.stopAtPosition=null,(r=this.abortController)===null||r===void 0||r.abort(),this.abortController=null,!e&&!i){let a=this.options.fetchParams||{};window.AbortController&&!a.signal&&(this.abortController=new AbortController,a.signal=this.abortController.signal);let o=p=>this.emit("loading",p);if(e=yield mt.fetchBlob(t,o,a),this._isDestroyed||s!==this._loadVersion)return;let d=this.options.blobMimeType;
d&&(e=new Blob([e],{type:d}))}if(this._isDestroyed||s!==this._loadVersion)return;this.setSrc(t,e);let l=yield new Promise((a=>{let o=n||this.getDuration();o?a(o):this.mediaSubscriptions.push(this.onMediaEvent("loadedmetadata",(()=>a(this.getDuration())),{once:!0}))}));if(!this._isDestroyed&&s===this._loadVersion){if(!t&&!e){let a=this.getMediaElement();a instanceof I&&(a.duration=l)}if(i)this.decodedData=$.createBuffer(i,l||0);else if(e){let a=yield e.arrayBuffer();if(this._isDestroyed||s!==this.
_loadVersion)return;this.decodedData=yield $.decode(a,this.options.sampleRate)}this._isDestroyed||s!==this._loadVersion||(this.decodedData&&(this.emit("decode",this.getDuration()),this.renderer.render(this.decodedData)),this.emit("ready",this.getDuration()))}}))}load(t,e,i){return D(this,void 0,void 0,(function*(){try{return yield this.loadAudio(t,void 0,e,i)}catch(n){throw this.emit("error",n),n}}))}loadBlob(t,e,i){return D(this,void 0,void 0,(function*(){try{return yield this.loadAudio("",t,e,
i)}catch(n){throw this.emit("error",n),n}}))}zoom(t){if(!this.decodedData)throw new Error("No audio loaded");this.renderer.zoom(t),this.emit("zoom",t)}getDecodedData(){return this.decodedData}exportPeaks({channels:t=2,maxLength:e=8e3,precision:i=1e4}={}){if(!this.decodedData)throw new Error("The audio has not been decoded yet");let n=Math.min(t,this.decodedData.numberOfChannels),r=[];for(let s=0;s<n;s++){let l=this.decodedData.getChannelData(s),a=[],o=l.length/e;for(let d=0;d<e;d++){let p=l.slice(
Math.floor(d*o),Math.ceil((d+1)*o)),u=0;for(let m=0;m<p.length;m++){let c=p[m];Math.abs(c)>Math.abs(u)&&(u=c)}a.push(Math.round(u*i)/i)}r.push(a)}return r}getDuration(){let t=super.getDuration()||0;return t!==0&&t!==1/0||!this.decodedData||(t=this.decodedData.duration),t}toggleInteraction(t){this.options.interact=t}setTime(t){this.stopAtPosition=null,super.setTime(t),this.updateProgress(t),this.emit("timeupdate",t)}seekTo(t){let e=this.getDuration()*t;this.setTime(e)}play(t,e){let i=Object.create(
null,{play:{get:()=>super.play}});return D(this,void 0,void 0,(function*(){t!=null&&this.setTime(t);let n=yield i.play.call(this);return e!=null&&(this.media instanceof I?this.media.stopAt(e):this.stopAtPosition=e),n}))}playPause(){return D(this,void 0,void 0,(function*(){return this.isPlaying()?this.pause():this.play()}))}stop(){this.pause(),this.setTime(0)}skip(t){this.setTime(this.getCurrentTime()+t)}empty(){this.load("",[[0]],.001)}setMediaElement(t){this.unsubscribePlayerEvents(),super.setMediaElement(
t),this.initPlayerEvents()}exportImage(){return D(this,arguments,void 0,(function*(t="image/png",e=1,i="dataURL"){return this.renderer.exportImage(t,e,i)}))}destroy(){var t;this._isDestroyed=!0,this.emit("destroy"),(t=this.abortController)===null||t===void 0||t.abort(),this.plugins.forEach((e=>e.destroy())),this.subscriptions.forEach((e=>e())),this.unsubscribePlayerEvents(),this.reactiveCleanups.forEach((e=>e())),this.reactiveCleanups=[],this.timer.destroy(),this.renderer.destroy(),super.destroy()}};
H.BasePlugin=class extends A{constructor(h){super(),this.subscriptions=[],this.isDestroyed=!1,this.options=h}onInit(){}_init(h){this.isDestroyed&&(this.subscriptions=[],this.isDestroyed=!1),this.wavesurfer=h,this.onInit()}destroy(){this.emit("destroy"),this.subscriptions.forEach((h=>h())),this.subscriptions=[],this.isDestroyed=!0,this.wavesurfer=void 0}},H.dom=pt;var U=class{constructor(){this.listeners={}}on(t,e,i){if(this.listeners[t]||(this.listeners[t]=new Set),i?.once){let n=(...r)=>{this.un(t,n),e(...r)};return this.listeners[t].add(n),()=>this.un(t,n)}return this.listeners[t].add(e),()=>this.un(t,e)}un(t,e){var i;(i=this.listeners[t])===null||i===void 0||i.delete(e)}once(t,e){return this.on(t,e,{once:!0})}unAll(){this.listeners={}}emit(t,...e){this.listeners[t]&&this.listeners[t].forEach((i=>i(...e)))}},Z=class extends U{constructor(t){super(),this.
subscriptions=[],this.isDestroyed=!1,this.options=t}onInit(){}_init(t){this.isDestroyed&&(this.subscriptions=[],this.isDestroyed=!1),this.wavesurfer=t,this.onInit()}destroy(){this.emit("destroy"),this.subscriptions.forEach((t=>t())),this.subscriptions=[],this.isDestroyed=!0,this.wavesurfer=void 0}};function ht(h,t){let e=t.xmlns?document.createElementNS(t.xmlns,h):document.createElement(h);for(let[i,n]of Object.entries(t))if(i==="children"&&n)for(let[r,s]of Object.entries(n))s instanceof Node?e.
appendChild(s):typeof s=="string"?e.appendChild(document.createTextNode(s)):e.appendChild(ht(r,s));else i==="style"?Object.assign(e.style,n):i==="textContent"?e.textContent=n:e.setAttribute(i,n.toString());return e}function j(h,t,e){let i=ht(h,t||{});return e?.appendChild(i),i}function dt(h){let t=h,e=new Set;return{get value(){return t},set(i){Object.is(t,i)||(t=i,e.forEach((n=>n(t))))},update(i){this.set(i(t))},subscribe:i=>(e.add(i),()=>e.delete(i))}}function X(h,t){let e,i=()=>{e&&(e(),e=void 0),
e=h()},n=t.map((r=>r.subscribe(i)));return i(),()=>{e&&(e(),e=void 0),n.forEach((r=>r()))}}function N(h,t){let e=dt(null),i=n=>{e.set(n)};return h.addEventListener(t,i),e._cleanup=()=>{h.removeEventListener(t,i)},e}function B(h){let t=h._cleanup;typeof t=="function"&&t()}function F(h,t={}){let{threshold:e=3,mouseButton:i=0,touchDelay:n=100}=t,r=dt(null),s=new Map,l=matchMedia("(pointer: coarse)").matches,a=()=>{},o=d=>{if(d.button!==i||s.has(d.pointerId)||(s.set(d.pointerId,d),s.size>1))return;let p=d.
pointerId,u=d.clientX,m=d.clientY,c=!1,v=Date.now(),g=h.getBoundingClientRect(),{left:C,top:x}=g,M=b=>{if(b.pointerId!==p||b.defaultPrevented||s.size>1||l&&Date.now()-v<n)return;let R=b.clientX,f=b.clientY,T=R-u,L=f-m;(c||Math.abs(T)>e||Math.abs(L)>e)&&(b.preventDefault(),b.stopPropagation(),c||(r.set({type:"start",x:u-C,y:m-x}),c=!0),r.set({type:"move",x:R-C,y:f-x,deltaX:T,deltaY:L}),u=R,m=f)},E=b=>{if(s.delete(b.pointerId)){if(b.pointerId===p&&c){let R=b.clientX,f=b.clientY;r.set({type:"end",x:R-
C,y:f-x})}s.size===0&&a()}},S=b=>{b.relatedTarget&&b.relatedTarget!==document.documentElement||E(b)},w=b=>{c&&(b.stopPropagation(),b.preventDefault())},k=b=>{b.defaultPrevented||s.size>1||c&&b.preventDefault()};document.addEventListener("pointermove",M),document.addEventListener("pointerup",E),document.addEventListener("pointerout",S),document.addEventListener("pointercancel",S),document.addEventListener("touchmove",k,{passive:!1}),document.addEventListener("click",w,{capture:!0}),a=()=>{document.
removeEventListener("pointermove",M),document.removeEventListener("pointerup",E),document.removeEventListener("pointerout",S),document.removeEventListener("pointercancel",S),document.removeEventListener("touchmove",k),setTimeout((()=>{document.removeEventListener("click",w,{capture:!0})}),10)}};return h.addEventListener("pointerdown",o),{signal:r,cleanup:()=>{a(),h.removeEventListener("pointerdown",o),s.clear(),B(r)}}}var V=class extends U{constructor(t,e,i=0){var n,r,s,l,a,o,d,p,u,m;super(),this.
totalDuration=e,this.numberOfChannels=i,this.element=null,this.minLength=0,this.maxLength=1/0,this.contentEditable=!1,this.subscriptions=[],this.updatingSide=void 0,this.isRemoved=!1,this.subscriptions=[],this.id=t.id||`region-${Math.random().toString(32).slice(2)}`,this.start=this.clampPosition(t.start),this.end=this.clampPosition((n=t.end)!==null&&n!==void 0?n:t.start),this.drag=(r=t.drag)===null||r===void 0||r,this.resize=(s=t.resize)===null||s===void 0||s,this.resizeStart=(l=t.resizeStart)===
null||l===void 0||l,this.resizeEnd=(a=t.resizeEnd)===null||a===void 0||a,this.color=(o=t.color)!==null&&o!==void 0?o:"rgba(0, 0, 0, 0.1)",this.minLength=(d=t.minLength)!==null&&d!==void 0?d:this.minLength,this.maxLength=(p=t.maxLength)!==null&&p!==void 0?p:this.maxLength,this.channelIdx=(u=t.channelIdx)!==null&&u!==void 0?u:-1,this.contentEditable=(m=t.contentEditable)!==null&&m!==void 0?m:this.contentEditable,this.element=this.initElement(),this.setContent(t.content),this.setPart(),this.renderPosition(),
this.initMouseEvents()}clampPosition(t){return Math.max(0,Math.min(this.totalDuration,t))}setPart(){var t;let e=this.start===this.end;(t=this.element)===null||t===void 0||t.setAttribute("part",`${e?"marker":"region"} ${this.id}`)}addResizeHandles(t){let e={position:"absolute",zIndex:"2",width:"6px",height:"100%",top:"0",cursor:"ew-resize",wordBreak:"keep-all"},i=j("div",{part:"region-handle region-handle-left",style:Object.assign(Object.assign({},e),{left:"0",borderLeft:"2px solid rgba(0, 0, 0, \
0.5)",borderRadius:"2px 0 0 2px"})},t),n=j("div",{part:"region-handle region-handle-right",style:Object.assign(Object.assign({},e),{right:"0",borderRight:"2px solid rgba(0, 0, 0, 0.5)",borderRadius:"0 2px 2px 0"})},t),r=F(i,{threshold:1}),s=F(n,{threshold:1}),l=X((()=>{let o=r.signal.value;o&&(o.type==="move"&&o.deltaX!==void 0?this.onResize(o.deltaX,"start"):o.type==="end"&&this.onEndResizing("start"))}),[r.signal]),a=X((()=>{let o=s.signal.value;o&&(o.type==="move"&&o.deltaX!==void 0?this.onResize(
o.deltaX,"end"):o.type==="end"&&this.onEndResizing("end"))}),[s.signal]);this.subscriptions.push((()=>{l(),a(),r.cleanup(),s.cleanup()}))}removeResizeHandles(t){let e=t.querySelector('[part*="region-handle-left"]'),i=t.querySelector('[part*="region-handle-right"]');e&&t.removeChild(e),i&&t.removeChild(i)}initElement(){if(this.isRemoved)return null;let t=this.start===this.end,e=0,i=100;this.channelIdx>=0&&this.numberOfChannels>0&&this.channelIdx<this.numberOfChannels&&(i=100/this.numberOfChannels,
e=i*this.channelIdx);let n=j("div",{style:{position:"absolute",top:`${e}%`,height:`${i}%`,backgroundColor:t?"none":this.color,borderLeft:t?"2px solid "+this.color:"none",borderRadius:"2px",boxSizing:"border-box",transition:"background-color 0.2s ease",cursor:this.drag?"grab":"default",pointerEvents:"all"}});return!t&&this.resize&&this.addResizeHandles(n),n}renderPosition(){if(!this.element)return;let t=this.start/this.totalDuration,e=(this.totalDuration-this.end)/this.totalDuration;this.element.
style.left=100*t+"%",this.element.style.right=100*e+"%"}toggleCursor(t){var e;this.drag&&(!((e=this.element)===null||e===void 0)&&e.style)&&(this.element.style.cursor=t?"grabbing":"grab")}initMouseEvents(){let{element:t}=this;if(!t)return;let e=N(t,"click"),i=N(t,"mouseenter"),n=N(t,"mouseleave"),r=N(t,"dblclick"),s=N(t,"pointerdown"),l=N(t,"pointerup"),a=e.subscribe((g=>g&&this.emit("click",g))),o=i.subscribe((g=>g&&this.emit("over",g))),d=n.subscribe((g=>g&&this.emit("leave",g))),p=r.subscribe(
(g=>g&&this.emit("dblclick",g))),u=s.subscribe((g=>g&&this.toggleCursor(!0))),m=l.subscribe((g=>g&&this.toggleCursor(!1)));this.subscriptions.push((()=>{a(),o(),d(),p(),u(),m(),B(e),B(i),B(n),B(r),B(s),B(l)}));let c=F(t),v=X((()=>{let g=c.signal.value;g&&(g.type==="start"?this.toggleCursor(!0):g.type==="move"&&g.deltaX!==void 0?this.onMove(g.deltaX):g.type==="end"&&(this.toggleCursor(!1),this.drag&&this.emit("update-end")))}),[c.signal]);this.subscriptions.push((()=>{v(),c.cleanup()})),this.contentEditable&&
this.content&&(this.contentClickListener=g=>this.onContentClick(g),this.contentBlurListener=()=>this.onContentBlur(),this.content.addEventListener("click",this.contentClickListener),this.content.addEventListener("blur",this.contentBlurListener))}_onUpdate(t,e,i){var n;if(!(!((n=this.element)===null||n===void 0)&&n.parentElement))return;let{width:r}=this.element.parentElement.getBoundingClientRect(),s=t/r*this.totalDuration,l=e&&e!=="start"?this.start:this.start+s,a=e&&e!=="end"?this.end:this.end+
s,o=i!==void 0;o&&this.updatingSide&&this.updatingSide!==e&&(this.updatingSide==="start"?l=i:a=i),l=Math.max(0,l),a=Math.min(this.totalDuration,a);let d=a-l;this.updatingSide=e;let p=d>=this.minLength&&d<=this.maxLength;l<=a&&(p||o)&&(this.start=l,this.end=a,this.renderPosition(),this.emit("update",e))}onMove(t){this.drag&&this._onUpdate(t)}onResize(t,e){this.resize&&(this.resizeStart||e!=="start")&&(this.resizeEnd||e!=="end")&&this._onUpdate(t,e)}onEndResizing(t){this.resize&&(this.emit("update\
-end",t),this.updatingSide=void 0)}onContentClick(t){t.stopPropagation(),t.target.focus(),this.emit("click",t)}onContentBlur(){this.emit("update-end")}_setTotalDuration(t){this.totalDuration=t,this.renderPosition()}play(t){this.emit("play",t&&this.end!==this.start?this.end:void 0)}getContent(t=!1){var e;return t?this.content||void 0:this.element instanceof HTMLElement?((e=this.content)===null||e===void 0?void 0:e.innerHTML)||void 0:""}setContent(t){var e;if(this.element)if(this.content&&this.contentEditable&&
(this.contentClickListener&&this.content.removeEventListener("click",this.contentClickListener),this.contentBlurListener&&this.content.removeEventListener("blur",this.contentBlurListener)),(e=this.content)===null||e===void 0||e.remove(),t){if(typeof t=="string"){let i=this.start===this.end;this.content=j("div",{style:{padding:`0.2em ${i?.2:.4}em`,display:"inline-block"},textContent:t})}else this.content=t;this.contentEditable&&(this.content.contentEditable="true",this.contentClickListener=i=>this.
onContentClick(i),this.contentBlurListener=()=>this.onContentBlur(),this.content.addEventListener("click",this.contentClickListener),this.content.addEventListener("blur",this.contentBlurListener)),this.content.setAttribute("part","region-content"),this.element.appendChild(this.content),this.emit("content-changed")}else this.content=void 0}setOptions(t){var e,i;if(this.element){if(t.color&&(this.color=t.color,this.element.style.backgroundColor=this.color),t.drag!==void 0&&(this.drag=t.drag,this.element.
style.cursor=this.drag?"grab":"default"),t.start!==void 0||t.end!==void 0){let n=this.start===this.end;this.start=this.clampPosition((e=t.start)!==null&&e!==void 0?e:this.start),this.end=this.clampPosition((i=t.end)!==null&&i!==void 0?i:n?this.start:this.end),this.renderPosition(),this.setPart(),this.emit("render")}if(t.content&&this.setContent(t.content),t.id&&(this.id=t.id,this.setPart()),t.resize!==void 0&&t.resize!==this.resize){let n=this.start===this.end;this.resize=t.resize,this.resize&&!n?
this.addResizeHandles(this.element):this.removeResizeHandles(this.element)}t.resizeStart!==void 0&&(this.resizeStart=t.resizeStart),t.resizeEnd!==void 0&&(this.resizeEnd=t.resizeEnd)}}remove(){this.isRemoved=!0,this.emit("remove"),this.subscriptions.forEach((t=>t())),this.subscriptions=[],this.content&&this.contentEditable&&(this.contentClickListener&&(this.content.removeEventListener("click",this.contentClickListener),this.contentClickListener=void 0),this.contentBlurListener&&(this.content.removeEventListener(
"blur",this.contentBlurListener),this.contentBlurListener=void 0)),this.element&&(this.element.remove(),this.element=null),this.unAll()}},J=class h extends Z{constructor(t){super(t),this.regions=[],this.regionsContainer=this.initRegionsContainer()}static create(t){return new h(t)}onInit(){if(!this.wavesurfer)throw Error("WaveSurfer is not initialized");this.wavesurfer.getWrapper().appendChild(this.regionsContainer),this.subscriptions.push(this.wavesurfer.on("ready",(e=>{this.regions.forEach((i=>i.
_setTotalDuration(e)))})));let t=[];this.subscriptions.push(this.wavesurfer.on("timeupdate",(e=>{let i=this.regions.filter((n=>n.start<=e&&(n.end===n.start?n.start+.05:n.end)>=e));i.forEach((n=>{t.includes(n)||this.emit("region-in",n)})),t.forEach((n=>{i.includes(n)||this.emit("region-out",n)})),t=i})))}initRegionsContainer(){return j("div",{part:"regions-container",style:{position:"absolute",top:"0",left:"0",width:"100%",height:"100%",zIndex:"5",pointerEvents:"none"}})}getRegions(){return this.
regions}avoidOverlapping(t){t.content&&!t.isRemoved&&setTimeout((()=>{if(!t.content)return;let e=t.content;e.style.marginTop="0";let i=e.getBoundingClientRect(),n=this.regions.indexOf(t);if(n<0)return;let r=this.regions.slice(0,n).filter((s=>!s.isRemoved)).reduce(((s,l)=>{if(l===t||!l.content)return s;let a=l.content.getBoundingClientRect();return i.left<a.right&&a.left<i.right&&s.push(a),s}),[]).sort(((s,l)=>s.top-l.top)).reduce(((s,l)=>{let a=i.top+s,o=a+i.height;return a<l.bottom&&l.top<o?l.bottom-
i.top+2:s}),0);e.style.marginTop=`${r}px`}),10)}avoidOverlappingAll(){this.regions.forEach((t=>this.avoidOverlapping(t)))}adjustScroll(t){var e,i;if(!t.element)return;let n=(i=(e=this.wavesurfer)===null||e===void 0?void 0:e.getWrapper())===null||i===void 0?void 0:i.parentElement;if(!n)return;let{clientWidth:r,scrollWidth:s}=n;if(s<=r)return;let l=n.getBoundingClientRect(),a=t.element.getBoundingClientRect(),o=a.left-l.left,d=a.right-l.left;o<0?n.scrollLeft+=o:d>r&&(n.scrollLeft+=d-r)}virtualAppend(t,e,i){
let n=()=>{if(!this.wavesurfer)return;let r=this.wavesurfer.getWidth(),s=this.wavesurfer.getScroll(),l=e.clientWidth,a=this.wavesurfer.getDuration(),o=Math.round(t.start/a*l),d=o+(Math.round((t.end-t.start)/a*l)||1)>s&&o<s+r;d&&!i.parentElement?e.appendChild(i):!d&&i.parentElement&&i.remove()};setTimeout((()=>{if(!this.wavesurfer||!t.element)return;n();let r=this.wavesurfer.on("scroll",n),s=this.wavesurfer.on("zoom",n),l=this.wavesurfer.on("resize",n),a=t.on("render",n),o=[r,s,l,a];this.subscriptions.
push(...o),t.once("remove",(()=>{r(),s(),l(),a(),this.subscriptions=this.subscriptions.filter((d=>!o.includes(d)))}))}),0)}saveRegion(t){if(!t.element)return;this.virtualAppend(t,this.regionsContainer,t.element),this.avoidOverlapping(t),this.regions.push(t);let e=[t.on("update",(i=>{i||this.adjustScroll(t),this.emit("region-update",t,i)})),t.on("update-end",(i=>{this.avoidOverlappingAll(),this.emit("region-updated",t,i)})),t.on("play",(i=>{var n;(n=this.wavesurfer)===null||n===void 0||n.play(t.start,
i)})),t.on("click",(i=>{this.emit("region-clicked",t,i)})),t.on("dblclick",(i=>{this.emit("region-double-clicked",t,i)})),t.on("content-changed",(()=>{this.emit("region-content-changed",t)})),t.once("remove",(()=>{e.forEach((i=>i())),this.subscriptions=this.subscriptions.filter((i=>!e.includes(i))),this.regions=this.regions.filter((i=>i!==t)),this.emit("region-removed",t)}))];this.subscriptions.push(...e),this.emit("region-created",t)}addRegion(t){var e,i;if(!this.wavesurfer)throw Error("WaveSur\
fer is not initialized");let n=this.wavesurfer.getDuration(),r=(i=(e=this.wavesurfer)===null||e===void 0?void 0:e.getDecodedData())===null||i===void 0?void 0:i.numberOfChannels,s=new V(t,n,r);if(this.emit("region-initialized",s),n)this.saveRegion(s);else{let l=this.wavesurfer.once("ready",(a=>{s._setTotalDuration(a),this.saveRegion(s),this.subscriptions=this.subscriptions.filter((o=>o!==l))}));this.subscriptions.push(l)}return s}enableDragSelection(t,e=3){var i;let n=(i=this.wavesurfer)===null||
i===void 0?void 0:i.getWrapper();if(!(n&&n instanceof HTMLElement))return()=>{};let r=null,s=0,l=0,a=F(n,{threshold:e}),o=X((()=>{var d,p;let u=a.signal.value;if(u)if(u.type==="start"){if(s=u.x,!this.wavesurfer)return;let m=this.wavesurfer.getDuration(),c=(p=(d=this.wavesurfer)===null||d===void 0?void 0:d.getDecodedData())===null||p===void 0?void 0:p.numberOfChannels,{width:v}=this.wavesurfer.getWrapper().getBoundingClientRect();l=s/v*m;let g=u.x/v*m,C=(u.x+5)/v*m;r=new V(Object.assign(Object.assign(
{},t),{start:g,end:C}),m,c),this.emit("region-initialized",r),r.element&&this.regionsContainer.appendChild(r.element)}else u.type==="move"&&u.deltaX!==void 0?r&&r._onUpdate(u.deltaX,u.x>s?"end":"start",l):u.type==="end"&&r&&(this.saveRegion(r),r.updatingSide=void 0,r=null)}),[a.signal]);return()=>{o(),a.cleanup()}}clearRegions(){this.regions.slice().forEach((t=>t.remove())),this.regions=[]}destroy(){this.clearRegions(),super.destroy(),this.regionsContainer.remove()}};export{J as RegionsPlugin,H as WaveSurfer,H as default};
