// This file is auto-generated by 'pnpm rebuild:icons'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from './types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='20'
    height='16'
    data-name='icon_List (stroke)'
    viewBox='0 0 20 16'
    ...attributes
  ><g data-name='V 02'><g
        data-name='Rectangle 1992'
        style='stroke:var(--icon-color, #000);stroke-width:1.4px;fill:none'
      ><rect
          width='20'
          height='4'
          stroke='none'
          rx='2'
          style='stroke:none'
        /><rect
          width='18.6'
          height='2.6'
          x='.7'
          y='.7'
          rx='1.3'
          style='fill:none'
        /></g><g
        data-name='Rectangle 1993'
        style='stroke:var(--icon-color, #000);stroke-width:1.4px;fill:none'
        transform='translate(0 6)'
      ><rect
          width='20'
          height='4'
          stroke='none'
          rx='2'
          style='stroke:none'
        /><rect
          width='18.6'
          height='2.6'
          x='.7'
          y='.7'
          rx='1.3'
          style='fill:none'
        /></g><g
        data-name='Rectangle 1994'
        style='stroke:var(--icon-color, #000);stroke-width:1.4px;fill:none'
        transform='translate(0 12)'
      ><rect
          width='20'
          height='4'
          stroke='none'
          rx='2'
          style='stroke:none'
        /><rect
          width='18.6'
          height='2.6'
          x='.7'
          y='.7'
          rx='1.3'
          style='fill:none'
        /></g></g></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'IconList';
export default IconComponent;
