export const THEME_TEMPLATE = `
{
  "data": {
    "type": "card",
    "attributes": {
      "cssVariables": ":root {\\n  --background: <css color>;\\n  --foreground: <css color>;\\n  --primary: <css color>;\\n  --primary-foreground: <css color>;\\n}\\n\\n.dark {\\n  --background: <css color>;\\n  --foreground: <css color>;\\n}\\n\\n@theme inline {\\n  --background: var(--background);\\n  --foreground: var(--foreground);\\n  --primary: var(--primary);\\n  --primary-foreground: var(--primary-foreground);\\n}",
      "cssImports": ["<https font url>", "<optional second font url>"]
    }
  }
}
`;

export const STRUCTURED_THEME_TEMPLATE = `
{
  "data": {
    "type": "card",
    "attributes": {
      "cardInfo": {
        "title": "<title describing the theme>",
        "description": "<1-2 sentence summary>",
        "thumbnailURL": "<https url>"
      },
      "rootVariables": {
        "background": "<css color>",
        "foreground": "<css color>",
        "card": "<css color>",
        "cardForeground": "<css color>",
        "popover": "<css color>",
        "popoverForeground": "<css color>",
        "primary": "<css color>",
        "primaryForeground": "<css color>",
        "secondary": "<css color>",
        "secondaryForeground": "<css color>",
        "muted": "<css color>",
        "mutedForeground": "<css color>",
        "accent": "<css color>",
        "accentForeground": "<css color>",
        "destructive": "<css color>",
        "destructiveForeground": "<css color>",
        "border": "<css color>",
        "input": "<css color>",
        "ring": "<css color>",
        "chart1": "<css color>",
        "chart2": "<css color>",
        "chart3": "<css color>",
        "chart4": "<css color>",
        "chart5": "<css color>",
        "sidebar": "<css color>",
        "sidebarForeground": "<css color>",
        "sidebarPrimary": "<css color>",
        "sidebarPrimaryForeground": "<css color>",
        "sidebarAccent": "<css color>",
        "sidebarAccentForeground": "<css color>",
        "sidebarBorder": "<css color>",
        "sidebarRing": "<css color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "darkModeVariables": {
        "background": "<css color>",
        "foreground": "<css color>",
        "card": "<css color>",
        "cardForeground": "<css color>",
        "popover": "<css color>",
        "popoverForeground": "<css color>",
        "primary": "<css color>",
        "primaryForeground": "<css color>",
        "secondary": "<css color>",
        "secondaryForeground": "<css color>",
        "muted": "<css color>",
        "mutedForeground": "<css color>",
        "accent": "<css color>",
        "accentForeground": "<css color>",
        "destructive": "<css color>",
        "destructiveForeground": "<css color>",
        "border": "<css color>",
        "input": "<css color>",
        "ring": "<css color>",
        "chart1": "<css color>",
        "chart2": "<css color>",
        "chart3": "<css color>",
        "chart4": "<css color>",
        "chart5": "<css color>",
        "sidebar": "<css color>",
        "sidebarForeground": "<css color>",
        "sidebarPrimary": "<css color>",
        "sidebarPrimaryForeground": "<css color>",
        "sidebarAccent": "<css color>",
        "sidebarAccentForeground": "<css color>",
        "sidebarBorder": "<css color>",
        "sidebarRing": "<css color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "cssImports": ["<https font url>", "<optional second font url>"]
    }
  }
}
`;

export const STYLE_REFERENCE_TEMPLATE = `
{
  "data": {
    "type": "card",
    "attributes": {
      "styleName": "<style reference name>",
      "visualDNA": "<sentence describing the vibe>",
      "cardInfo": {
        "title": "<title>",
        "description": "<summary>",
        "thumbnailURL": "<https url>"
      },
      "inspirations": ["<keyword>", "<keyword>", "<keyword>"],
      "wallpaperImages": ["<https url>", "<https url>"],
      "cssImports": ["<https font url>", "<optional font url>"],
      "rootVariables": {
        "background": "<css color>",
        "foreground": "<css color>",
        "card": "<css color>",
        "cardForeground": "<css color>",
        "popover": "<css color>",
        "popoverForeground": "<css color>",
        "primary": "<css color>",
        "primaryForeground": "<css color>",
        "secondary": "<css color>",
        "secondaryForeground": "<css color>",
        "muted": "<css color>",
        "mutedForeground": "<css color>",
        "accent": "<css color>",
        "accentForeground": "<css color>",
        "destructive": "<css color>",
        "destructiveForeground": "<css color>",
        "border": "<css color>",
        "input": "<css color>",
        "ring": "<css color>",
        "chart1": "<css color>",
        "chart2": "<css color>",
        "chart3": "<css color>",
        "chart4": "<css color>",
        "chart5": "<css color>",
        "sidebar": "<css color>",
        "sidebarForeground": "<css color>",
        "sidebarPrimary": "<css color>",
        "sidebarPrimaryForeground": "<css color>",
        "sidebarAccent": "<css color>",
        "sidebarAccentForeground": "<css color>",
        "sidebarBorder": "<css color>",
        "sidebarRing": "<css color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "darkModeVariables": {
        "background": "<css color>",
        "foreground": "<css color>",
        "card": "<css color>",
        "cardForeground": "<css color>",
        "popover": "<css color>",
        "popoverForeground": "<css color>",
        "primary": "<css color>",
        "primaryForeground": "<css color>",
        "secondary": "<css color>",
        "secondaryForeground": "<css color>",
        "muted": "<css color>",
        "mutedForeground": "<css color>",
        "accent": "<css color>",
        "accentForeground": "<css color>",
        "destructive": "<css color>",
        "destructiveForeground": "<css color>",
        "border": "<css color>",
        "input": "<css color>",
        "ring": "<css color>",
        "chart1": "<css color>",
        "chart2": "<css color>",
        "chart3": "<css color>",
        "chart4": "<css color>",
        "chart5": "<css color>",
        "sidebar": "<css color>",
        "sidebarForeground": "<css color>",
        "sidebarPrimary": "<css color>",
        "sidebarPrimaryForeground": "<css color>",
        "sidebarAccent": "<css color>",
        "sidebarAccentForeground": "<css color>",
        "sidebarBorder": "<css color>",
        "sidebarRing": "<css color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "cssVariables": "<structured theme CSS string>"
    }
  }
}
`;

export const BRAND_GUIDE_TEMPLATE = `
{
  "data": {
    "type": "card",
    "attributes": {
      "styleName": "<brand guide name>",
      "visualDNA": "<sentence describing brand essence>",
      "cardInfo": {
        "title": "<title>",
        "description": "<summary>",
        "thumbnailURL": "<https url>"
      },
      "inspirations": ["<keyword>", "<keyword>", "<keyword>"],
      "wallpaperImages": ["<https url>", "<https url>"],
      "markUsage": {
        "primaryMark1": "<https url>",
        "primaryMarkMinHeight": "<px>",
        "primaryMarkClearanceRatio": "<ratio>",
        "socialMediaProfileIcon": "<https url>"
      },
      "typography": {
        "heading": {
          "fontFamily": "<font stack>",
          "fontWeight": "<numeric weight>",
          "fontSize": "<px>",
          "lineHeight": "<unitless>"
        },
        "body": {
          "fontFamily": "<font stack>",
          "fontWeight": "<numeric weight>",
          "fontSize": "<px>",
          "lineHeight": "<unitless>"
        }
      },
      "rootVariables": {
        "background": "<css color>",
        "foreground": "<css color>",
        "card": "<css color>",
        "cardForeground": "<css color>",
        "popover": "<css color>",
        "popoverForeground": "<css color>",
        "primary": "<css color>",
        "primaryForeground": "<css color>",
        "secondary": "<css color>",
        "secondaryForeground": "<css color>",
        "muted": "<css color>",
        "mutedForeground": "<css color>",
        "accent": "<css color>",
        "accentForeground": "<css color>",
        "destructive": "<css color>",
        "destructiveForeground": "<css color>",
        "border": "<css color>",
        "input": "<css color>",
        "ring": "<css color>",
        "chart1": "<css color>",
        "chart2": "<css color>",
        "chart3": "<css color>",
        "chart4": "<css color>",
        "chart5": "<css color>",
        "sidebar": "<css color>",
        "sidebarForeground": "<css color>",
        "sidebarPrimary": "<css color>",
        "sidebarPrimaryForeground": "<css color>",
        "sidebarAccent": "<css color>",
        "sidebarAccentForeground": "<css color>",
        "sidebarBorder": "<css color>",
        "sidebarRing": "<css color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "darkModeVariables": {
        "background": "<css color>",
        "foreground": "<css color>",
        "card": "<css color>",
        "cardForeground": "<css color>",
        "popover": "<css color>",
        "popoverForeground": "<css color>",
        "primary": "<css color>",
        "primaryForeground": "<css color>",
        "secondary": "<css color>",
        "secondaryForeground": "<css color>",
        "muted": "<css color>",
        "mutedForeground": "<css color>",
        "accent": "<css color>",
        "accentForeground": "<css color>",
        "destructive": "<css color>",
        "destructiveForeground": "<css color>",
        "border": "<css color>",
        "input": "<css color>",
        "ring": "<css color>",
        "chart1": "<css color>",
        "chart2": "<css color>",
        "chart3": "<css color>",
        "chart4": "<css color>",
        "chart5": "<css color>",
        "sidebar": "<css color>",
        "sidebarForeground": "<css color>",
        "sidebarPrimary": "<css color>",
        "sidebarPrimaryForeground": "<css color>",
        "sidebarAccent": "<css color>",
        "sidebarAccentForeground": "<css color>",
        "sidebarBorder": "<css color>",
        "sidebarRing": "<css color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "brandColorPalette": [
        { "name": "<swatch name 1>", "value": "<css color>" },
        { "name": "<swatch name 2>", "value": "<css color>" },
        { "name": "<swatch name 3>", "value": "<css color>" }
      ],
      "functionalPalette": {
        "primary": "<css color>",
        "secondary": "<css color>",
        "accent": "<css color>",
        "neutral": "<css color>",
        "light": "<css color>",
        "dark": "<css color>",
        "border": "<css color>"
      },
      "cornerRadius": "<px or rem>",
      "spacing": "<px or rem>",
      "cssImports": ["<https font url>"],
      "cssVariables": "<structured theme CSS string>"
    }
  }
}
`;
