/** Editorial interest scores: visual payoff, distinctiveness, and explanatory value; not API quality. */
export const tourStops = [
  {
    id: 'gestures',
    score: 6,
    seconds: 6,
    chapter: '01 / Feedback',
    title: 'Feel the response',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Start with touch. The glow and spring answer your press. Motion powers the response; Choreo coordinates what follows.',
  },
  {
    id: 'enter',
    score: 3,
    seconds: 4,
    chapter: '01 / Feedback',
    title: 'An entrance with intent',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'An entrance gives new content a direction, instead of simply switching it on.',
  },
  {
    id: 'presence',
    score: 5,
    seconds: 4,
    chapter: '01 / Feedback',
    title: 'Exits stay alive',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Watch the departing content finish its exit, even after the application removes it.',
  },
  {
    id: 'keyframes',
    score: 3,
    seconds: 4,
    chapter: '01 / Feedback',
    title: 'Shape the middle',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Keyframes shape the journey between endpoints, adding anticipation and overshoot.',
  },
  {
    id: 'circle-loop',
    score: 8,
    seconds: 10,
    chapter: '01 / Feedback',
    title: 'One cast, many arrangements',
    cue: 'Follow the circles from cluster to field to grid. The whole scene zooms while each circle moves locally.',
    text: 'The same circles become a cluster, a field, then a grid. One shared zoom connects them. Precise keyframe timing gives the loop its rhythm, without rebuilding the scene.',
  },
  {
    id: 'path',
    score: 4,
    seconds: 4,
    chapter: '01 / Feedback',
    title: 'Draw attention',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'A path draws itself into view. The reveal makes your eye follow the line.',
  },
  {
    id: 'pointer',
    score: 5,
    seconds: 4,
    chapter: '01 / Feedback',
    title: 'Give the pointer weight',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'The pointer followers arrive at different speeds. That tiny delay gives a flat interface weight.',
  },
  {
    id: 'stagger',
    score: 4,
    seconds: 4,
    chapter: '01 / Feedback',
    title: 'One change, a rhythm',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'A stagger turns simultaneous arrivals into a readable rhythm.',
  },
  {
    id: 'trail',
    score: 7,
    seconds: 6,
    chapter: '01 / Feedback',
    title: 'Keep your bearings',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'The breadcrumb grows and collapses while preserving your place. Navigation becomes a continuous object.',
  },
  {
    id: 'tabs',
    score: 5,
    seconds: 4,
    chapter: '02 / Continuity',
    title: 'One moving selection',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'The highlight travels between tabs. Your eye follows the same element, rather than finding a replacement.',
  },
  {
    id: 'layout',
    score: 5,
    seconds: 4,
    chapter: '02 / Continuity',
    title: 'Resize without a jump',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Change the layout. The content moves into its new bounds without a visual jump.',
  },
  {
    id: 'lists',
    score: 6,
    seconds: 6,
    chapter: '02 / Continuity',
    title: 'Follow the person',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Move someone between lists. Their identity survives the journey, so the change stays easy to follow.',
  },
  {
    id: 'reorder',
    score: 6,
    seconds: 6,
    chapter: '02 / Continuity',
    title: 'Make room',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Reorder the tracks. Their neighbors make room, showing where the moved item belongs.',
  },
  {
    id: 'grid',
    score: 7,
    seconds: 6,
    chapter: '02 / Continuity',
    title: 'Reorder in two dimensions',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'The same continuity works across a grid. The other covers reorganize around the moving item.',
  },
  {
    id: 'inline-edit',
    score: 8,
    seconds: 8,
    chapter: '02 / Continuity',
    title: 'Edit in place',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'This editor unfolds inside the existing layout. Context stays visible while the controls make room.',
  },
  {
    id: 'lightbox',
    score: 8,
    seconds: 8,
    chapter: '02 / Continuity',
    title: 'The thumbnail becomes the view',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'The thumbnail expands into the detail view. Closing it retraces that relationship, preserving your bearings.',
  },
  {
    id: 'split',
    score: 6,
    seconds: 6,
    chapter: '02 / Continuity',
    title: 'Move a whole relationship',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'The split changes together: panel, content, and divider. Coordination makes the resize feel like one decision.',
  },
  {
    id: 'inbox',
    score: 9,
    seconds: 8,
    chapter: '03 / Choreography',
    title: 'Give motion a destination',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Now Choreo directs the workflow. A new message comes from Compose; deletion flies toward Trash. Beacons name those destinations.',
  },
  {
    id: 'far',
    score: 9,
    seconds: 8,
    chapter: '03 / Choreography',
    title: 'Cross the boundary',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'These regions update separately, yet the same item travels between them. Choreo coordinates the crossing.',
  },
  {
    id: 'crossing',
    score: 7,
    seconds: 6,
    chapter: '03 / Choreography',
    title: 'Control the crossing',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Watch the overlap. A convincing crossing depends on which element owns the foreground, and when.',
  },
  {
    id: 'escort',
    score: 8,
    seconds: 8,
    chapter: '03 / Choreography',
    title: 'Travel together',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'The card travels with its companions. Their coordinated movement makes several pieces read as one object.',
  },
  {
    id: 'interrupt',
    score: 8,
    seconds: 8,
    chapter: '03 / Choreography',
    title: 'Interrupt without a jolt',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Change the destination mid-flight. The spring preserves momentum, while the tween follows its timing curve.',
  },
  {
    id: 'sequence',
    score: 8,
    seconds: 8,
    chapter: '03 / Choreography',
    title: 'Close, move, reveal',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Details close, cards rearrange, then new details appear. The order keeps each change legible.',
  },
  {
    id: 'wires',
    score: 9,
    seconds: 8,
    chapter: '03 / Choreography',
    title: 'Keep the annotation attached',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Change the draft. Comments follow their text as it moves. The relationship matters more than either element alone.',
  },
  {
    id: 'jump',
    score: 7,
    seconds: 6,
    chapter: '03 / Choreography',
    title: 'Jump with context',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Jump to the next failure. The viewport brings the relevant content into view, keeping the task moving.',
  },
  {
    id: 'parallax',
    score: 5,
    seconds: 4,
    chapter: '04 / Scroll and time',
    title: 'Depth from one scroll',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'One scroll value moves several layers at different speeds. That difference creates depth.',
  },
  {
    id: 'reveal',
    score: 5,
    seconds: 4,
    chapter: '04 / Scroll and time',
    title: 'Reveal at the right moment',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Content reveals as it enters view. Motion marks the moment it becomes relevant.',
  },
  {
    id: 'drift',
    score: 7,
    seconds: 6,
    chapter: '04 / Scroll and time',
    title: 'Drive, then choreograph the result',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'The car uses its own driving physics. Choreo handles the lap board: arrivals, rearrangement, and departures, all while driving continues.',
  },
  {
    id: 'hang',
    score: 7,
    seconds: 6,
    chapter: '04 / Scroll and time',
    title: 'Turn a flick into a flight',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'A flick becomes a measured flight. Choreo carries the puck, follows the leader, and coordinates the collisions.',
  },
  {
    id: 'header',
    score: 4,
    seconds: 4,
    chapter: '04 / Scroll and time',
    title: 'Follow the scroll direction',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Scroll down and the header yields space. Reverse direction and the controls return.',
  },
  {
    id: 'fold',
    score: 9,
    seconds: 8,
    chapter: '04 / Scroll and time',
    title: 'Scrub a whole system',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Scrub the kiln. Temperature, flame, and the command ledger describe the same moment. Time becomes an inspectable state.',
  },
  {
    id: 'sheet',
    score: 6,
    seconds: 6,
    chapter: '04 / Scroll and time',
    title: 'A sheet with positions',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'The sheet moves between useful positions. Each stop gives the content a different amount of space.',
  },
  {
    id: 'mockup',
    score: 9,
    seconds: 8,
    chapter: '05 / Spatial interfaces',
    title: 'Live content gains depth',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Now enter space. Open the app: real interface content moves within the device scene, keeping its controls alive.',
  },
  {
    id: 'camera',
    score: 9,
    seconds: 8,
    chapter: '05 / Spatial interfaces',
    title: 'Direct the viewpoint',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Choose a frame. The camera brings it forward, then the interface remains usable. Depth serves attention.',
  },
  {
    id: 'long-take',
    score: 9,
    seconds: 8,
    chapter: '05 / Spatial interfaces',
    title: 'Keep the scene continuous',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'The device and viewpoint move through one continuous scene. A camera move connects states that a cut would separate.',
  },
  {
    id: 'sylva',
    score: 10,
    seconds: 10,
    chapter: '05 / Spatial interfaces',
    title: 'A living spatial interface',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Sylva combines a rendered world with interface planes. Choreo coordinates the viewpoint and reveals; the renderer supplies the landscape.',
  },
  {
    id: 'subdivision',
    score: 8,
    seconds: 8,
    chapter: '05 / Spatial interfaces',
    title: 'Space reorganizes around focus',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Select a tile. The divisions reorganize around it, turning the layout itself into a way to focus.',
  },
  {
    id: 'rack',
    score: 9,
    seconds: 8,
    chapter: '05 / Spatial interfaces',
    title: 'Scrub between arrangements',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Scrub the arrangement. The same content changes its staging continuously, so intermediate positions are meaningful too.',
  },
  {
    id: 'grip',
    score: 8,
    seconds: 8,
    chapter: '05 / Spatial interfaces',
    title: 'Keep the object intact',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Open a guest’s details. The card carries its identity and controls as the surrounding layout makes space.',
  },
  {
    id: 'drag',
    score: 5,
    seconds: 4,
    chapter: '05 / Spatial interfaces',
    title: 'Constrain the gesture',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Constraints give a drag somewhere useful to go. The boundary becomes part of the interaction.',
  },
  {
    id: 'slides',
    score: 7,
    seconds: 6,
    chapter: '06 / Film and story',
    title: 'Build a sequence',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Advance the slide. Entrances and exits establish an order: what leaves, what arrives, and where to look.',
  },
  {
    id: 'presentation',
    score: 9,
    seconds: 8,
    chapter: '06 / Film and story',
    title: 'From interaction to direction',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Advance the builds. A presentation uses the same staging ideas, but now the author chooses the sequence.',
  },
  {
    id: 'towers',
    score: 10,
    seconds: 10,
    chapter: '06 / Film and story',
    title: 'Motion makes an argument',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Towers turns camera, architecture, and typography into a film. Choreo coordinates time; it does not model or render the building.',
  },
  {
    id: 'sagrada',
    score: 10,
    seconds: 10,
    chapter: '06 / Film and story',
    title: 'Explain through the camera',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Sagrada uses the camera to reveal architectural detail. The film’s movement helps explain the subject, rather than merely decorate it.',
  },
  {
    id: 'playhead',
    score: 10,
    seconds: 10,
    chapter: '06 / Film and story',
    title: 'Inspect authored time',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Now scrub backward. The scene returns to an authored moment. The playhead makes the choreography something you can inspect.',
  },
  {
    id: 'build-order',
    score: 10,
    seconds: 10,
    chapter: '06 / Film and story',
    title: 'Interaction. Space. Story.',
    cue: 'Watch the guided interaction. Tap Pause to explore.',
    text: 'Finish with the Choreo mark. Feedback in interfaces. Continuity in space. Authored timing in film. One language for coordinating change.',
  },
];
export const auditionText =
  'Welcome to Choreo. A good animation does more than look smooth. It helps us understand what changed, where to look, and what we can do next. Follow me through the gallery: from a familiar interface, into a spatial scene, and finally into a film.';
