/**
 * Generate the stylesheet consumed by every host from the readable canonical
 * source. Boxel mounts the gallery inside a larger workbench document, so no
 * selector may style anything outside `.choreo-site`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import postcss from 'postcss';
import selectorParser from 'postcss-selector-parser';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = join(packageRoot, 'styles/app.css');
const outputPath = join(packageRoot, 'styles/app.scoped.css');
const boundary = selectorParser.className({ value: 'choreo-site' });

function isInsideKeyframes(rule) {
  for (let parent = rule.parent; parent; parent = parent.parent) {
    if (parent.type === 'atrule' && /(?:^|-)keyframes$/i.test(parent.name)) {
      return true;
    }
  }
  return false;
}

function firstSignificant(selector) {
  return selector.nodes.find((node) => node.type !== 'comment');
}

function scopeSelector(selector) {
  const first = firstSignificant(selector);
  if (!first) {
    return;
  }

  // Theme tokens and their descendants now resolve against the local mount.
  if (first.type === 'pseudo' && first.value === ':root') {
    first.replaceWith(boundary.clone());
    return;
  }

  if (first.type === 'tag' && /^(?:html|body)$/i.test(first.value)) {
    if (selector.toString().includes('[data-gm-dragging]')) {
      // glimmer-motion owns this document-level signal. Keep the signal but
      // constrain everything it affects to the gallery subtree.
      const firstCombinator = selector.nodes.find(
        (node) => node.type === 'combinator',
      );
      if (firstCombinator) {
        const localBoundary = boundary.clone();
        selector.insertAfter(firstCombinator, localBoundary);
        selector.insertAfter(
          localBoundary,
          selectorParser.combinator({ value: ' ' }),
        );
      } else {
        selector.append(selectorParser.combinator({ value: ' ' }));
        selector.append(boundary.clone());
      }
      return;
    }
    const wasBody = first.value.toLowerCase() === 'body';
    first.replaceWith(boundary.clone());
    if (wasBody && selector.nodes.length === 1) {
      selector.append(selectorParser.combinator({ value: ' ' }));
      selector.append(selectorParser.className({ value: 'app-shell' }));
    }
    return;
  }

  selector.prepend(selectorParser.combinator({ value: ' ' }));
  selector.prepend(boundary.clone());
}

export function scopeStyles(source, from) {
  const root = postcss.parse(source, { from });
  root.walkRules((rule) => {
    if (isInsideKeyframes(rule)) {
      return;
    }
    rule.selector = selectorParser((selectors) => {
      selectors.each(scopeSelector);
    }).processSync(rule.selector);
  });
  return root.toString();
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  writeFileSync(
    outputPath,
    '/* Generated by scripts/scope-css.mjs. */\n' +
      scopeStyles(readFileSync(sourcePath, 'utf8'), sourcePath),
  );
}
