{
 "title": "Boxel Logs",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job_id",
    "label": "Jobs",
    "query": "SELECT j.id || '.' || jr.id as __value, RTRIM(REGEXP_REPLACE(j.concurrency_group, 'indexing:https:\\/\\/[^\\/]+\\/', ''), '/') || ' (' || REPLACE(j.job_type, '-index', '') || ' ' || TO_CHAR(jr.created_at, 'YYYY-MM-DD HH24:MI:SS') || ')' as __text FROM job_reservations jr JOIN jobs j ON jr.job_id = j.id WHERE jr.created_at >= NOW() - INTERVAL '1 day' ORDER BY jr.created_at DESC;\n"
   },
   {
    "name": "worker_id",
    "label": "Workers",
    "query": "SELECT worker_id FROM job_reservations WHERE created_at >= NOW() - INTERVAL '1 day' ORDER BY created_at DESC;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Job Logs",
   "type": "logs",
   "description": "This panel displays the logs for the job selected in the drop down above. Make sure to set the date range wide enough to capture the selected logs.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n parse @message /\\[job: (?<jobId>.*?)\\]/ |\n filter (jobId = \"$job_id\") |\n sort @timestamp asc",
     "logGroups": [
      {
       "accountId": "680542703984",
       "arn": "arn:aws:logs:us-east-1:680542703984:log-group:ecs-boxel-worker-staging",
       "name": "ecs-boxel-worker-staging"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Worker Logs",
   "type": "logs",
   "description": "This panel displays the logs for the selected worker. Make sure to set the date range wide enough to capture the selected logs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n parse @message /^\\[worker (?<workerId>.*?) / |\n filter (workerId = \"$worker_id\") |\n sort @timestamp asc",
     "id": "4",
     "logGroups": [
      {
       "accountId": "680542703984",
       "arn": "arn:aws:logs:us-east-1:680542703984:log-group:ecs-boxel-worker-staging",
       "name": "ecs-boxel-worker-staging"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Realm Server Logs",
   "type": "logs",
   "description": "The realm server logs. Make sure to set the duration to the value that encapsulates time frame for the logs that you want. Note that these logs have been truncated to 1000 lines.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 1000",
     "logGroups": [
      {
       "accountId": "680542703984",
       "arn": "arn:aws:logs:us-east-1:680542703984:log-group:ecs-boxel-realm-server-staging",
       "name": "ecs-boxel-realm-server-staging"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}