// Single source of truth for filesystem paths used by the bench-amd
// harness. Keeping these in one module lets bench / check / prepare
// stay in lockstep when the layout changes.
import path from 'node:path';

export const repoRoot = path.resolve(__dirname, '../../../..');

// Committed, hermetic fixtures. Generated by `pnpm bench:amd:prep`. The
// bench gate reads only from this path so that edits to card sources
// or the upstream transpile pipeline don't ripple the perf numbers.
export const fixturesDir = path.join(
  repoRoot,
  'bench-fixtures/runtime-common/amd-transpile',
);

export const candidatesDir = path.join(__dirname, 'candidates');

// `BENCH_AMD_BASELINE_OVERRIDE` redirects the gate to read a synthetic
// baseline from somewhere else on disk. Used by the trip-test to prove
// the gate's failure path works without ever mutating the real
// `baseline.json`. Default unchanged.
export const baselinePath =
  process.env.BENCH_AMD_BASELINE_OVERRIDE ??
  path.join(__dirname, 'baseline.json');
