// AUTO-GENERATED by scripts/codemods/qunit-to-vitest.ts. Run codemod again instead of editing by hand.
import { describe, it, expect, beforeAll, beforeEach, afterAll, afterEach } from "vitest";
import type { PgAdapter } from '@cardstack/postgres';
import type { IndexWriter, DefinitionLookup, Prerenderer, QueuePublisher, } from '@cardstack/runtime-common';
import { asExpressions, fullReindex, insert, insertPermissions, logger, query, uuidv4, } from '@cardstack/runtime-common';
import { setupDB } from './helpers';
describe("full-reindex-test.ts", function () {
    const hooks = {
        before: beforeAll,
        after: afterAll,
        beforeEach,
        afterEach
    };
    let dbAdapter: PgAdapter;
    let queuePublisher: QueuePublisher;
    setupDB(hooks, {
        beforeEach: async (_dbAdapter: PgAdapter, _publisher: QueuePublisher): Promise<void> => {
            dbAdapter = _dbAdapter;
            queuePublisher = _publisher;
        },
    });
    function buildFullReindexTask() {
        return fullReindex({
            reportStatus: () => { },
            log: logger('full-reindex-test'),
            dbAdapter,
            queuePublisher,
            indexWriter: null as unknown as IndexWriter,
            prerenderer: null as unknown as Prerenderer,
            definitionLookup: null as unknown as DefinitionLookup,
            matrixURL: 'http://localhost:8008',
            getReader: () => {
                throw new Error('getReader is not used by full-reindex');
            },
            getAuthedFetch: async () => globalThis.fetch,
            createPrerenderAuth: () => '',
        });
    }
    async function insertPublishedRealm({ sourceRealmURL, publishedRealmURL, ownerUsername, }: {
        sourceRealmURL: string;
        publishedRealmURL: string;
        ownerUsername: string;
    }) {
        let { nameExpressions, valueExpressions } = asExpressions({
            id: uuidv4(),
            owner_username: ownerUsername,
            source_realm_url: sourceRealmURL,
            published_realm_url: publishedRealmURL,
            last_published_at: Date.now().toString(),
        });
        await query(dbAdapter, insert('published_realms', nameExpressions, valueExpressions));
    }
    it('enqueues jobs for source and published realms using the source owner', async function () {
        const ownerUserId = '@owner:localhost';
        const sourceRealmURL = 'http://example.com/source/';
        const publishedRealmURL = 'http://example.com/published/';
        await insertPermissions(dbAdapter, new URL(sourceRealmURL), {
            [ownerUserId]: ['read', 'realm-owner'],
        });
        await insertPublishedRealm({
            sourceRealmURL,
            publishedRealmURL,
            ownerUsername: '@realm/published-owner',
        });
        let reindex = buildFullReindexTask();
        await reindex({
            realmUrls: [sourceRealmURL, publishedRealmURL],
        });
        type JobArgs = {
            realmURL: string;
            realmUsername: string;
        };
        type JobRow = {
            job_type: string;
            concurrency_group: string | null;
            args: JobArgs;
        };
        let jobs = (await dbAdapter.execute('select * from jobs')) as JobRow[];
        expect(jobs.length).toBe(2);
        let jobsByRealm = new Map(jobs.map((job) => [job.args.realmURL, job]));
        let sourceJob = jobsByRealm.get(sourceRealmURL);
        expect(sourceJob).toBeTruthy();
        expect(sourceJob?.job_type).toBe('from-scratch-index');
        expect(sourceJob?.concurrency_group).toBe(`indexing:${sourceRealmURL}`);
        expect(sourceJob?.args).toEqual({
            realmURL: sourceRealmURL,
            realmUsername: 'owner',
        });
        let publishedJob = jobsByRealm.get(publishedRealmURL);
        expect(publishedJob).toBeTruthy();
        expect(publishedJob?.job_type).toBe('from-scratch-index');
        expect(publishedJob?.concurrency_group).toBe(`indexing:${publishedRealmURL}`);
        expect(publishedJob?.args).toEqual({
            realmURL: publishedRealmURL,
            realmUsername: 'owner',
        });
    });
    it('skips bot-owned realms', async function () {
        const botUserId = '@realm/bot:localhost';
        const botRealmURL = 'http://example.com/bot/';
        await insertPermissions(dbAdapter, new URL(botRealmURL), {
            [botUserId]: ['read', 'realm-owner'],
        });
        let reindex = buildFullReindexTask();
        await reindex({ realmUrls: [botRealmURL] });
        let jobs = await dbAdapter.execute('select * from jobs');
        expect(jobs.length).toBe(0);
    });
});
