// AUTO-GENERATED by scripts/codemods/qunit-to-vitest.ts. Run codemod again instead of editing by hand.
import { describe, test, expect, beforeAll, beforeEach, afterAll, afterEach } from "vitest";
import { createServer } from 'http';
import { createRemotePrerenderer } from '../prerender/remote-prerenderer';
import { PRERENDER_SERVER_DRAINING_STATUS_CODE, PRERENDER_SERVER_STATUS_DRAINING, PRERENDER_SERVER_STATUS_HEADER, } from '../prerender/prerender-constants';
describe("remote-prerenderer-test.ts", function () {
    const hooks = {
        before: beforeAll,
        after: afterAll,
        beforeEach,
        afterEach
    };
    hooks.afterEach(function () {
        delete process.env.PRERENDER_MANAGER_RETRY_ATTEMPTS;
        delete process.env.PRERENDER_MANAGER_RETRY_DELAY_MS;
        delete process.env.PRERENDER_MANAGER_REQUEST_TIMEOUT_MS;
        delete process.env.PRERENDER_MANAGER_MAX_DELAY_MS;
    });
    describe('remote prerenderer payload', function () {
        async function expectValidationFailure(assert: Assert, attrs: any, message: RegExp) {
            let originalFetch = globalThis.fetch;
            let fetchCalled = false;
            (globalThis as any).fetch = () => {
                fetchCalled = true;
                throw new Error('fetch should not be called when validation fails');
            };
            try {
                let prerenderer = createRemotePrerenderer('http://127.0.0.1:0');
                await assert.rejects(prerenderer.prerenderModule(attrs as any), message);
                expect(fetchCalled).toBe(false);
            }
            finally {
                (globalThis as any).fetch = originalFetch;
            }
        }
        test('sends JSON:API headers and attributes', async function () {
            let receivedHeaders: any;
            let receivedBody: any;
            let server = createServer((req, res) => {
                receivedHeaders = req.headers;
                let body: Buffer[] = [];
                req.on('data', (chunk) => body.push(chunk));
                req.on('end', () => {
                    receivedBody = JSON.parse(Buffer.concat(body).toString('utf-8'));
                    res.statusCode = 201;
                    res.setHeader('Content-Type', 'application/json');
                    res.end(JSON.stringify({
                        data: { attributes: { ok: true } },
                    }));
                });
            }).listen(0);
            try {
                let url = `http://127.0.0.1:${(server.address() as any).port}`;
                let prerenderer = createRemotePrerenderer(url);
                await prerenderer.prerenderModule({
                    realm: 'realm-1',
                    url: 'https://example.com/module',
                    auth: '{"token":"x"}',
                });
                expect(receivedHeaders?.['content-type']).toBe('application/vnd.api+json');
                expect(receivedHeaders?.accept).toBe('application/vnd.api+json');
                expect(receivedBody?.data?.attributes).toEqual({
                    realm: 'realm-1',
                    url: 'https://example.com/module',
                    auth: '{"token":"x"}',
                    renderOptions: {},
                });
            }
            finally {
                await new Promise<void>((resolve) => server.close(() => resolve()));
            }
        });
        test('rejects empty realm before sending', async function () {
            await expectValidationFailure(assert, { realm: '', url: 'https://example.com/module', auth: '{}' }, /Missing prerender prerender-module-request attributes: realm/);
        });
        test('rejects empty url before sending', async function () {
            await expectValidationFailure(assert, { realm: 'realm', url: '', auth: '{}' }, /Missing prerender prerender-module-request attributes: url/);
        });
        test('rejects empty auth before sending', async function () {
            await expectValidationFailure(assert, { realm: 'realm', url: 'https://example.com/module', auth: '' }, /Missing prerender prerender-module-request attributes: auth/);
        });
        test('rejects missing auth before sending', async function () {
            await expectValidationFailure(assert, { realm: 'realm', url: 'https://example.com/module' }, /Missing prerender prerender-module-request attributes: auth/);
        });
    });
    describe('remote prerenderer retries', function () {
        test('retries draining responses and succeeds', async function () {
            let attempts = 0;
            let server = createServer((req, res) => {
                attempts++;
                if (req.url?.endsWith('/prerender-card') && attempts < 3) {
                    res.statusCode = PRERENDER_SERVER_DRAINING_STATUS_CODE;
                    res.setHeader(PRERENDER_SERVER_STATUS_HEADER, PRERENDER_SERVER_STATUS_DRAINING);
                    res.end('draining');
                    return;
                }
                res.statusCode = 201;
                res.setHeader('Content-Type', 'application/json');
                res.end(JSON.stringify({
                    data: { attributes: { ok: true } },
                }));
            }).listen(0);
            let url = `http://127.0.0.1:${(server.address() as any).port}`;
            let prerenderer = createRemotePrerenderer(url);
            let result = await prerenderer.prerenderCard({
                realm: 'realm',
                url: 'https://example.com/card',
                auth: '{}',
            });
            expect((result as any).ok).toBe(true);
            await new Promise<void>((resolve) => server.close(() => resolve()));
        });
        test('fails after exhausting retries on 503', async function () {
            process.env.PRERENDER_MANAGER_RETRY_ATTEMPTS = '2';
            let attempts = 0;
            let server = createServer((_req, res) => {
                attempts++;
                res.statusCode = 503;
                res.end('unavailable');
            }).listen(0);
            let url = `http://127.0.0.1:${(server.address() as any).port}`;
            let prerenderer = createRemotePrerenderer(url);
            try {
                await prerenderer.prerenderCard({
                    realm: 'realm',
                    url: 'https://example.com/card',
                    auth: '{}',
                });
                expect(false).toBeTruthy();
            }
            catch (e: any) {
                expect(/status 503/.test(e.message)).toBeTruthy();
                expect(attempts >= 2).toBeTruthy();
            }
            finally {
                await new Promise<void>((resolve) => server.close(() => resolve()));
                delete process.env.PRERENDER_MANAGER_RETRY_ATTEMPTS;
                delete process.env.PRERENDER_MANAGER_RETRY_MAX_ELAPSED_MS;
            }
        });
        test('retries on manager 500 and succeeds', async function () {
            process.env.PRERENDER_MANAGER_RETRY_ATTEMPTS = '3';
            process.env.PRERENDER_MANAGER_RETRY_DELAY_MS = '1';
            let attempts = 0;
            let server = createServer((_req, res) => {
                attempts++;
                if (attempts === 1) {
                    res.statusCode = 500;
                    res.setHeader('Content-Type', 'application/json');
                    res.end(JSON.stringify({
                        errors: [{ status: 500, message: 'Protocol error' }],
                    }));
                    return;
                }
                res.statusCode = 201;
                res.setHeader('Content-Type', 'application/json');
                res.end(JSON.stringify({
                    data: { attributes: { ok: true } },
                }));
            }).listen(0);
            try {
                let url = `http://127.0.0.1:${(server.address() as any).port}`;
                let prerenderer = createRemotePrerenderer(url);
                let result = await prerenderer.prerenderCard({
                    realm: 'realm',
                    url: 'https://example.com/card',
                    auth: '{}',
                });
                expect((result as any).ok).toBe(true);
                expect(attempts >= 2).toBeTruthy();
            }
            finally {
                await new Promise<void>((resolve) => server.close(() => resolve()));
            }
        });
    });
});
describe("remote-prerenderer-test.ts", function () {
    describe('remote prerenderer timeouts', function () {
        test('does not retry when the client aborts from request timeout', async function () {
            process.env.PRERENDER_MANAGER_RETRY_ATTEMPTS = '3';
            process.env.PRERENDER_MANAGER_RETRY_DELAY_MS = '1';
            process.env.PRERENDER_MANAGER_REQUEST_TIMEOUT_MS = '20';
            let attempts = 0;
            let server = createServer((_req, res) => {
                attempts++;
                // Never respond; let client-side timeout abort the request.
                res.on('error', () => { });
            }).listen(0);
            try {
                let url = `http://127.0.0.1:${(server.address() as any).port}`;
                let prerenderer = createRemotePrerenderer(url);
                await assert.rejects(prerenderer.prerenderCard({
                    realm: 'realm',
                    url: 'https://example.com/card',
                    auth: '{}',
                }), /aborted/, 'throws after client-side abort');
                expect(attempts).toBe(1);
            }
            finally {
                await new Promise<void>((resolve) => server.close(() => resolve()));
            }
        });
    });
});
