export const STRUCTURED_THEME_TEMPLATE = `
{
  "data": {
    "type": "card",
    "attributes": {
      "cardInfo": {
        "title": "<title describing the theme>",
        "description": "<1-2 sentence summary>",
        "thumbnailURL": "<https url>"
      },
      "rootVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "darkModeVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "cssImports": ["<https font url>", "<optional second font url>"]
    }
  }
}
`;

export const STYLE_REFERENCE_TEMPLATE = `
{
  "data": {
    "type": "card",
    "attributes": {
      "styleName": "<style reference name>",
      "visualDNA": "<sentence describing the vibe>",
      "cardInfo": {
        "title": "<title>",
        "description": "<summary>",
        "thumbnailURL": "<https url>"
      },
      "inspirations": ["<keyword>", "<keyword>", "<keyword>"],
      "wallpaperImages": ["<https url>", "<https url>"],
      "cssImports": ["<https font url>", "<optional font url>"],
      "rootVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "darkModeVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "cssVariables": "<structured theme CSS string>"
    }
  }
}
`;

export const BRAND_GUIDE_TEMPLATE = `
{
  "data": {
    "type": "card",
    "attributes": {
      "styleName": "<brand guide name>",
      "visualDNA": "<sentence describing brand essence>",
      "cardInfo": {
        "title": "<title>",
        "description": "<summary>",
        "thumbnailURL": "<https url>"
      },
      "inspirations": ["<keyword>", "<keyword>", "<keyword>"],
      "wallpaperImages": ["<https url>", "<https url>"],
      "markUsage": {
        "primaryMark1": "<https url>",
        "primaryMarkMinHeight": "<px>",
        "primaryMarkClearanceRatio": "<ratio>",
        "socialMediaProfileIcon": "<https url>"
      },
      "typography": {
        "heading": {
          "fontFamily": "<font stack>",
          "fontWeight": "<numeric weight>",
          "fontSize": "<px>",
          "lineHeight": "<unitless>"
        },
        "body": {
          "fontFamily": "<font stack>",
          "fontWeight": "<numeric weight>",
          "fontSize": "<px>",
          "lineHeight": "<unitless>"
        }
      },
      "rootVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "darkModeVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "brandColorPalette": [
        { "name": "<swatch name 1>", "value": "<hex color>" },
        { "name": "<swatch name 2>", "value": "<hex color>" },
        { "name": "<swatch name 3>", "value": "<hex color>" }
      ],
      "functionalPalette": {
        "primary": "<hex color>",
        "secondary": "<hex color>",
        "accent": "<hex color>",
        "neutral": "<hex color>",
        "light": "<hex color>",
        "dark": "<hex color>",
        "border": "<hex color>"
      },
      "cornerRadius": "<px or rem>",
      "spacing": "<px or rem>",
      "cssImports": ["<https font url>"],
      "cssVariables": "<structured theme CSS string>"
    }
  }
}
`;
