export const BRAND_GUIDE_ROOT_VARIABLES = JSON.stringify(
  {
    card: '#FFFFFF',
    ring: '#0051BA',
    input: '#DFDFDF',
    muted: null,
    accent: null,
    border: null,
    chart1: '#0051BA',
    chart2: '#FFDB00',
    chart3: '#484848',
    chart4: '#DFDFDF',
    chart5: '#F5F5F5',
    radius: '2px',
    shadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    popover: '#FFFFFF',
    primary: null,
    sidebar: '#F5F5F5',
    spacing: '4px',
    fontMono: "'Courier New', monospace",
    fontSans: "'Noto IKEA', 'Noto Sans', sans-serif",
    shadowLg: '0 10px 15px rgba(0, 0, 0, 0.1)',
    shadowMd: '0 4px 6px rgba(0, 0, 0, 0.1)',
    shadowSm: '0 1px 2px rgba(0, 0, 0, 0.05)',
    shadowXl: '0 20px 25px rgba(0, 0, 0, 0.15)',
    shadowXs: '0 1px 1.5px rgba(0, 0, 0, 0.04)',
    fontSerif: "Georgia, 'Times New Roman', serif",
    secondary: null,
    shadow2xl: '0 25px 50px rgba(0, 0, 0, 0.25)',
    shadow2xs: '0 0.5px 1px rgba(0, 0, 0, 0.03)',
    background: '#FFFFFF',
    foreground: null,
    destructive: '#DC2626',
    sidebarRing: '#0051BA',
    sidebarAccent: '#FFDB00',
    sidebarBorder: '#DFDFDF',
    cardForeground: '#111111',
    sidebarPrimary: '#0051BA',
    trackingNormal: '0',
    mutedForeground: null,
    accentForeground: null,
    popoverForeground: '#111111',
    primaryForeground: null,
    sidebarForeground: '#111111',
    secondaryForeground: null,
    destructiveForeground: '#FFFFFF',
    sidebarAccentForeground: '#111111',
    sidebarPrimaryForeground: '#FFFFFF',
  },
  null,
  2,
);

export const STRUCTURED_THEME_ROOT_VARIABLES = JSON.stringify(
  {
    background: '#ffffff',
    foreground: '#111418',
    card: '#f8f9fb',
    cardForeground: '#111418',
    popover: '#ffffff',
    popoverForeground: '#111418',
    primary: '#5c6ac4',
    primaryForeground: '#ffffff',
    secondary: '#f3f6ff',
    secondaryForeground: '#1f2a48',
    muted: '#eef1f6',
    mutedForeground: '#4c5567',
    accent: '#f5eafb',
    accentForeground: '#5f2861',
    destructive: '#e23e57',
    destructiveForeground: '#ffffff',
    border: '#e1e6ef',
    input: '#d8deea',
    ring: '#7f8cf1',
    chart1: '#5c6ac4',
    chart2: '#4dc9b1',
    chart3: '#ffb347',
    chart4: '#eef1f6',
    chart5: '#d5e1ff',
    sidebar: '#ffffff',
    sidebarForeground: '#111418',
    sidebarPrimary: '#5c6ac4',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#f3f6ff',
    sidebarAccentForeground: '#1f2a48',
    sidebarBorder: '#e1e6ef',
    sidebarRing: '#7f8cf1',
    fontSans: "'Inter', system-ui, sans-serif",
    fontSerif: "'Playfair Display', serif",
    fontMono: "'JetBrains Mono', 'SFMono-Regular', monospace",
    radius: '0.5rem',
    spacing: '0.25rem',
    trackingNormal: '0.02em',
    shadow2xs: '0 0.5px 1px rgba(17, 20, 24, 0.05)',
    shadowXs: '0 1px 2px rgba(17, 20, 24, 0.06)',
    shadowSm: '0 1px 3px rgba(17, 20, 24, 0.08)',
    shadow: '0 2px 6px rgba(17, 20, 24, 0.08)',
    shadowMd: '0 4px 10px rgba(17, 20, 24, 0.1)',
    shadowLg: '0 8px 16px rgba(17, 20, 24, 0.12)',
    shadowXl: '0 12px 24px rgba(17, 20, 24, 0.14)',
    shadow2xl: '0 18px 30px rgba(17, 20, 24, 0.18)',
  },
  null,
  2,
);

export const STRUCTURED_THEME_TEMPLATE = `
{
  "data": {
    "type": "card",
    "attributes": {
      "cardInfo": {
        "title": "<title describing the theme>",
        "description": "<1-2 sentence summary>",
        "thumbnailURL": "<https url>"
      },
      "rootVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "darkModeVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "cssImports": ["<https font url>", "<optional second font url>"]
    }
  }
}
`;

export const STYLE_REFERENCE_TEMPLATE = `
{
  "data": {
    "type": "card",
    "attributes": {
      "styleName": "<style reference name>",
      "visualDNA": "<sentence describing the vibe>",
      "cardInfo": {
        "title": "<title>",
        "description": "<summary>",
        "thumbnailURL": "<https url>"
      },
      "inspirations": ["<keyword>", "<keyword>", "<keyword>"],
      "wallpaperImages": ["<https url>", "<https url>"],
      "cssImports": ["<https font url>", "<optional font url>"],
      "rootVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "darkModeVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "cssVariables": "<structured theme CSS string>"
    }
  }
}
`;

export const BRAND_GUIDE_TEMPLATE = `
{
  "data": {
    "type": "card",
    "attributes": {
      "styleName": "<brand guide name>",
      "visualDNA": "<sentence describing brand essence>",
      "cardInfo": {
        "title": "<title>",
        "description": "<summary>",
        "thumbnailURL": "<https url>"
      },
      "inspirations": ["<keyword>", "<keyword>", "<keyword>"],
      "wallpaperImages": ["<https url>", "<https url>"],
      "markUsage": {
        "primaryMark1": "<https url>",
        "primaryMarkMinHeight": "<px>",
        "primaryMarkClearanceRatio": "<ratio>",
        "socialMediaProfileIcon": "<https url>"
      },
      "typography": {
        "heading": {
          "fontFamily": "<font stack>",
          "fontWeight": "<numeric weight>",
          "fontSize": "<px>",
          "lineHeight": "<unitless>"
        },
        "body": {
          "fontFamily": "<font stack>",
          "fontWeight": "<numeric weight>",
          "fontSize": "<px>",
          "lineHeight": "<unitless>"
        }
      },
      "rootVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "darkModeVariables": {
        "background": "<hex color>",
        "foreground": "<hex color>",
        "card": "<hex color>",
        "cardForeground": "<hex color>",
        "popover": "<hex color>",
        "popoverForeground": "<hex color>",
        "primary": "<hex color>",
        "primaryForeground": "<hex color>",
        "secondary": "<hex color>",
        "secondaryForeground": "<hex color>",
        "muted": "<hex color>",
        "mutedForeground": "<hex color>",
        "accent": "<hex color>",
        "accentForeground": "<hex color>",
        "destructive": "<hex color>",
        "destructiveForeground": "<hex color>",
        "border": "<hex color>",
        "input": "<hex color>",
        "ring": "<hex color>",
        "chart1": "<hex color>",
        "chart2": "<hex color>",
        "chart3": "<hex color>",
        "chart4": "<hex color>",
        "chart5": "<hex color>",
        "sidebar": "<hex color>",
        "sidebarForeground": "<hex color>",
        "sidebarPrimary": "<hex color>",
        "sidebarPrimaryForeground": "<hex color>",
        "sidebarAccent": "<hex color>",
        "sidebarAccentForeground": "<hex color>",
        "sidebarBorder": "<hex color>",
        "sidebarRing": "<hex color>",
        "fontSans": "<font stack>",
        "fontSerif": "<font stack>",
        "fontMono": "<font stack>",
        "radius": "<px or rem>",
        "spacing": "<px or rem>",
        "trackingNormal": "<em or unitless>",
        "shadow2xs": "<shadow value>",
        "shadowXs": "<shadow value>",
        "shadowSm": "<shadow value>",
        "shadow": "<shadow value>",
        "shadowMd": "<shadow value>",
        "shadowLg": "<shadow value>",
        "shadowXl": "<shadow value>",
        "shadow2xl": "<shadow value>"
      },
      "brandColorPalette": [
        { "name": "<swatch name 1>", "value": "<hex color>" },
        { "name": "<swatch name 2>", "value": "<hex color>" },
        { "name": "<swatch name 3>", "value": "<hex color>" }
      ],
      "functionalPalette": {
        "primary": "<hex color>",
        "secondary": "<hex color>",
        "accent": "<hex color>",
        "neutral": "<hex color>",
        "light": "<hex color>",
        "dark": "<hex color>",
        "border": "<hex color>"
      },
      "cornerRadius": "<px or rem>",
      "spacing": "<px or rem>",
      "cssImports": ["<https font url>"],
      "cssVariables": "<structured theme CSS string>"
    }
  }
}
`;
