#!/bin/sh
#MISE description="Clear the modules cache in the database"
#MISE depends=["infra:ensure-pg"]
#MISE dir="packages/realm-server"

echo "Clearing modules cache..."
PGPORT="${PGPORT}" PGDATABASE="${PGDATABASE}" \
  NODE_NO_WARNINGS=1 \
  ts-node --transpileOnly scripts/clear-modules-cache.ts
