#!/bin/sh
#MISE description="Wait for PostgreSQL to be ready"

COUNT=0
MAX_ATTEMPTS=10

while ! docker exec boxel-pg pg_isready -U postgres >/dev/null 2>&1; do
  if [ $COUNT -eq 0 ]; then
    echo "Waiting for postgres"
  fi
  if [ $COUNT -eq $MAX_ATTEMPTS ]; then
    echo "Failed to detect postgres after $MAX_ATTEMPTS attempts."
    exit 1
  fi
  COUNT=$((COUNT + 1))
  printf '.'
  sleep 5
done
