// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from './types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-barn'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='M22 12H2l2-6 8-4 8 4Z' /><path
      d='M10 8h4v4h-4zM7 22l10-10v10L7 12Z'
    /><path d='M21 12v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-8' /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'barn';
export default IconComponent;
