// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from './types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-book-dashed'
    viewBox='0 0 24 24'
    ...attributes
  ><path
      d='M12 17h2M12 22h2M12 2h2M18 22h1a1 1 0 0 0 1-1M18 2h1a1 1 0 0 1 1 1v1M20 15v2h-2M20 8v3M4 11V9M4 19.5V15M4 5v-.5A2.5 2.5 0 0 1 6.5 2H8M8 22H6.5a1 1 0 0 1 0-5H8'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'book-dashed';
export default IconComponent;
