// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from './types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-cocktail'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='M9 6 6.6 2.8C6.3 2.4 5.6 2 5 2H2M18 6l-7 8-7-8Z' /><path
      d='M15.4 9.1A4 4 0 1 0 14 6M11 14v8M7 22h8'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'cocktail';
export default IconComponent;
