// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from './types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-flower-tulip'
    viewBox='0 0 24 24'
    ...attributes
  ><path d='M12 7c-2-3.2-6-4-6-4v5c0 3.3 2.7 6 6 6v8' /><path
      d='M9.5 4.5C10 3 12 2 12 2s2 1 2.5 2.5'
    /><path
      d='M12 14c3.3 0 6-2.7 6-6V3c-6.2.9-10.8 11-6 11M12 22c-4.2 0-7-1.7-7-5 4.2 0 7 1.7 7 5M12 22c4.2 0 7-1.7 7-5-4.2 0-7 1.7-7 5'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'flower-tulip';
export default IconComponent;
