// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from './types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-git-pull-request-closed'
    viewBox='0 0 24 24'
    ...attributes
  ><circle cx='6' cy='6' r='3' /><path
      d='M6 9v12M21 3l-6 6M21 9l-6-6M18 11.5V15'
    /><circle cx='18' cy='18' r='3' /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'git-pull-request-closed';
export default IconComponent;
