// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from './types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-microwave'
    viewBox='0 0 24 24'
    ...attributes
  ><rect width='20' height='15' x='2' y='4' rx='2' /><rect
      width='8'
      height='7'
      x='6'
      y='8'
      rx='1'
    /><path d='M18 8v7M6 19v2M18 19v2' /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'microwave';
export default IconComponent;
