// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from './types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-snowman'
    viewBox='0 0 24 24'
    ...attributes
  ><circle cx='12' cy='6' r='4' /><path
      d='M12 14h.01M12 18h.01M2 9h2V7M7 12 4 9M17.8 11.1 20 9M20 7v2h2M9 8.7a7 7 0 1 0 6 0M5 22h14'
    /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'snowman';
export default IconComponent;
