// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from './types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-unicorn-head'
    viewBox='0 0 24 24'
    ...attributes
  ><path
      d='m15.6 4.8 2.7 2.3M15.5 10S19 7 22 2c-6 2-10 5-10 5M11.5 12H11'
    /><path
      d='M5 15a4 4 0 0 0 4 4h7.8l.3.3a3 3 0 0 0 4-4.46L12 7c0-3-1-5-1-5S8 3 8 7c-4 1-6 3-6 3'
    /><path d='M2 4.5C4 3 6 3 6 3l2 4M6.14 17.8S4 19 2 22' /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'unicorn-head';
export default IconComponent;
