// This file is auto-generated by 'pnpm rebuild:all'
import type { TemplateOnlyComponent } from '@ember/component/template-only';

import type { Signature } from './types.ts';

const IconComponent: TemplateOnlyComponent<Signature> = <template>
  <svg
    xmlns='http://www.w3.org/2000/svg'
    width='24'
    height='24'
    fill='none'
    stroke='currentColor'
    stroke-linecap='round'
    stroke-linejoin='round'
    stroke-width='2'
    class='lucide lucide-videotape'
    viewBox='0 0 24 24'
    ...attributes
  ><rect width='20' height='16' x='2' y='4' rx='2' /><path d='M2 8h20' /><circle
      cx='8'
      cy='14'
      r='2'
    /><path d='M8 12h8' /><circle cx='16' cy='14' r='2' /></svg>
</template>;

// @ts-expect-error this is the only way to set a name on a Template Only Component currently
IconComponent.name = 'videotape';
export default IconComponent;
