import { readdirSync, readFileSync } from 'fs';
import { join, relative, resolve } from 'path';

// Duration-weighted assignment of Playwright spec files to CI shards.
//
// Playwright's own `--shard` balances the number of tests, not their cost.
// This suite's per-test cost spans three orders of magnitude — a
// synapse-oidc-gating case is skipped in milliseconds while a host-mode case
// boots a realm and a browser for the better part of a minute — so an
// equal-count split leaves one shard running several times longer than
// another. Assignment here instead bin-packs whole spec files by their
// recorded duration (tests/spec-timings.json, regenerated by
// scripts/generate-spec-timings.mjs).
//
// Every shard in a run computes the assignment for ALL shards from the same
// inputs and keeps only its own bucket, so the algorithm must be
// deterministic: files are sorted (by weight descending, path ascending) and
// greedily assigned to the lightest bucket, ties going to the lowest bucket
// index. That makes the buckets a partition — every discovered spec file
// runs on exactly one shard — which is the property the suite's coverage
// depends on.
//
// A file absent from the timings data gets the median known weight, so a
// newly added spec runs (on exactly one shard) without the timings file
// needing regeneration first.

// Matches what Playwright's default `testMatch` would pick up, so a spec
// file the runner would otherwise have run can never be missing from the
// assignment — the failure mode of a narrower pattern here is a file that
// runs on no shard at all.
const SPEC_FILE_PATTERN = /\.(spec|test)\.[cm]?[jt]sx?$/;

// A file recorded at (or rounding to) zero is pathological for the pack:
// adding it never changes a bucket's running weight, so every zero-weight
// file lands in whichever bucket is lightest — and that bucket stays
// lightest, so they all collect together. Flooring every weight at a nominal
// per-file cost both stands in for the boot and hook time the recorded
// durations can't see and keeps such files spread across buckets.
//
// scripts/generate-spec-timings.mjs floors identically, because the drift
// gate deciding whether to rewrite the timings file predicts the slowest
// shard by replaying this pack.
const MIN_SPEC_WEIGHT_SECONDS = 1;

export interface ShardCoordinates {
  index: number;
  total: number;
}

// Parses the `<index>/<total>` form CI passes through to `pnpm test:group`.
// An unset or empty value means "run everything", which is what a local
// `pnpm test` does.
export function parseShardCoordinates(
  raw: string | undefined,
): ShardCoordinates | undefined {
  if (!raw?.trim()) {
    return undefined;
  }
  let match = /^(\d+)\s*\/\s*(\d+)$/.exec(raw.trim());
  if (!match) {
    throw new Error(
      `expected a shard of the form <index>/<total>, got ${JSON.stringify(raw)}`,
    );
  }
  let index = Number(match[1]);
  let total = Number(match[2]);
  if (total < 1 || index < 1 || index > total) {
    throw new Error(`shard index must be in 1..total, got ${index}/${total}`);
  }
  return { index, total };
}

export function discoverSpecFiles(testDir: string): string[] {
  let root = resolve(testDir);
  let found: string[] = [];
  let walk = (dir: string) => {
    for (let entry of readdirSync(dir, { withFileTypes: true })) {
      let full = join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (SPEC_FILE_PATTERN.test(entry.name)) {
        found.push(relative(root, full).split('\\').join('/'));
      }
    }
  };
  walk(root);
  return found.sort();
}

export function loadSpecTimings(path: string): Record<string, number> {
  return JSON.parse(readFileSync(path, 'utf8')) as Record<string, number>;
}

export function assignSpecFiles(
  specFiles: string[],
  shard: number,
  shardCount: number,
  timings: Record<string, number>,
): string[] {
  if (!Number.isInteger(shard) || !Number.isInteger(shardCount)) {
    throw new Error(
      `shard and shardCount must be integers (got shard=${shard}, shardCount=${shardCount})`,
    );
  }
  if (shardCount < 1 || shard < 1 || shard > shardCount) {
    throw new Error(
      `shard must be in 1..shardCount (got shard=${shard}, shardCount=${shardCount})`,
    );
  }

  let knownWeights = Object.values(timings)
    .map((weight) => Math.max(weight, MIN_SPEC_WEIGHT_SECONDS))
    .sort((a, b) => a - b);
  let defaultWeight = knownWeights.length
    ? knownWeights[Math.floor(knownWeights.length / 2)]
    : MIN_SPEC_WEIGHT_SECONDS;
  // `== null`, not `??` on a floored value: a file measured at 0 takes the
  // floor, not the median a file with no measurement at all gets.
  let weightOf = (file: string) => {
    let measured = timings[file];
    return measured == null
      ? defaultWeight
      : Math.max(measured, MIN_SPEC_WEIGHT_SECONDS);
  };

  let ordered = [...specFiles].sort((a, b) => {
    let diff = weightOf(b) - weightOf(a);
    if (diff !== 0) {
      return diff;
    }
    return a < b ? -1 : a > b ? 1 : 0;
  });

  let buckets: { weight: number; files: string[] }[] = Array.from(
    { length: shardCount },
    () => ({ weight: 0, files: [] }),
  );
  for (let file of ordered) {
    let lightest = buckets[0];
    for (let bucket of buckets) {
      if (bucket.weight < lightest.weight) {
        lightest = bucket;
      }
    }
    lightest.files.push(file);
    lightest.weight += weightOf(file);
  }

  return buckets[shard - 1].files;
}

// Playwright matches a `testMatch` string as a glob against the file's
// absolute path, with an implicit `**/` prefix — so a bare `login.spec.ts`
// would also select `sub/login.spec.ts`, putting one file on two shards.
// Anchoring each entry to the absolute test directory keeps the assignment
// the exact partition the pack computed.
export function specFileMatchers(
  testDir: string,
  specFiles: string[],
): RegExp[] {
  let root = resolve(testDir);
  return specFiles.map(
    (file) => new RegExp(`^${escapeForRegExp(join(root, file))}$`),
  );
}

function escapeForRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
