flowchart
    PostgresInfra-->PostgresMigrations
    PostgresMigrations-->PostgresQueue
    JobQueueFacade-->SQLiteIndexerImplementation
    SQLiteIndexerImplementation-->PostgresIndexerImplementation
    PostgresInfra-->PostgresIndexerImplementation
    TestHelperForIndexedCardTablePopulation-->SQLiteQueryEngineImplementation
    SQLiteQueryEngineImplementation-->PostgresQueryEngineImplementation
    PostgresInfra-->PostgresQueryEngineImplementation
    SQLiteIndexerImplementation-->IndexInvalidation
    SQLiteIndexerImplementation-->UseSQLiteIndexerInHostTests
    PostgresIndexerImplementation-->UsePostgresIndexerInRealmServer
    PostgresQueue-->UsePostgresIndexerInRealmServer


