flowchart
    PostgresInfra[Postgres Infra\nCS-6464]
    click PostgresInfra "https://linear.app/cardstack/issue/CS-6464" "Open in Linear"
    PostgresMigrations[Postgres Migrations Setup\nCS-6460]
    click PostgresMigrations "https://linear.app/cardstack/issue/CS-6460" "Open in Linear"
    PostgresQueue[Postgres Queue\nCS-6462]
    click PostgresQueue "https://linear.app/cardstack/issue/CS-6462" "Open in Linear"
    JobQueueFacade[Job Queue API\nCS-6459]
    click JobQueueFacade "https://linear.app/cardstack/issue/CS-6459" "Open in Linear"
    SQLiteIndexerImplementation[SQLite Indexer\nImplementation\nCS-6626]
    click SQLiteIndexerImplementation "https://linear.app/cardstack/issue/CS-6626" "Open in Linear"
    PostgresIndexerImplementation[Postgres Indexer\nImplementation\nCS-6627]
    click PostgresIndexerImplementation "https://linear.app/cardstack/issue/CS-6627" "Open in Linear"
    TestHelperForIndexedCardTablePopulation[Test Helper For\nIndexed Card Table Population\nCS-6637]
    click TestHelperForIndexedCardTablePopulation "https://linear.app/cardstack/issue/CS-6637" "Open in Linear"
    SQLiteQueryEngineImplementation[SQLite Query Engine Implementation\nCS-6457]
    click SQLiteQueryEngineImplementation "https://linear.app/cardstack/issue/CS-6457" "Open in Linear"
    PostgresQueryEngineImplementation[Postgres Query Engine\nImplementation\nCS-6614]
    click PostgresQueryEngineImplementation "https://linear.app/cardstack/issue/CS-6614" "Open in Linear"
    IndexInvalidation[Index Invalidation\nCS-6467]
    click IndexInvalidation "https://linear.app/cardstack/issue/CS-6467" "Open in Linear"
    UseSQLiteIndexerInHostTests[Use SQLite Indexer\nIn Host Tests\nCS-6638]
    click UseSQLiteIndexerInHostTests "https://linear.app/cardstack/issue/CS-6638" "Open in Linear"
    UsePostgresIndexerInRealmServer[Use Postgres Indexer\nIn Realm Server\nCS-6639]
    click UsePostgresIndexerInRealmServer "https://linear.app/cardstack/issue/CS-6639" "Open in Linear"
    PostgresInfra-->PostgresMigrations
    PostgresMigrations-->PostgresQueue
    JobQueueFacade-->SQLiteIndexerImplementation
    SQLiteIndexerImplementation-->PostgresIndexerImplementation
    PostgresInfra-->PostgresIndexerImplementation
    TestHelperForIndexedCardTablePopulation-->SQLiteQueryEngineImplementation
    SQLiteQueryEngineImplementation-->PostgresQueryEngineImplementation
    PostgresInfra-->PostgresQueryEngineImplementation
    SQLiteIndexerImplementation-->IndexInvalidation
    SQLiteIndexerImplementation-->UseSQLiteIndexerInHostTests
    PostgresIndexerImplementation-->UsePostgresIndexerInRealmServer
    PostgresQueue-->UsePostgresIndexerInRealmServer
    JobQueueFacade-->PostgresQueue


