export interface Country {
  ISO3_CODE: string;
  ISO2_CODE: string;
  CURRENCY: { NAME: string[]; CODE: string[]; NUM: string[] }[];
  LIST_OF_NAME: { [key: string]: string[] };
}

export const countries = {
  ABW: {
    ISO3_CODE: 'ABW',
    ISO2_CODE: 'AW',
    CURRENCY: [{ NAME: ['Aruban Florin'], CODE: ['AWG'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Aruba'], DUTCH: ['Aruba'] },
  },
  AFG: {
    ISO3_CODE: 'AFG',
    ISO2_CODE: 'AF',
    CURRENCY: [{ NAME: ['Afghan afghani'], CODE: ['AFN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Afghanistan'], DUTCH: ['Afghanistan'] },
  },
  AGO: {
    ISO3_CODE: 'AGO',
    ISO2_CODE: 'AO',
    CURRENCY: [{ NAME: ['Angolan kwanza'], CODE: ['AOA'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Angola'], DUTCH: ['Angola'] },
  },
  AIA: {
    ISO3_CODE: 'AIA',
    ISO2_CODE: 'AI',
    CURRENCY: [{ NAME: ['East Caribbean dollar'], CODE: ['XCD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Anguilla'], DUTCH: ['Anguilla'] },
  },
  ALA: {
    ISO3_CODE: 'ALA',
    ISO2_CODE: 'AX',
    CURRENCY: [{ NAME: ['European euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Aland Islands', 'Aland Islands (Finland)'],
      DUTCH: ['Aland-eilanden', 'Aland-eilanden (Finland)'],
    },
  },
  ALB: {
    ISO3_CODE: 'ALB',
    ISO2_CODE: 'AL',
    CURRENCY: [{ NAME: ['Albanian lek'], CODE: ['ALL'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Albania'], DUTCH: ['Albanië'] },
  },
  AND: {
    ISO3_CODE: '',
    ISO2_CODE: 'AD',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Andorra'], DUTCH: ['Andorra'] },
  },
  ARE: {
    ISO3_CODE: 'ARE',
    ISO2_CODE: 'AE',
    CURRENCY: [
      { NAME: ['United Arab Emirates dirham'], CODE: ['AED'], NUM: [] },
    ],
    LIST_OF_NAME: {
      ENG: ['United Arab Emirates'],
      DUTCH: ['Verenigde Arabische Emiraten'],
    },
  },
  ARG: {
    ISO3_CODE: 'ARG',
    ISO2_CODE: 'AR',
    CURRENCY: [{ NAME: ['Argentine peso'], CODE: ['ARS'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Argentina'], DUTCH: ['Argentinië'] },
  },
  ARM: {
    ISO3_CODE: 'ARM',
    ISO2_CODE: 'AM',
    CURRENCY: [{ NAME: ['Armenian dram'], CODE: ['AMD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Armenia'], DUTCH: ['Armenië'] },
  },
  ASM: {
    ISO3_CODE: 'ASM',
    ISO2_CODE: 'AS',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['American Samoa'], DUTCH: ['Amerikaans Samoa'] },
  },
  ATA: {
    ISO3_CODE: 'ATA',
    ISO2_CODE: 'AQ',
    CURRENCY: [],
    LIST_OF_NAME: { ENG: ['Antarctica'], DUTCH: ['Antarctica'] },
  },
  ATF: {
    ISO3_CODE: 'ATF',
    ISO2_CODE: 'TF',
    CURRENCY: [],
    LIST_OF_NAME: {
      ENG: ['French Southern Territories'],
      DUTCH: ['Franse zuidelijke gebieden'],
    },
  },
  ATG: {
    ISO3_CODE: 'ATG',
    ISO2_CODE: 'AG',
    CURRENCY: [{ NAME: ['East Caribbean dollar'], CODE: ['XCD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Antigua and Barbuda'],
      DUTCH: ['Antigua en Barbuda'],
    },
  },
  AUS: {
    ISO3_CODE: 'AUS',
    ISO2_CODE: 'AU',
    CURRENCY: [{ NAME: ['Australian dollar'], CODE: ['AUD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Australia'], DUTCH: ['Australië'] },
  },
  AUT: {
    ISO3_CODE: 'AUT',
    ISO2_CODE: 'AT',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Austria'], DUTCH: ['Oostenrijk'] },
  },
  AZE: {
    ISO3_CODE: 'AZE',
    ISO2_CODE: 'AZ',
    CURRENCY: [{ NAME: ['Azerbaijani manat'], CODE: ['AZN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Azerbaijan'], DUTCH: ['Azerbeidzjan'] },
  },
  BDI: {
    ISO3_CODE: 'BDI',
    ISO2_CODE: 'BI',
    CURRENCY: [{ NAME: ['Burundian franc'], CODE: ['BIF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Burundi'], DUTCH: ['Burundi'] },
  },
  BEL: {
    ISO3_CODE: 'BEL',
    ISO2_CODE: 'BE',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Belgium'], DUTCH: ['België'] },
  },
  BEN: {
    ISO3_CODE: 'BEN',
    ISO2_CODE: 'BJ',
    CURRENCY: [{ NAME: ['CFA franc BCEAO'], CODE: ['XOF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Benin'], DUTCH: ['Benin'] },
  },
  BES: {
    ISO3_CODE: 'BES',
    ISO2_CODE: '',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Bonaire'], DUTCH: ['Bonaire'] },
  },
  BFA: {
    ISO3_CODE: 'BFA',
    ISO2_CODE: 'BF',
    CURRENCY: [{ NAME: ['CFA franc BCEAO'], CODE: ['XOF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Burkina Faso'], DUTCH: ['Burkina Faso'] },
  },
  BGD: {
    ISO3_CODE: 'BGD',
    ISO2_CODE: 'BD',
    CURRENCY: [{ NAME: ['Bangladeshi taka'], CODE: ['BDT'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Bangladesh'], DUTCH: ['Bangladesh'] },
  },
  BGR: {
    ISO3_CODE: 'BGR',
    ISO2_CODE: 'BG',
    CURRENCY: [{ NAME: ['Bulgarian lev'], CODE: ['BGN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Bulgaria'], DUTCH: ['Bulgarije'] },
  },
  BHR: {
    ISO3_CODE: 'BHR',
    ISO2_CODE: 'BH',
    CURRENCY: [{ NAME: ['Bahraini dinar'], CODE: ['BHD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Bahrain'], DUTCH: ['Bahrein'] },
  },
  BHS: {
    ISO3_CODE: 'BHS',
    ISO2_CODE: 'BS',
    CURRENCY: [{ NAME: ['Bahamian dollar'], CODE: ['BSD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Bahamas'], DUTCH: ['Bahama’s'] },
  },
  BIH: {
    ISO3_CODE: 'BIH',
    ISO2_CODE: 'BA',
    CURRENCY: [
      {
        NAME: ['Bosnia and Herzegovina convertible mark'],
        CODE: ['BAM'],
        NUM: [],
      },
    ],
    LIST_OF_NAME: {
      ENG: ['Bosnia and Herzegovina'],
      DUTCH: ['Bosnië en Herzegovina '],
    },
  },
  BLM: {
    ISO3_CODE: 'BLM',
    ISO2_CODE: 'BL',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Saint Barthelemy'], DUTCH: ['Saint Barthelemy'] },
  },
  BLR: {
    ISO3_CODE: 'BLR',
    ISO2_CODE: 'BY',
    CURRENCY: [{ NAME: ['Belarusian ruble'], CODE: ['BYN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Belarus'], DUTCH: ['Wit-Rusland '] },
  },
  BLZ: {
    ISO3_CODE: 'BLZ',
    ISO2_CODE: 'BZ',
    CURRENCY: [{ NAME: ['Belize dollar'], CODE: ['BZD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Belize'], DUTCH: ['Belize'] },
  },
  BMU: {
    ISO3_CODE: 'BMU',
    ISO2_CODE: 'BM',
    CURRENCY: [{ NAME: ['Bermudian dollar'], CODE: ['BMD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Bermuda'], DUTCH: ['Bermuda'] },
  },
  BOL: {
    ISO3_CODE: 'BOL',
    ISO2_CODE: 'BO',
    CURRENCY: [{ NAME: ['Bolivian boliviano'], CODE: ['BOB'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Bolivia'], DUTCH: ['Bolivia'] },
  },
  BRA: {
    ISO3_CODE: 'BRA',
    ISO2_CODE: 'BR',
    CURRENCY: [{ NAME: ['Brazilian real'], CODE: ['BRL'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Brazil'], DUTCH: ['Brazilië'] },
  },
  BRB: {
    ISO3_CODE: 'BRB',
    ISO2_CODE: 'BB',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Barbados'], DUTCH: ['Barbados'] },
  },
  BRN: {
    ISO3_CODE: 'BRN',
    ISO2_CODE: 'BN',
    CURRENCY: [{ NAME: ['Brunei dollar'], CODE: ['BND'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Brunei Darussalam'], DUTCH: ['Brunei Darussalam'] },
  },
  BTN: {
    ISO3_CODE: 'BTN',
    ISO2_CODE: 'BT',
    CURRENCY: [{ NAME: ['Bhutanese ngultrum'], CODE: ['BTN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Bhutan'], DUTCH: ['Bhutan'] },
  },
  BVT: {
    ISO3_CODE: 'BVT',
    ISO2_CODE: 'BV',
    CURRENCY: [{ NAME: ['Norwegian krone'], CODE: ['NOK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Bouvet Island'], DUTCH: ['Bouvet Island'] },
  },
  BWA: {
    ISO3_CODE: 'BWA',
    ISO2_CODE: 'BW',
    CURRENCY: [{ NAME: ['Botswana pula'], CODE: ['BWP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Botswana'], DUTCH: ['Botswana'] },
  },
  CAF: {
    ISO3_CODE: 'CAF',
    ISO2_CODE: 'CF',
    CURRENCY: [{ NAME: ['CFA franc BEAC'], CODE: ['XAF'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Central African Republic'],
      DUTCH: ['Centraal-Afrikaanse Republiek'],
    },
  },
  CAN: {
    ISO3_CODE: 'CAN',
    ISO2_CODE: 'CA',
    CURRENCY: [{ NAME: ['Canadian dollar'], CODE: ['CAD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Canada'], DUTCH: ['Canada'] },
  },
  CCK: {
    ISO3_CODE: 'CCK',
    ISO2_CODE: 'CC',
    CURRENCY: [{ NAME: ['Australian dollar'], CODE: ['AUD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Cocos (Keeling) Islands'],
      DUTCH: ['Cocos (Keeling) eilanden'],
    },
  },
  CHE: {
    ISO3_CODE: 'CHE',
    ISO2_CODE: 'CH',
    CURRENCY: [{ NAME: ['Swiss franc'], CODE: ['CHF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Switzerland'], DUTCH: ['Zwitserland'] },
  },
  CHL: {
    ISO3_CODE: 'CHL',
    ISO2_CODE: 'CL',
    CURRENCY: [{ NAME: ['Chilean peso'], CODE: ['CLP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Chile'], DUTCH: ['Chili'] },
  },
  CHN: {
    ISO3_CODE: 'CHN',
    ISO2_CODE: 'CN',
    CURRENCY: [{ NAME: ['Renminbi (Chinese) yuan'], CODE: ['CNY'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['China'], DUTCH: ['China'] },
  },
  CIV: {
    ISO3_CODE: 'CIV',
    ISO2_CODE: 'CI',
    CURRENCY: [{ NAME: ['CFA franc BCEAO'], CODE: ['XOF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ["Cote d'Ivoire"], DUTCH: ['Ivoorkust'] },
  },
  CMR: {
    ISO3_CODE: 'CMR',
    ISO2_CODE: 'CM',
    CURRENCY: [{ NAME: ['CFA franc BEAC'], CODE: ['XAF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Cameroon'], DUTCH: ['Kameroen'] },
  },
  COD: {
    ISO3_CODE: 'COD',
    ISO2_CODE: 'CD',
    CURRENCY: [{ NAME: ['Congolese franc'], CODE: ['CDF'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Democratic Republic of the Congo', 'Kinshasa', 'Congo (Kinshasa)'],
      DUTCH: ['Democratische Republiek Congo', 'Kinshasa', 'Congo (Kinshasa)'],
    },
  },
  COG: {
    ISO3_CODE: 'COG',
    ISO2_CODE: 'CG',
    CURRENCY: [{ NAME: ['CFA franc BEAC'], CODE: ['XAF'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Republic of the Congo ', 'Brazzaville', 'Congo(Brazzaville)'],
      DUTCH: ['Republiek Congo', 'Brazzaville', 'Congo(Brazzaville)'],
    },
  },
  COK: {
    ISO3_CODE: 'COK',
    ISO2_CODE: 'CK',
    CURRENCY: [{ NAME: ['New Zealand dollar'], CODE: ['NZD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Cook Islands'], DUTCH: ['Cook Eilanden'] },
  },
  COL: {
    ISO3_CODE: 'COL',
    ISO2_CODE: 'CO',
    CURRENCY: [{ NAME: ['Colombian peso'], CODE: ['COP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Colombia'], DUTCH: ['Colombia'] },
  },
  COM: {
    ISO3_CODE: 'COM',
    ISO2_CODE: 'KM',
    CURRENCY: [{ NAME: ['Comoro franc'], CODE: ['KMF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Comoros'], DUTCH: ['Comoren'] },
  },
  CPV: {
    ISO3_CODE: 'CPV',
    ISO2_CODE: 'CV',
    CURRENCY: [{ NAME: ['Cape Verdean escudo'], CODE: ['CVE'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Cabo Verde'], DUTCH: ['Cabo Verde'] },
  },
  CRI: {
    ISO3_CODE: 'CRI',
    ISO2_CODE: 'CR',
    CURRENCY: [{ NAME: ['Costa Rican colon'], CODE: ['CRC'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Costa Rica'], DUTCH: ['Costa Rica'] },
  },
  CUB: {
    ISO3_CODE: 'CUB',
    ISO2_CODE: 'CU',
    CURRENCY: [{ NAME: ['Cuban peso'], CODE: ['CUP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Cuba'], DUTCH: ['Cuba'] },
  },
  CUW: {
    ISO3_CODE: 'CUW',
    ISO2_CODE: 'CW',
    CURRENCY: [
      { NAME: ['Netherlands Antillean guilder'], CODE: ['ANG'], NUM: [] },
    ],
    LIST_OF_NAME: { ENG: ['Curacao'], DUTCH: ['Curacao'] },
  },
  CXR: {
    ISO3_CODE: 'CXR',
    ISO2_CODE: 'CX',
    CURRENCY: [{ NAME: ['Australian dollar'], CODE: ['AUD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Christmas Island'], DUTCH: ['Kersteiland'] },
  },
  CYM: {
    ISO3_CODE: 'CYM',
    ISO2_CODE: 'KY',
    CURRENCY: [{ NAME: ['Cayman Islands dollar'], CODE: ['KYD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Cayman Islands'], DUTCH: ['Kaaiman Eilanden'] },
  },
  CYP: {
    ISO3_CODE: 'CYP',
    ISO2_CODE: 'CY',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Cyprus'], DUTCH: ['Cyprus'] },
  },
  CZE: {
    ISO3_CODE: 'CZE',
    ISO2_CODE: 'CZ',
    CURRENCY: [{ NAME: ['Czech koruna'], CODE: ['CZK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Czechia'], DUTCH: ['Tsjechië'] },
  },
  DEU: {
    ISO3_CODE: '',
    ISO2_CODE: 'DE',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Germany'], DUTCH: ['Duitsland'] },
  },
  DJI: {
    ISO3_CODE: 'DJI',
    ISO2_CODE: 'DJ',
    CURRENCY: [{ NAME: ['Djiboutian franc'], CODE: ['DJF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Djibouti'], DUTCH: ['Djibouti'] },
  },
  DMA: {
    ISO3_CODE: 'DMA',
    ISO2_CODE: 'DM',
    CURRENCY: [{ NAME: ['East Caribbean dollar'], CODE: ['XCD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Dominica'], DUTCH: ['Dominica'] },
  },
  DNK: {
    ISO3_CODE: 'DNK',
    ISO2_CODE: 'DK',
    CURRENCY: [{ NAME: ['Danish krone'], CODE: ['DKK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Denmark'], DUTCH: ['Denemarken'] },
  },
  DOM: {
    ISO3_CODE: 'DOM',
    ISO2_CODE: 'DO',
    CURRENCY: [{ NAME: ['Dominican peso'], CODE: ['DOP'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Dominican Republic'],
      DUTCH: ['Dominicaanse Republiek'],
    },
  },
  DZA: {
    ISO3_CODE: 'DZA',
    ISO2_CODE: 'DZ',
    CURRENCY: [{ NAME: ['Algerian dinar'], CODE: ['DZD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Algeria'], DUTCH: ['Algerije'] },
  },
  ECU: {
    ISO3_CODE: 'ECU',
    ISO2_CODE: 'EC',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Ecuador'], DUTCH: ['Ecuador'] },
  },
  EGY: {
    ISO3_CODE: 'EGY',
    ISO2_CODE: 'EG',
    CURRENCY: [{ NAME: ['Egyptian pound'], CODE: ['EGP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Egypt'], DUTCH: ['Egypte'] },
  },
  ERI: {
    ISO3_CODE: 'ERI',
    ISO2_CODE: 'ER',
    CURRENCY: [{ NAME: ['Eritrean nakfa'], CODE: ['ERN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Eritrea'], DUTCH: ['Eritrea'] },
  },
  ESH: {
    ISO3_CODE: 'ESH',
    ISO2_CODE: 'EH',
    CURRENCY: [],
    LIST_OF_NAME: { ENG: ['Western Sahara'], DUTCH: ['Westelijke Sahara'] },
  },
  ESP: {
    ISO3_CODE: 'ESP',
    ISO2_CODE: 'ES',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Spain'], DUTCH: ['Spanje'] },
  },
  EST: {
    ISO3_CODE: 'EST',
    ISO2_CODE: 'EE',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Estonia'], DUTCH: ['Estland'] },
  },
  ETH: {
    ISO3_CODE: 'ETH',
    ISO2_CODE: 'ET',
    CURRENCY: [{ NAME: ['Ethiopian birr'], CODE: ['ETB'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Ethiopia'], DUTCH: ['Ethiopië'] },
  },
  FIN: {
    ISO3_CODE: 'FIN',
    ISO2_CODE: 'FI',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Finland'], DUTCH: ['Finland'] },
  },
  FJI: {
    ISO3_CODE: 'FJI',
    ISO2_CODE: 'FJ',
    CURRENCY: [{ NAME: ['Fiji dollar'], CODE: ['FJD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Fiji'], DUTCH: ['Fiji'] },
  },
  FLK: {
    ISO3_CODE: 'FLK',
    ISO2_CODE: 'FK',
    CURRENCY: [{ NAME: ['Falkland Islands pound'], CODE: ['FKP'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Falkland Islands (Malvinas)'],
      DUTCH: ['Falkland Eilanden  (Malvinas)'],
    },
  },
  FRA: {
    ISO3_CODE: 'FRA',
    ISO2_CODE: 'FR',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['France'], DUTCH: ['Frankrijk'] },
  },
  FRO: {
    ISO3_CODE: 'FRO',
    ISO2_CODE: 'FO',
    CURRENCY: [{ NAME: ['Danish krone'], CODE: ['DKK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Faroe Islands'], DUTCH: ['Faeröer'] },
  },
  FSM: {
    ISO3_CODE: 'FSM',
    ISO2_CODE: 'FM',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Micronesia'], DUTCH: ['Micronesië'] },
  },
  GAB: {
    ISO3_CODE: 'GAB',
    ISO2_CODE: 'GA',
    CURRENCY: [{ NAME: ['CFA franc BEAC'], CODE: ['XAF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Gabon'], DUTCH: ['Gabon'] },
  },
  GBR: {
    ISO3_CODE: 'GBR',
    ISO2_CODE: 'GB',
    CURRENCY: [{ NAME: ['Pound sterling'], CODE: ['GBP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['United Kingdom'], DUTCH: ['Verenigd Koninkrijk'] },
  },
  GEO: {
    ISO3_CODE: 'GEO',
    ISO2_CODE: 'GE',
    CURRENCY: [{ NAME: ['Georgian lari'], CODE: ['GEL'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Georgia'], DUTCH: ['Georgië'] },
  },
  GGY: {
    ISO3_CODE: 'GGY',
    ISO2_CODE: 'GG',
    CURRENCY: [{ NAME: ['Pound sterling'], CODE: ['GBP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Guernsey'], DUTCH: ['Guernsey'] },
  },
  GHA: {
    ISO3_CODE: 'GHA',
    ISO2_CODE: 'GH',
    CURRENCY: [{ NAME: ['Ghanaian cedi'], CODE: ['GHS'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Ghana'], DUTCH: ['Ghana'] },
  },
  GIB: {
    ISO3_CODE: 'GIB',
    ISO2_CODE: 'GI',
    CURRENCY: [{ NAME: ['Gibraltar pound'], CODE: ['GIP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Gibraltar'], DUTCH: ['Gibraltar'] },
  },
  GIN: {
    ISO3_CODE: 'GIN',
    ISO2_CODE: 'GN',
    CURRENCY: [{ NAME: ['Guinean franc'], CODE: ['GNF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Guinea'], DUTCH: ['Guinea'] },
  },
  GLP: {
    ISO3_CODE: 'GLP',
    ISO2_CODE: 'GP',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Guadeloupe'], DUTCH: ['Guadeloupe'] },
  },
  GMB: {
    ISO3_CODE: 'GMB',
    ISO2_CODE: 'GM',
    CURRENCY: [{ NAME: ['Gambian dalasi'], CODE: ['GMD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Gambia'], DUTCH: ['Gambia'] },
  },
  GNB: {
    ISO3_CODE: 'GNB',
    ISO2_CODE: 'GW',
    CURRENCY: [{ NAME: ['CFA franc BCEAO'], CODE: ['XOF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Guinea-Bissau'], DUTCH: ['Guinee-Bissau'] },
  },
  GNQ: {
    ISO3_CODE: 'GNQ',
    ISO2_CODE: 'GQ',
    CURRENCY: [{ NAME: ['CFA franc BEAC'], CODE: ['XAF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Equatorial Guinea'], DUTCH: ['Equatoriaal-Guinea'] },
  },
  GRC: {
    ISO3_CODE: 'GRC',
    ISO2_CODE: 'GR',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Greece'], DUTCH: ['Griekenland'] },
  },
  GRD: {
    ISO3_CODE: 'GRD',
    ISO2_CODE: 'GD',
    CURRENCY: [{ NAME: ['East Caribbean dollar'], CODE: ['XCD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Grenada'], DUTCH: ['Grenada'] },
  },
  GRL: {
    ISO3_CODE: 'GRL',
    ISO2_CODE: 'GL',
    CURRENCY: [{ NAME: ['Danish krone'], CODE: ['DKK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Greenland'], DUTCH: ['Groenland'] },
  },
  GTM: {
    ISO3_CODE: 'GTM',
    ISO2_CODE: 'GT',
    CURRENCY: [{ NAME: ['Guatemalan quetzal'], CODE: ['GTQ'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Guatemala'], DUTCH: ['Guatemala'] },
  },
  GUF: {
    ISO3_CODE: 'GUF',
    ISO2_CODE: 'GF',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['French Guiana'], DUTCH: ['Frans Guyana'] },
  },
  GUM: {
    ISO3_CODE: 'GUM',
    ISO2_CODE: 'GU',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Guam'], DUTCH: ['Guam'] },
  },
  GUY: {
    ISO3_CODE: 'GUY',
    ISO2_CODE: 'GY',
    CURRENCY: [{ NAME: ['Guyanese dollar'], CODE: ['GYD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Guyana'], DUTCH: ['Guyana'] },
  },
  HKG: {
    ISO3_CODE: 'HKG',
    ISO2_CODE: 'HK',
    CURRENCY: [{ NAME: ['Hong Kong dollar'], CODE: ['HKD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Hong Kong'], DUTCH: ['Hong Kong'] },
  },
  HMD: {
    ISO3_CODE: 'HMD',
    ISO2_CODE: 'HM',
    CURRENCY: [{ NAME: ['Australian dollar'], CODE: ['AUD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Heard Island and McDonald Islands'],
      DUTCH: ['Heard Island en McDonald Islands'],
    },
  },
  HND: {
    ISO3_CODE: 'HND',
    ISO2_CODE: 'HN',
    CURRENCY: [{ NAME: ['Honduran lempira'], CODE: ['HNL'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Honduras'], DUTCH: ['Honduras'] },
  },
  HRV: {
    ISO3_CODE: 'HRV',
    ISO2_CODE: 'HR',
    CURRENCY: [{ NAME: ['Croatian Kuna'], CODE: ['HRK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Croatia'], DUTCH: ['Kroatië'] },
  },
  HTI: {
    ISO3_CODE: 'HTI',
    ISO2_CODE: 'HT',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Haiti'], DUTCH: ['Haïti'] },
  },
  HUN: {
    ISO3_CODE: 'HUN',
    ISO2_CODE: 'HU',
    CURRENCY: [{ NAME: ['Hungarian forint'], CODE: ['HUF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Hungary'], DUTCH: ['Hongarije'] },
  },
  IDN: {
    ISO3_CODE: 'IDN',
    ISO2_CODE: 'ID',
    CURRENCY: [{ NAME: ['Indonesian rupiah'], CODE: ['IDR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Indonesia'], DUTCH: ['Indonesië'] },
  },
  IMN: {
    ISO3_CODE: 'IMN',
    ISO2_CODE: 'IM',
    CURRENCY: [
      { NAME: ['Isle of Man pound also Manx pound'], CODE: ['IMP'], NUM: [] },
    ],
    LIST_OF_NAME: { ENG: ['Isle of Man'], DUTCH: ['Isle of Man'] },
  },
  IND: {
    ISO3_CODE: 'IND',
    ISO2_CODE: 'IN',
    CURRENCY: [{ NAME: ['Indian rupee'], CODE: ['INR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['India'], DUTCH: ['Indië'] },
  },
  IOT: {
    ISO3_CODE: 'IOT',
    ISO2_CODE: 'IO',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['British Indian Ocean Territory'],
      DUTCH: ['Brits-Indisch oceaan gebied'],
    },
  },
  IRL: {
    ISO3_CODE: 'IRL',
    ISO2_CODE: 'IE',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Ireland'], DUTCH: ['Ierland'] },
  },
  IRN: {
    ISO3_CODE: 'IRN',
    ISO2_CODE: 'IR',
    CURRENCY: [{ NAME: ['Iranian rial'], CODE: ['IRR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Iran'], DUTCH: ['Iran'] },
  },
  IRQ: {
    ISO3_CODE: 'IRQ',
    ISO2_CODE: 'IQ',
    CURRENCY: [{ NAME: ['Iraqi dinar'], CODE: ['IQD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Iraq'], DUTCH: ['Irak'] },
  },
  ISL: {
    ISO3_CODE: 'ISL',
    ISO2_CODE: 'IS',
    CURRENCY: [{ NAME: ['Icelandic króna'], CODE: ['ISK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Iceland'], DUTCH: ['IJsland'] },
  },
  ISR: {
    ISO3_CODE: 'ISR',
    ISO2_CODE: 'IL',
    CURRENCY: [{ NAME: ['Israeli new shekel'], CODE: ['ILS'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Israel'], DUTCH: ['Israël'] },
  },
  ITA: {
    ISO3_CODE: 'ITA',
    ISO2_CODE: 'IT',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Italy'], DUTCH: ['Italië'] },
  },
  JAM: {
    ISO3_CODE: 'JAM',
    ISO2_CODE: 'JM',
    CURRENCY: [{ NAME: ['Jamaican dollar'], CODE: ['JMD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Jamaica'], DUTCH: ['Jamaica'] },
  },
  JEY: {
    ISO3_CODE: 'JEY',
    ISO2_CODE: 'JE',
    CURRENCY: [{ NAME: ['Pound sterling'], CODE: ['GBP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Jersey'], DUTCH: ['Jersey'] },
  },
  JOR: {
    ISO3_CODE: 'JOR',
    ISO2_CODE: 'JO',
    CURRENCY: [{ NAME: ['Jordanian dinar'], CODE: ['JOD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Jordan'], DUTCH: ['Jordanië'] },
  },
  JPN: {
    ISO3_CODE: 'JPN',
    ISO2_CODE: 'JP',
    CURRENCY: [{ NAME: ['Japanese yen'], CODE: ['JPY'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Japan'], DUTCH: ['Japan'] },
  },
  KAZ: {
    ISO3_CODE: 'KAZ',
    ISO2_CODE: 'KZ',
    CURRENCY: [{ NAME: ['Kazakhstani tenge'], CODE: ['KZT'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Kazakhstan'], DUTCH: ['Kazachstan'] },
  },
  KEN: {
    ISO3_CODE: 'KEN',
    ISO2_CODE: 'KE',
    CURRENCY: [{ NAME: ['Kenyan shilling'], CODE: ['KES'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Kenya'], DUTCH: ['Kenia'] },
  },
  KGZ: {
    ISO3_CODE: 'KGZ',
    ISO2_CODE: 'KG',
    CURRENCY: [{ NAME: ['Kyrgyzstani som'], CODE: ['KGS'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Kyrgyzstan'], DUTCH: ['Kirgizië'] },
  },
  KHM: {
    ISO3_CODE: 'KHM',
    ISO2_CODE: 'KH',
    CURRENCY: [{ NAME: ['Cambodian riel'], CODE: ['KHR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Cambodia'], DUTCH: ['Cambodja'] },
  },
  KIR: {
    ISO3_CODE: 'KIR',
    ISO2_CODE: 'KI',
    CURRENCY: [{ NAME: ['Australian dollar'], CODE: ['AUD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Kiribati'], DUTCH: ['Kiribati'] },
  },
  KNA: {
    ISO3_CODE: 'KNA',
    ISO2_CODE: 'KN',
    CURRENCY: [{ NAME: ['East Caribbean dollar'], CODE: ['XCD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Saint Kitts and Nevis'],
      DUTCH: ['Saint Kitts en Nevis'],
    },
  },
  KOR: {
    ISO3_CODE: 'KOR',
    ISO2_CODE: 'KR',
    CURRENCY: [{ NAME: ['South Korean won'], CODE: ['KRW'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['South Korea', 'Korea Republic of'],
      DUTCH: ['Zuid-Korea', 'Korea Republic of'],
    },
  },
  KWT: {
    ISO3_CODE: 'KWT',
    ISO2_CODE: 'KW',
    CURRENCY: [{ NAME: ['Kuwaiti dinar'], CODE: ['KWD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Kuwait'], DUTCH: ['Koeweit'] },
  },
  LAO: {
    ISO3_CODE: 'LAO',
    ISO2_CODE: 'LA',
    CURRENCY: [{ NAME: ['Lao kip'], CODE: ['LAK'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Laos', "Lao People's Democratic Republic"],
      DUTCH: ['Laos', 'Lao Democratische Volksrepubliek'],
    },
  },
  LBN: {
    ISO3_CODE: 'LBN',
    ISO2_CODE: 'LB',
    CURRENCY: [{ NAME: ['Lebanese pound'], CODE: ['LBP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Lebanon'], DUTCH: ['Libanon'] },
  },
  LBR: {
    ISO3_CODE: 'LBR',
    ISO2_CODE: 'LR',
    CURRENCY: [{ NAME: ['Liberian dollar'], CODE: ['LRD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Liberia'], DUTCH: ['Liberia'] },
  },
  LBY: {
    ISO3_CODE: 'LBY',
    ISO2_CODE: 'LY',
    CURRENCY: [{ NAME: ['Libyan dinar'], CODE: ['LYD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Libya'], DUTCH: ['Libië'] },
  },
  LCA: {
    ISO3_CODE: 'LCA',
    ISO2_CODE: 'LC',
    CURRENCY: [{ NAME: ['East Caribbean dollar'], CODE: ['XCD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Saint Lucia'], DUTCH: ['Saint Lucia'] },
  },
  LIE: {
    ISO3_CODE: 'LIE',
    ISO2_CODE: 'LI',
    CURRENCY: [{ NAME: ['Swiss franc'], CODE: ['CHF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Liechtenstein'], DUTCH: ['Liechtenstein'] },
  },
  LKA: {
    ISO3_CODE: 'LKA',
    ISO2_CODE: 'LK',
    CURRENCY: [{ NAME: ['Sri Lankan rupee'], CODE: ['LKR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Sri Lanka'], DUTCH: ['Sri Lanka'] },
  },
  LSO: {
    ISO3_CODE: 'LSO',
    ISO2_CODE: 'LS',
    CURRENCY: [{ NAME: ['Lesotho loti'], CODE: ['LSL'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Lesotho'], DUTCH: ['Lesotho'] },
  },
  LTU: {
    ISO3_CODE: 'LTU',
    ISO2_CODE: 'LT',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Lithuania'], DUTCH: ['Litouwen'] },
  },
  LUX: {
    ISO3_CODE: 'LUX',
    ISO2_CODE: 'LU',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Luxembourg'], DUTCH: ['Luxemburg'] },
  },
  LVA: {
    ISO3_CODE: 'LVA',
    ISO2_CODE: 'LV',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Latvia'], DUTCH: ['Letland'] },
  },
  MAC: {
    ISO3_CODE: 'MAC',
    ISO2_CODE: 'MO',
    CURRENCY: [],
    LIST_OF_NAME: { ENG: ['Macao'], DUTCH: ['Macao'] },
  },
  MAF: {
    ISO3_CODE: 'MAF',
    ISO2_CODE: 'MF',
    CURRENCY: [],
    LIST_OF_NAME: {
      ENG: ['Saint Martin (French part)'],
      DUTCH: ['Saint Martin (Frans deel)'],
    },
  },
  MAR: {
    ISO3_CODE: 'MAR',
    ISO2_CODE: 'MA',
    CURRENCY: [{ NAME: ['Moroccan dirham'], CODE: ['MAD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Morocco'], DUTCH: ['Marokko'] },
  },
  MCO: {
    ISO3_CODE: 'MCO',
    ISO2_CODE: 'MC',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Monaco'], DUTCH: ['Monaco'] },
  },
  MDA: {
    ISO3_CODE: 'MDA',
    ISO2_CODE: 'MD',
    CURRENCY: [{ NAME: ['Moldovan leu'], CODE: ['MDL'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Moldova'], DUTCH: ['Moldavië'] },
  },
  MDG: {
    ISO3_CODE: 'MDG',
    ISO2_CODE: 'MG',
    CURRENCY: [{ NAME: ['Malagasy ariary'], CODE: ['MGA'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Madagascar'], DUTCH: ['Madagaskar'] },
  },
  MDV: {
    ISO3_CODE: 'MDV',
    ISO2_CODE: 'MV',
    CURRENCY: [{ NAME: ['Maldivian rufiyaa'], CODE: ['MVR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Maldives'], DUTCH: ['Maldiven'] },
  },
  MEX: {
    ISO3_CODE: 'MEX',
    ISO2_CODE: 'MX',
    CURRENCY: [{ NAME: ['Mexican peso'], CODE: ['MXN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Mexico'], DUTCH: ['Mexico'] },
  },
  MHL: {
    ISO3_CODE: 'MHL',
    ISO2_CODE: 'MH',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Marshall Islands'], DUTCH: ['Marshalleilanden'] },
  },
  MKD: {
    ISO3_CODE: 'MKD',
    ISO2_CODE: 'MK',
    CURRENCY: [{ NAME: ['Macedonian denar'], CODE: ['MKD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Macedonia'], DUTCH: ['Macedonië'] },
  },
  MLI: {
    ISO3_CODE: 'MLI',
    ISO2_CODE: 'ML',
    CURRENCY: [{ NAME: ['Somali shilling'], CODE: ['SOS'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Mali'], DUTCH: ['Mali'] },
  },
  MLT: {
    ISO3_CODE: 'MLT',
    ISO2_CODE: 'MT',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Malta'], DUTCH: ['Malta'] },
  },
  MMR: {
    ISO3_CODE: 'MMR',
    ISO2_CODE: 'MM',
    CURRENCY: [{ NAME: ['Myanmar kyat'], CODE: ['MMK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Myanmar'], DUTCH: ['Myanmar'] },
  },
  MNE: {
    ISO3_CODE: 'MNE',
    ISO2_CODE: 'ME',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Montenegro'], DUTCH: ['Montenegro'] },
  },
  MNG: {
    ISO3_CODE: 'MNG',
    ISO2_CODE: 'MN',
    CURRENCY: [{ NAME: ['Mongolian tögrög'], CODE: ['MNT'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Mongolia'], DUTCH: ['Mongolië'] },
  },
  MNP: {
    ISO3_CODE: 'MNP',
    ISO2_CODE: 'MP',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Northern Mariana Islands'],
      DUTCH: ['noordelijke Mariana eilanden'],
    },
  },
  MOZ: {
    ISO3_CODE: 'MOZ',
    ISO2_CODE: 'MZ',
    CURRENCY: [{ NAME: ['Mozambican metical'], CODE: ['MZN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Mozambique'], DUTCH: ['Mozambique'] },
  },
  MTQ: {
    ISO3_CODE: 'MTQ',
    ISO2_CODE: 'MQ',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Martinique'], DUTCH: ['Martinique'] },
  },
  MUS: {
    ISO3_CODE: 'MUS',
    ISO2_CODE: 'MU',
    CURRENCY: [{ NAME: ['Mauritian rupee'], CODE: ['MUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Mauritius'], DUTCH: ['Mauritius'] },
  },
  MWI: {
    ISO3_CODE: 'MWI',
    ISO2_CODE: 'MW',
    CURRENCY: [{ NAME: ['Malawian kwacha'], CODE: ['MWK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Malawi'], DUTCH: ['Malawi'] },
  },
  MYS: {
    ISO3_CODE: 'MYS',
    ISO2_CODE: 'MY',
    CURRENCY: [{ NAME: ['Malaysian ringgit'], CODE: ['MYR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Malaysia'], DUTCH: ['Maleisië'] },
  },
  MYT: {
    ISO3_CODE: 'MYT',
    ISO2_CODE: 'YT',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Mayotte'], DUTCH: ['Mayotte'] },
  },
  NAM: {
    ISO3_CODE: 'NAM',
    ISO2_CODE: 'NA',
    CURRENCY: [{ NAME: ['Namibian dollar'], CODE: ['NAD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Namibia'], DUTCH: ['Namibië'] },
  },
  NCL: {
    ISO3_CODE: 'NCL',
    ISO2_CODE: 'NC',
    CURRENCY: [
      { NAME: ['CFP franc (franc Pacifique)'], CODE: ['XPF'], NUM: [] },
    ],
    LIST_OF_NAME: { ENG: ['New Caledonia'], DUTCH: ['Nieuw-Caledonië'] },
  },
  NER: {
    ISO3_CODE: 'NER',
    ISO2_CODE: 'NE',
    CURRENCY: [{ NAME: ['CFA franc BCEAO'], CODE: ['XOF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Niger'], DUTCH: ['Niger'] },
  },
  NFK: {
    ISO3_CODE: 'NFK',
    ISO2_CODE: 'NF',
    CURRENCY: [{ NAME: ['Australian dollar'], CODE: ['AUD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Norfolk Island'], DUTCH: ['Norfolk Island'] },
  },
  NGA: {
    ISO3_CODE: 'NGA',
    ISO2_CODE: 'NG',
    CURRENCY: [{ NAME: ['Nigerian naira'], CODE: ['NGN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Nigeria'], DUTCH: ['Nigeria'] },
  },
  NIC: {
    ISO3_CODE: 'NIC',
    ISO2_CODE: 'NI',
    CURRENCY: [{ NAME: ['Nicaraguan córdoba'], CODE: ['NIO'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Nicaragua'], DUTCH: ['Nicaragua'] },
  },
  NIU: {
    ISO3_CODE: 'NIU',
    ISO2_CODE: 'NU',
    CURRENCY: [{ NAME: ['New Zealand dollar'], CODE: ['NZD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Niue'], DUTCH: ['Niue'] },
  },
  NLD: {
    ISO3_CODE: 'NLD',
    ISO2_CODE: 'NL',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Netherlands'], DUTCH: ['Nederland'] },
  },
  NOR: {
    ISO3_CODE: 'NOR',
    ISO2_CODE: 'NO',
    CURRENCY: [{ NAME: ['Norwegian krone'], CODE: ['NOK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Norway'], DUTCH: ['Noorwegen'] },
  },
  NPL: {
    ISO3_CODE: 'NPL',
    ISO2_CODE: 'NP',
    CURRENCY: [{ NAME: ['Nepalese rupee'], CODE: ['NPR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Nepal'], DUTCH: ['Nepal'] },
  },
  NRU: {
    ISO3_CODE: 'NRU',
    ISO2_CODE: 'NR',
    CURRENCY: [{ NAME: ['Australian dollar'], CODE: ['AUD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Nauru'], DUTCH: ['Nauru'] },
  },
  NZL: {
    ISO3_CODE: 'NZL',
    ISO2_CODE: 'NZ',
    CURRENCY: [{ NAME: ['New Zealand dollar'], CODE: ['NZD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['New Zealand'], DUTCH: ['Nieuw-Zeeland'] },
  },
  OMN: {
    ISO3_CODE: 'OMN',
    ISO2_CODE: 'OM',
    CURRENCY: [{ NAME: ['Omani rial'], CODE: ['OMR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Oman'], DUTCH: ['Oman'] },
  },
  PAK: {
    ISO3_CODE: 'PAK',
    ISO2_CODE: 'PK',
    CURRENCY: [{ NAME: ['Pakistani rupee'], CODE: ['PKR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Pakistan'], DUTCH: ['Pakistan'] },
  },
  PAN: {
    ISO3_CODE: 'PAN',
    ISO2_CODE: 'PA',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Panama'], DUTCH: ['Panama'] },
  },
  PCN: {
    ISO3_CODE: 'PCN',
    ISO2_CODE: 'PN',
    CURRENCY: [{ NAME: ['New Zealand dollar'], CODE: ['NZD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Pitcairn'], DUTCH: ['Pitcairn'] },
  },
  PER: {
    ISO3_CODE: 'PER',
    ISO2_CODE: 'PE',
    CURRENCY: [{ NAME: ['Peruvian sol'], CODE: ['PEN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Peru'], DUTCH: ['Peru'] },
  },
  PHL: {
    ISO3_CODE: 'PHL',
    ISO2_CODE: 'PH',
    CURRENCY: [{ NAME: ['Philippine peso'], CODE: ['PHP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Philippines'], DUTCH: ['Filipijnen'] },
  },
  PLW: {
    ISO3_CODE: 'PLW',
    ISO2_CODE: 'PW',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Palau'], DUTCH: ['Palau'] },
  },
  PNG: {
    ISO3_CODE: 'PNG',
    ISO2_CODE: 'PG',
    CURRENCY: [{ NAME: ['Papua New Guinean kina'], CODE: ['PGK'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Papua New Guinea'],
      DUTCH: ['Papoea-Nieuw-Guinea '],
    },
  },
  POL: {
    ISO3_CODE: 'POL',
    ISO2_CODE: 'PL',
    CURRENCY: [{ NAME: ['Polish złoty'], CODE: ['PLN'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Poland'], DUTCH: ['Polen'] },
  },
  PRI: {
    ISO3_CODE: 'PRI',
    ISO2_CODE: 'PR',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Puerto Rico'], DUTCH: ['Puerto Rico'] },
  },
  PRK: {
    ISO3_CODE: 'PRK',
    ISO2_CODE: 'KP',
    CURRENCY: [{ NAME: ['North Korean won'], CODE: ['KPW'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['North Korea', "Korea Democratic People's Republic of"],
      DUTCH: ['Noord-Korea', 'Korea, Democratische Volksrepubliek'],
    },
  },
  PRT: {
    ISO3_CODE: 'PRT',
    ISO2_CODE: 'PT',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Portugal'], DUTCH: ['Portugal'] },
  },
  PRY: {
    ISO3_CODE: 'PRY',
    ISO2_CODE: 'PY',
    CURRENCY: [{ NAME: ['Paraguayan guaraní'], CODE: ['PYG'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Paraguay'], DUTCH: ['Paraguay'] },
  },
  PSE: {
    ISO3_CODE: 'PSE',
    ISO2_CODE: 'PS',
    CURRENCY: [{ NAME: ['Egyptian Pound'], CODE: ['EGP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Palestine'], DUTCH: ['Palestina'] },
  },
  PYF: {
    ISO3_CODE: 'PYF',
    ISO2_CODE: 'PF',
    CURRENCY: [
      { NAME: ['CFP franc (franc Pacifique)'], CODE: ['XPF'], NUM: [] },
    ],
    LIST_OF_NAME: { ENG: ['French Polynesia'], DUTCH: ['Frans-Polynesië'] },
  },
  QAT: {
    ISO3_CODE: 'QAT',
    ISO2_CODE: 'QA',
    CURRENCY: [{ NAME: ['Qatari riyal'], CODE: ['QAR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Qatar'], DUTCH: ['Qatar'] },
  },
  REU: {
    ISO3_CODE: 'REU',
    ISO2_CODE: 'RE',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Reunion'], DUTCH: ['Bijeenkomst'] },
  },
  ROU: {
    ISO3_CODE: 'ROU',
    ISO2_CODE: 'RO',
    CURRENCY: [{ NAME: ['Romanian leu'], CODE: ['RON'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Romania'], DUTCH: ['Roemenië'] },
  },
  RUS: {
    ISO3_CODE: 'RUS',
    ISO2_CODE: 'RU',
    CURRENCY: [{ NAME: ['Russian ruble'], CODE: ['RUB'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Russian Federation'],
      DUTCH: ['Russische Federatie'],
    },
  },
  RWA: {
    ISO3_CODE: 'RWA',
    ISO2_CODE: 'RW',
    CURRENCY: [{ NAME: ['Rwandan franc'], CODE: ['RWF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Rwanda'], DUTCH: ['Rwanda'] },
  },
  SAU: {
    ISO3_CODE: 'SAU',
    ISO2_CODE: 'SA',
    CURRENCY: [{ NAME: ['Saudi riyal'], CODE: ['SAR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Saudi Arabia'], DUTCH: ['Saoedi-Arabië'] },
  },
  SDN: {
    ISO3_CODE: 'SDN',
    ISO2_CODE: 'SD',
    CURRENCY: [{ NAME: ['Sudanese pound'], CODE: ['SDG'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Sudan'], DUTCH: ['Soedan'] },
  },
  SEN: {
    ISO3_CODE: 'SEN',
    ISO2_CODE: 'SN',
    CURRENCY: [{ NAME: ['CFA franc BCEAO'], CODE: ['XOF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Senegal'], DUTCH: ['Senegal'] },
  },
  SGP: {
    ISO3_CODE: 'SGP',
    ISO2_CODE: 'SG',
    CURRENCY: [{ NAME: ['Singapore dollar'], CODE: ['SGD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Singapore'], DUTCH: ['Singapore'] },
  },
  SGS: {
    ISO3_CODE: 'SGS',
    ISO2_CODE: 'GS',
    CURRENCY: [],
    LIST_OF_NAME: {
      ENG: ['South Georgia and the South Sandwich Islands'],
      DUTCH: ['South Georgia en de South Sandwich Islands'],
    },
  },
  SHN: {
    ISO3_CODE: 'SHN',
    ISO2_CODE: 'SH',
    CURRENCY: [],
    LIST_OF_NAME: { ENG: ['Saint Helena'], DUTCH: ['Sint Helena'] },
  },
  SJM: {
    ISO3_CODE: 'SJM',
    ISO2_CODE: 'SJ',
    CURRENCY: [{ NAME: ['Svalbard and Jan Mayen'], CODE: ['NOK'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Svalbard and Jan Mayen'],
      DUTCH: ['Svalbard en Jan Mayen'],
    },
  },
  SLB: {
    ISO3_CODE: 'SLB',
    ISO2_CODE: 'SB',
    CURRENCY: [{ NAME: ['Solomon Islands dollar'], CODE: ['SBD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Solomon Islands'], DUTCH: ['Salomonseilanden'] },
  },
  SLE: {
    ISO3_CODE: 'SLE',
    ISO2_CODE: 'SL',
    CURRENCY: [{ NAME: ['Sierra Leonean leone'], CODE: ['SLL'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Sierra Leone'], DUTCH: ['Sierra Leone'] },
  },
  SLV: {
    ISO3_CODE: 'SLV',
    ISO2_CODE: 'SV',
    CURRENCY: [{ NAME: ['Salvadoran colón'], CODE: ['SVC'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['El Salvador'], DUTCH: ['El Salvador'] },
  },
  SMR: {
    ISO3_CODE: 'SMR',
    ISO2_CODE: 'SM',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['San Marino'], DUTCH: ['San Marino'] },
  },
  SOM: {
    ISO3_CODE: 'SOM',
    ISO2_CODE: 'SO',
    CURRENCY: [{ NAME: ['Somali shilling'], CODE: ['SOS'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Somalia'], DUTCH: ['Somalië'] },
  },
  SPM: {
    ISO3_CODE: 'SPM',
    ISO2_CODE: 'PM',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Saint Pierre and Miquelon'],
      DUTCH: ['Saint Pierre en Miquelon'],
    },
  },
  SRB: {
    ISO3_CODE: 'SRB',
    ISO2_CODE: 'RS',
    CURRENCY: [{ NAME: ['Serbian dinar'], CODE: ['RSD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Serbia'], DUTCH: ['Servië'] },
  },
  SSD: {
    ISO3_CODE: 'SSD',
    ISO2_CODE: 'SS',
    CURRENCY: [{ NAME: ['South Sudanese pound'], CODE: ['SSP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['South Sudan'], DUTCH: ['Zuid-Soedan'] },
  },
  STP: {
    ISO3_CODE: 'STP',
    ISO2_CODE: 'ST',
    CURRENCY: [
      { NAME: ['São Tomé and Príncipe dobra'], CODE: ['STN'], NUM: [] },
    ],
    LIST_OF_NAME: {
      ENG: ['Sao Tome and Principe'],
      DUTCH: ['Sao Tomé en Principe'],
    },
  },
  SUR: {
    ISO3_CODE: 'SUR',
    ISO2_CODE: 'SR',
    CURRENCY: [{ NAME: ['Surinamese dollar'], CODE: ['SRD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Suriname'], DUTCH: ['Suriname'] },
  },
  SVK: {
    ISO3_CODE: 'SVK',
    ISO2_CODE: 'SK',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Slovakia'], DUTCH: ['Slowakije'] },
  },
  SVN: {
    ISO3_CODE: 'SVN',
    ISO2_CODE: 'SI',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Slovenia'], DUTCH: ['Slovenië'] },
  },
  SWE: {
    ISO3_CODE: 'SWE',
    ISO2_CODE: 'SE',
    CURRENCY: [{ NAME: ['Swedish krona/kronor'], CODE: ['SEK'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Sweden'], DUTCH: ['Zweden'] },
  },
  SWZ: {
    ISO3_CODE: 'SWZ',
    ISO2_CODE: 'SZ',
    CURRENCY: [{ NAME: ['Swazi lilangeni'], CODE: ['SZL'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Eswatini'], DUTCH: ['Eswatini'] },
  },
  SXM: {
    ISO3_CODE: 'SXM',
    ISO2_CODE: 'SX',
    CURRENCY: [
      { NAME: ['Netherlands Antillean guilder'], CODE: ['ANG'], NUM: [] },
    ],
    LIST_OF_NAME: {
      ENG: ['Sint Maarten (Dutch part)'],
      DUTCH: ['Sint Maarten (Nederlands deel)'],
    },
  },
  SYC: {
    ISO3_CODE: 'SYC',
    ISO2_CODE: 'SC',
    CURRENCY: [{ NAME: ['Seychelles rupee'], CODE: ['SCR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Seychelles'], DUTCH: ['Seychellen'] },
  },
  SYR: {
    ISO3_CODE: 'SYR',
    ISO2_CODE: 'SY',
    CURRENCY: [{ NAME: ['Syrian pound'], CODE: ['SYP'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Syrian Arab Republic'],
      DUTCH: ['Syrische Arabische Republiek'],
    },
  },
  TCA: {
    ISO3_CODE: 'TCA',
    ISO2_CODE: 'TC',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Turks and Caicos Islands'],
      DUTCH: ['Turks- en Caicoseilanden'],
    },
  },
  TCD: {
    ISO3_CODE: 'TCD',
    ISO2_CODE: 'TD',
    CURRENCY: [{ NAME: ['CFA franc BEAC'], CODE: ['XAF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Chad'], DUTCH: ['Tsjaad'] },
  },
  TGO: {
    ISO3_CODE: 'TGO',
    ISO2_CODE: 'TG',
    CURRENCY: [{ NAME: ['CFA franc BCEAO'], CODE: ['XOF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Togo'], DUTCH: ['Togo'] },
  },
  THA: {
    ISO3_CODE: 'THA',
    ISO2_CODE: 'TH',
    CURRENCY: [{ NAME: ['Thai baht'], CODE: ['THB'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Thailand'], DUTCH: ['Thailand'] },
  },
  TJK: {
    ISO3_CODE: 'TJK',
    ISO2_CODE: 'TJ',
    CURRENCY: [{ NAME: ['Tajikistani somoni'], CODE: ['TJS'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Tajikistan'], DUTCH: ['Tadzjikistan'] },
  },
  TKL: {
    ISO3_CODE: 'TKL',
    ISO2_CODE: 'TK',
    CURRENCY: [{ NAME: ['New Zealand dollar'], CODE: ['NZD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Tokelau'], DUTCH: ['Tokelau'] },
  },
  TKM: {
    ISO3_CODE: 'TKM',
    ISO2_CODE: 'TM',
    CURRENCY: [{ NAME: ['Turkmenistan manat'], CODE: ['TMT'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Turkmenistan'], DUTCH: ['Turkmenistan'] },
  },
  TLS: {
    ISO3_CODE: 'TLS',
    ISO2_CODE: 'TL',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Timor-Leste'], DUTCH: ['Timor-Leste'] },
  },
  TON: {
    ISO3_CODE: 'TON',
    ISO2_CODE: 'TO',
    CURRENCY: [{ NAME: ['Tongan paʻanga'], CODE: ['TOP'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Tonga'], DUTCH: ['Tonga'] },
  },
  TTO: {
    ISO3_CODE: 'TTO',
    ISO2_CODE: 'TT',
    CURRENCY: [
      { NAME: ['Trinidad and Tobago dollar'], CODE: ['TTD'], NUM: [] },
    ],
    LIST_OF_NAME: {
      ENG: ['Trinidad and Tobago'],
      DUTCH: ['Trinidad en Tobago'],
    },
  },
  TUN: {
    ISO3_CODE: 'TUN',
    ISO2_CODE: 'TN',
    CURRENCY: [{ NAME: ['Tunisian dinar'], CODE: ['TND'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Tunisia'], DUTCH: ['Tunesië'] },
  },
  TUR: {
    ISO3_CODE: 'TUR',
    ISO2_CODE: 'TR',
    CURRENCY: [{ NAME: ['Turkish lira'], CODE: ['TRY'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Turkey'], DUTCH: ['Turkije'] },
  },
  TUV: {
    ISO3_CODE: 'TUV',
    ISO2_CODE: 'TV',
    CURRENCY: [{ NAME: ['Australian dollar'], CODE: ['AUD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Tuvalu'], DUTCH: ['Tuvalu'] },
  },
  TWN: {
    ISO3_CODE: 'TWN',
    ISO2_CODE: 'TW',
    CURRENCY: [{ NAME: ['New Taiwan dollar'], CODE: ['TWD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Taiwan'], DUTCH: ['Taiwan'] },
  },
  TZA: {
    ISO3_CODE: 'TZA',
    ISO2_CODE: 'TZ',
    CURRENCY: [{ NAME: ['Tanzanian shilling'], CODE: ['TZS'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Tanzania'], DUTCH: ['Tanzania'] },
  },
  UGA: {
    ISO3_CODE: 'UGA',
    ISO2_CODE: 'UG',
    CURRENCY: [{ NAME: ['Ugandan shilling'], CODE: ['UGX'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Uganda'], DUTCH: ['Oeganda'] },
  },
  UKR: {
    ISO3_CODE: 'UKR',
    ISO2_CODE: 'UA',
    CURRENCY: [{ NAME: ['Hryvnia'], CODE: ['UAH'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Ukraine'], DUTCH: ['Oekraïne'] },
  },
  UMI: {
    ISO3_CODE: 'UMI',
    ISO2_CODE: 'UM',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['United States Minor Outlying Islands'],
      DUTCH: ['Kleine afgelegen eilanden van de Verenigde Staten'],
    },
  },
  URY: {
    ISO3_CODE: 'URY',
    ISO2_CODE: 'UY',
    CURRENCY: [{ NAME: ['Uruguayan peso'], CODE: ['UYU'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Uruguay'], DUTCH: ['Uruguay'] },
  },
  USA: {
    ISO3_CODE: 'USA',
    ISO2_CODE: 'US',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['United States of America'],
      DUTCH: ['Verenigde Staten '],
    },
  },
  UZB: {
    ISO3_CODE: 'UZB',
    ISO2_CODE: 'UZ',
    CURRENCY: [{ NAME: ['Uzbekistan som'], CODE: ['UZS'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Uzbekistan'], DUTCH: ['Oezbekistan'] },
  },
  VAT: {
    ISO3_CODE: 'VAT',
    ISO2_CODE: 'VA',
    CURRENCY: [{ NAME: ['Euro'], CODE: ['EUR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Holy See'], DUTCH: ['Heilige Stoel'] },
  },
  VCT: {
    ISO3_CODE: 'VCT',
    ISO2_CODE: 'VC',
    CURRENCY: [{ NAME: ['East Caribbean dollar'], CODE: ['XCD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['Saint Vincent and the Grenadines'],
      DUTCH: ['Saint Vincent en de Grenadines'],
    },
  },
  VEN: {
    ISO3_CODE: 'VEN',
    ISO2_CODE: 'VE',
    CURRENCY: [
      { NAME: ['Venezuelan bolívar soberano'], CODE: ['VES'], NUM: [] },
    ],
    LIST_OF_NAME: { ENG: ['Venezuela'], DUTCH: ['Venezuela'] },
  },
  VGB: {
    ISO3_CODE: 'VGB',
    ISO2_CODE: 'VG',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: {
      ENG: ['British Virgin Islands'],
      DUTCH: ['Britse Maagdeneilanden'],
    },
  },
  VIR: {
    ISO3_CODE: 'VIR',
    ISO2_CODE: 'VI',
    CURRENCY: [{ NAME: ['United States dollar'], CODE: ['USD'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Virgin Islands, US'], DUTCH: ['maagden Eilanden'] },
  },
  VNM: {
    ISO3_CODE: 'VNM',
    ISO2_CODE: 'VN',
    CURRENCY: [{ NAME: ['Vietnamese dong'], CODE: ['VND'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['VietNam'], DUTCH: ['VietNam'] },
  },
  VUT: {
    ISO3_CODE: 'VUT',
    ISO2_CODE: 'VU',
    CURRENCY: [{ NAME: ['Vanuatu vatu'], CODE: ['VUV'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Vanuatu'], DUTCH: ['Vanuatu'] },
  },
  WLF: {
    ISO3_CODE: 'WLF',
    ISO2_CODE: 'WF',
    CURRENCY: [{ NAME: ['CFP franc'], CODE: ['XPF'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Wallis and Futuna'], DUTCH: ['Wallis en Futuna'] },
  },
  WSM: {
    ISO3_CODE: 'WSM',
    ISO2_CODE: 'WS',
    CURRENCY: [{ NAME: ['Samoan tala'], CODE: ['WST'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Samoa'], DUTCH: ['Samoa'] },
  },
  YEM: {
    ISO3_CODE: 'YEM',
    ISO2_CODE: 'YE',
    CURRENCY: [{ NAME: ['Yemeni rial'], CODE: ['YER'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Yemen'], DUTCH: ['Jemen'] },
  },
  ZAF: {
    ISO3_CODE: 'ZAF',
    ISO2_CODE: 'ZA',
    CURRENCY: [{ NAME: ['South African rand'], CODE: ['ZAR'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['South Africa'], DUTCH: ['Zuid-Afrika'] },
  },
  ZMB: {
    ISO3_CODE: 'ZMB',
    ISO2_CODE: 'ZM',
    CURRENCY: [{ NAME: ['Zambian kwacha'], CODE: ['ZMW'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Zambia'], DUTCH: ['Zambia'] },
  },
  ZWE: {
    ISO3_CODE: 'ZWE',
    ISO2_CODE: 'ZW',
    CURRENCY: [{ NAME: ['Zimbabwean dollar'], CODE: ['ZWL'], NUM: [] }],
    LIST_OF_NAME: { ENG: ['Zimbabwe'], DUTCH: ['Zimbabwe'] },
  },
};

export function findCountry(E: string, O: string = 'ENG'): Country | undefined {
  const country = Object.values(countries).find((C) => {
    return C.LIST_OF_NAME[O as keyof typeof C.LIST_OF_NAME].find(
      (C) => C === E,
    );
  });

  if (!country) {
    return;
  }

  return country;
}
