import {
  excelBetaDist,
  excelBetaInv,
  excelBinomDist,
  excelBinomDistRange,
  excelBinomInv,
  excelChisqDist,
  excelChisqDistRt,
  excelChisqInv,
  excelChisqInvRt,
  excelChisqTest,
  excelConfidenceNorm,
  excelConfidenceT,
  excelExponDist,
  excelFDist,
  excelFDistRt,
  excelFInv,
  excelFInvRt,
  excelFTest,
  excelGamma,
  excelGammaDist,
  excelGammaInv,
  excelGammaln,
  excelGauss,
  excelHypgeomDist,
  excelLognormDist,
  excelLognormInv,
  excelNegbinomDist,
  excelNormDist,
  excelNormInv,
  excelNormSDist,
  excelNormSInv,
  excelPhi,
  excelPoissonDist,
  excelStandardize,
  excelTDist,
  excelTDist2T,
  excelTDistRt,
  excelTInv,
  excelTInv2T,
  excelTTest,
  excelWeibullDist,
  excelZTest,
} from '../../formulajs/statistical.js';
import { BareNativeFilter, wrapBareNativeFilters } from '../../jqtools/evaluate/filters/lib/nativeFilter.js';

const bareNativeFilters: Record<string, BareNativeFilter> = {
  *'BETA_DIST/4'(_input, x, alpha, beta, cumulative) { yield excelBetaDist(x, alpha, beta, cumulative); },
  *'BETA_DIST/5'(_input, x, alpha, beta, cumulative, a) { yield excelBetaDist(x, alpha, beta, cumulative, a); },
  *'BETA_DIST/6'(_input, x, alpha, beta, cumulative, a, b) { yield excelBetaDist(x, alpha, beta, cumulative, a, b); },
  *'BETA_INV/3'(_input, probability, alpha, beta) { yield excelBetaInv(probability, alpha, beta); },
  *'BETA_INV/4'(_input, probability, alpha, beta, a) { yield excelBetaInv(probability, alpha, beta, a); },
  *'BETA_INV/5'(_input, probability, alpha, beta, a, b) { yield excelBetaInv(probability, alpha, beta, a, b); },
  *'BINOM_DIST/4'(_input, numberS, trials, probabilityS, cumulative) { yield excelBinomDist(numberS, trials, probabilityS, cumulative); },
  *'BINOM_DIST_RANGE/3'(_input, trials, probabilityS, numberS) { yield excelBinomDistRange(trials, probabilityS, numberS); },
  *'BINOM_DIST_RANGE/4'(_input, trials, probabilityS, numberS, numberS2) { yield excelBinomDistRange(trials, probabilityS, numberS, numberS2); },
  *'BINOM_INV/3'(_input, trials, probabilityS, alpha) { yield excelBinomInv(trials, probabilityS, alpha); },
  *'CHISQ_DIST/3'(_input, x, degFreedom, cumulative) { yield excelChisqDist(x, degFreedom, cumulative); },
  *'CHISQ_DIST_RT/2'(_input, x, degFreedom) { yield excelChisqDistRt(x, degFreedom); },
  *'CHISQ_INV/2'(_input, probability, degFreedom) { yield excelChisqInv(probability, degFreedom); },
  *'CHISQ_INV_RT/2'(_input, probability, degFreedom) { yield excelChisqInvRt(probability, degFreedom); },
  *'CHISQ_TEST/2'(_input, actual, expected) { yield excelChisqTest(actual, expected); },
  *'CONFIDENCE_NORM/3'(_input, alpha, standardDev, size) { yield excelConfidenceNorm(alpha, standardDev, size); },
  *'CONFIDENCE_T/3'(_input, alpha, standardDev, size) { yield excelConfidenceT(alpha, standardDev, size); },
  *'EXPON_DIST/3'(_input, x, lambda, cumulative) { yield excelExponDist(x, lambda, cumulative); },
  *'F_DIST/4'(_input, x, degFreedom1, degFreedom2, cumulative) { yield excelFDist(x, degFreedom1, degFreedom2, cumulative); },
  *'F_DIST_RT/3'(_input, x, degFreedom1, degFreedom2) { yield excelFDistRt(x, degFreedom1, degFreedom2); },
  *'F_INV/3'(_input, probability, degFreedom1, degFreedom2) { yield excelFInv(probability, degFreedom1, degFreedom2); },
  *'F_INV_RT/3'(_input, probability, degFreedom1, degFreedom2) { yield excelFInvRt(probability, degFreedom1, degFreedom2); },
  *'F_TEST/2'(_input, array1, array2) { yield excelFTest(array1, array2); },
  *'GAMMA/1'(_input, value) { yield excelGamma(value); },
  *'GAMMA_DIST/4'(_input, value, alpha, beta, cumulative) { yield excelGammaDist(value, alpha, beta, cumulative); },
  *'GAMMA_INV/3'(_input, probability, alpha, beta) { yield excelGammaInv(probability, alpha, beta); },
  *'GAMMALN/1'(_input, value) { yield excelGammaln(value); },
  *'GAMMALN_PRECISE/1'(_input, value) { yield excelGammaln(value); },
  *'GAUSS/1'(_input, z) { yield excelGauss(z); },
  *'HYPGEOM_DIST/5'(_input, sampleS, numberSample, populationS, numberPop, cumulative) { yield excelHypgeomDist(sampleS, numberSample, populationS, numberPop, cumulative); },
  *'LOGNORM_DIST/4'(_input, x, mean, standardDev, cumulative) { yield excelLognormDist(x, mean, standardDev, cumulative); },
  *'LOGNORM_INV/3'(_input, probability, mean, standardDev) { yield excelLognormInv(probability, mean, standardDev); },
  *'NEGBINOM_DIST/4'(_input, numberF, numberS, probabilityS, cumulative) { yield excelNegbinomDist(numberF, numberS, probabilityS, cumulative); },
  *'NORM_DIST/4'(_input, x, mean, standardDev, cumulative) { yield excelNormDist(x, mean, standardDev, cumulative); },
  *'NORM_INV/3'(_input, probability, mean, standardDev) { yield excelNormInv(probability, mean, standardDev); },
  *'NORM_S_DIST/2'(_input, z, cumulative) { yield excelNormSDist(z, cumulative); },
  *'NORM_S_INV/1'(_input, probability) { yield excelNormSInv(probability); },
  *'PHI/1'(_input, x) { yield excelPhi(x); },
  *'POISSON_DIST/3'(_input, x, mean, cumulative) { yield excelPoissonDist(x, mean, cumulative); },
  *'STANDARDIZE/3'(_input, x, mean, standardDev) { yield excelStandardize(x, mean, standardDev); },
  *'T_DIST/3'(_input, x, degFreedom, cumulative) { yield excelTDist(x, degFreedom, cumulative); },
  *'T_DIST_2T/2'(_input, x, degFreedom) { yield excelTDist2T(x, degFreedom); },
  *'T_DIST_RT/2'(_input, x, degFreedom) { yield excelTDistRt(x, degFreedom); },
  *'T_INV/2'(_input, probability, degFreedom) { yield excelTInv(probability, degFreedom); },
  *'T_INV_2T/2'(_input, probability, degFreedom) { yield excelTInv2T(probability, degFreedom); },
  *'T_TEST/2'(_input, array1, array2) { yield excelTTest(array1, array2); },
  *'WEIBULL_DIST/4'(_input, x, alpha, beta, cumulative) { yield excelWeibullDist(x, alpha, beta, cumulative); },
  *'Z_TEST/2'(_input, array, x) { yield excelZTest(array, x); },
  *'Z_TEST/3'(_input, array, x, sigma) { yield excelZTest(array, x, sigma); },
};

export const formulaStatisticalNativeFilters =
  wrapBareNativeFilters(bareNativeFilters);
