name: Init
description: Setup common dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # 4.3.0
      with:
        node-version-file: "package.json"

    - uses: cardstack/gh-actions/setup-pnpm-volta@main

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path -s)" >> $GITHUB_OUTPUT

    - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # 4.2.2
      name: Setup pnpm cache
      id: cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Prune pnpm store
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: pnpm store prune
