import {
  ensureDirSync,
  readFileSync,
  writeFileSync,
  copyFileSync,
} from 'fs-extra';
import { basename, dirname, join, relative } from 'path';
import { glob } from 'glob';
import ts from 'typescript';

const projectRoot = join(__dirname, '..', '..');
const sourceRoot = join(projectRoot, 'tests');
const targetRoot = join(projectRoot, 'tests-vitest');
const generatedHeader =
  '// AUTO-GENERATED by scripts/codemods/qunit-to-vitest.ts. Run codemod again instead of editing by hand.\n';

type TransformResult = {
  code: string;
  needsVitestHookImport: boolean;
  needsDirnamePolyfill: boolean;
  needsFilenamePolyfill: boolean;
  unsupportedCalls: string[];
};

function callText(node: ts.CallExpression, sourceFile: ts.SourceFile): string {
  return node.getText(sourceFile).replace(/\s+/g, ' ');
}

function isBasenameFilenameCall(node: ts.Expression): boolean {
  return (
    ts.isCallExpression(node) &&
    ts.isIdentifier(node.expression) &&
    node.expression.text === 'basename' &&
    node.arguments.length === 1 &&
    ts.isIdentifier(node.arguments[0]) &&
    node.arguments[0].text === '__filename'
  );
}

function replaceBasenameFilenameArg(
  node: ts.Expression,
  fileNameLiteral: string,
): ts.Expression {
  if (isBasenameFilenameCall(node)) {
    return ts.factory.createStringLiteral(fileNameLiteral);
  }
  if (ts.isTemplateExpression(node)) {
    let value = node.head.text;
    for (let span of node.templateSpans) {
      if (!isBasenameFilenameCall(span.expression)) {
        return node;
      }
      value += fileNameLiteral + span.literal.text;
    }
    return ts.factory.createStringLiteral(value);
  }
  return node;
}

function convertAssertCall(
  method: string,
  node: ts.CallExpression,
): ts.CallExpression | undefined {
  let args = [...node.arguments];
  let expectCall = (value: ts.Expression) =>
    ts.factory.createCallExpression(
      ts.factory.createIdentifier('expect'),
      undefined,
      [value],
    );

  switch (method) {
    case 'strictEqual':
      if (args.length >= 2) {
        return ts.factory.createCallExpression(
          ts.factory.createPropertyAccessExpression(
            expectCall(args[0]),
            'toBe',
          ),
          undefined,
          [args[1]],
        );
      }
      return undefined;
    case 'notStrictEqual':
      if (args.length >= 2) {
        return ts.factory.createCallExpression(
          ts.factory.createPropertyAccessExpression(
            ts.factory.createPropertyAccessExpression(
              expectCall(args[0]),
              'not',
            ),
            'toBe',
          ),
          undefined,
          [args[1]],
        );
      }
      return undefined;
    case 'deepEqual':
      if (args.length >= 2) {
        return ts.factory.createCallExpression(
          ts.factory.createPropertyAccessExpression(
            expectCall(args[0]),
            'toEqual',
          ),
          undefined,
          [args[1]],
        );
      }
      return undefined;
    case 'notEqual':
      if (args.length >= 2) {
        return ts.factory.createCallExpression(
          ts.factory.createPropertyAccessExpression(
            ts.factory.createPropertyAccessExpression(
              expectCall(args[0]),
              'not',
            ),
            'toEqual',
          ),
          undefined,
          [args[1]],
        );
      }
      return undefined;
    case 'ok':
      if (args.length >= 1) {
        return ts.factory.createCallExpression(
          ts.factory.createPropertyAccessExpression(
            expectCall(args[0]),
            'toBeTruthy',
          ),
          undefined,
          [],
        );
      }
      return undefined;
    case 'notOk':
      if (args.length >= 1) {
        return ts.factory.createCallExpression(
          ts.factory.createPropertyAccessExpression(
            expectCall(args[0]),
            'toBeFalsy',
          ),
          undefined,
          [],
        );
      }
      return undefined;
    case 'true':
      if (args.length >= 1) {
        return ts.factory.createCallExpression(
          ts.factory.createPropertyAccessExpression(
            expectCall(args[0]),
            'toBe',
          ),
          undefined,
          [ts.factory.createTrue()],
        );
      }
      return undefined;
    case 'false':
      if (args.length >= 1) {
        return ts.factory.createCallExpression(
          ts.factory.createPropertyAccessExpression(
            expectCall(args[0]),
            'toBe',
          ),
          undefined,
          [ts.factory.createFalse()],
        );
      }
      return undefined;
    case 'rejects': {
      if (args.length >= 1) {
        let rejectsExpr = ts.factory.createPropertyAccessExpression(
          ts.factory.createPropertyAccessExpression(
            expectCall(args[0]),
            'rejects',
          ),
          'toThrow',
        );
        return ts.factory.createCallExpression(
          rejectsExpr,
          undefined,
          args.length >= 2 ? [args[1]] : [],
        );
      }
      return undefined;
    }
    case 'codeEqual': {
      if (args.length >= 2) {
        return ts.factory.createCallExpression(
          ts.factory.createPropertyAccessExpression(
            expectCall(args[0]),
            'toEqual',
          ),
          undefined,
          [args[1]],
        );
      }
      return undefined;
    }
    default:
      return undefined;
  }
}

function addNamedImport(
  statements: ts.Statement[],
  moduleName: string,
  importName: string,
): ts.Statement[] {
  let importDecl = statements.find(
    (s): s is ts.ImportDeclaration =>
      ts.isImportDeclaration(s) &&
      ts.isStringLiteral(s.moduleSpecifier) &&
      s.moduleSpecifier.text === moduleName,
  );

  if (!importDecl) {
    let newImport = ts.factory.createImportDeclaration(
      undefined,
      ts.factory.createImportClause(
        false,
        undefined,
        ts.factory.createNamedImports([
          ts.factory.createImportSpecifier(
            false,
            undefined,
            ts.factory.createIdentifier(importName),
          ),
        ]),
      ),
      ts.factory.createStringLiteral(moduleName),
      undefined,
    );
    return [newImport, ...statements];
  }

  let clause = importDecl.importClause;
  let namedBindings = clause?.namedBindings;
  if (!clause || !namedBindings || !ts.isNamedImports(namedBindings)) {
    return statements;
  }

  let alreadyImported = namedBindings.elements.some(
    (e) => e.name.text === importName,
  );
  if (alreadyImported) {
    return statements;
  }

  let updatedNamedBindings = ts.factory.updateNamedImports(namedBindings, [
    ...namedBindings.elements,
    ts.factory.createImportSpecifier(
      false,
      undefined,
      ts.factory.createIdentifier(importName),
    ),
  ]);
  let updatedClause = ts.factory.updateImportClause(
    clause,
    clause.isTypeOnly,
    clause.name,
    updatedNamedBindings,
  );
  let updatedDecl = ts.factory.updateImportDeclaration(
    importDecl,
    importDecl.modifiers,
    updatedClause,
    importDecl.moduleSpecifier,
    importDecl.attributes,
  );

  return statements.map((s) => (s === importDecl ? updatedDecl : s));
}

function ensureVitestImport(
  statements: ts.Statement[],
  additionalImports: string[] = [],
): ts.Statement[] {
  let vitestImport = statements.find(
    (s): s is ts.ImportDeclaration =>
      ts.isImportDeclaration(s) &&
      ts.isStringLiteral(s.moduleSpecifier) &&
      s.moduleSpecifier.text === 'vitest',
  );

  const needed = [
    ...new Set(['describe', 'it', 'expect', ...additionalImports]),
  ];
  if (!vitestImport) {
    let importDecl = ts.factory.createImportDeclaration(
      undefined,
      ts.factory.createImportClause(
        false,
        undefined,
        ts.factory.createNamedImports(
          needed.map((n) =>
            ts.factory.createImportSpecifier(
              false,
              undefined,
              ts.factory.createIdentifier(n),
            ),
          ),
        ),
      ),
      ts.factory.createStringLiteral('vitest'),
      undefined,
    );
    return [importDecl, ...statements];
  }

  let clause = vitestImport.importClause;
  let namedBindings = clause?.namedBindings;
  if (!clause || !namedBindings || !ts.isNamedImports(namedBindings)) {
    return statements;
  }

  let existing = new Set(namedBindings.elements.map((e) => e.name.text));
  let missing = needed.filter((n) => !existing.has(n));
  if (!missing.length) {
    return statements;
  }

  let updatedNamedBindings = ts.factory.updateNamedImports(namedBindings, [
    ...namedBindings.elements,
    ...missing.map((n) =>
      ts.factory.createImportSpecifier(
        false,
        undefined,
        ts.factory.createIdentifier(n),
      ),
    ),
  ]);
  let updatedClause = ts.factory.updateImportClause(
    clause,
    clause.isTypeOnly,
    clause.name,
    updatedNamedBindings,
  );
  let updatedDecl = ts.factory.updateImportDeclaration(
    vitestImport,
    vitestImport.modifiers,
    updatedClause,
    vitestImport.moduleSpecifier,
    vitestImport.attributes,
  );

  return statements.map((s) => (s === vitestImport ? updatedDecl : s));
}

function ensureFilenameDirnamePrelude(
  statements: ts.Statement[],
  needsFilenamePolyfill: boolean,
  needsDirnamePolyfill: boolean,
): ts.Statement[] {
  if (!needsFilenamePolyfill && !needsDirnamePolyfill) {
    return statements;
  }

  let updatedStatements = statements;

  if (needsFilenamePolyfill) {
    updatedStatements = addNamedImport(
      updatedStatements,
      'url',
      'fileURLToPath',
    );
  }
  if (needsDirnamePolyfill) {
    updatedStatements = addNamedImport(updatedStatements, 'path', 'dirname');
  }

  let hasFilenameDecl = updatedStatements.some(
    (s) =>
      ts.isVariableStatement(s) &&
      s.declarationList.declarations.some(
        (d) => ts.isIdentifier(d.name) && d.name.text === '__filename',
      ),
  );
  let hasDirnameDecl = updatedStatements.some(
    (s) =>
      ts.isVariableStatement(s) &&
      s.declarationList.declarations.some(
        (d) => ts.isIdentifier(d.name) && d.name.text === '__dirname',
      ),
  );

  let prelude: ts.Statement[] = [];
  if (needsFilenamePolyfill && !hasFilenameDecl) {
    prelude.push(
      ts.factory.createVariableStatement(
        undefined,
        ts.factory.createVariableDeclarationList(
          [
            ts.factory.createVariableDeclaration(
              ts.factory.createIdentifier('__filename'),
              undefined,
              undefined,
              ts.factory.createCallExpression(
                ts.factory.createIdentifier('fileURLToPath'),
                undefined,
                [
                  ts.factory.createPropertyAccessExpression(
                    ts.factory.createMetaProperty(
                      ts.SyntaxKind.ImportKeyword,
                      ts.factory.createIdentifier('meta'),
                    ),
                    'url',
                  ),
                ],
              ),
            ),
          ],
          ts.NodeFlags.Const,
        ),
      ),
    );
  }
  if (needsDirnamePolyfill && !hasDirnameDecl) {
    prelude.push(
      ts.factory.createVariableStatement(
        undefined,
        ts.factory.createVariableDeclarationList(
          [
            ts.factory.createVariableDeclaration(
              ts.factory.createIdentifier('__dirname'),
              undefined,
              undefined,
              ts.factory.createCallExpression(
                ts.factory.createIdentifier('dirname'),
                undefined,
                [ts.factory.createIdentifier('__filename')],
              ),
            ),
          ],
          ts.NodeFlags.Const,
        ),
      ),
    );
  }

  if (!prelude.length) {
    return updatedStatements;
  }

  let lastImportIndex = -1;
  for (let i = 0; i < updatedStatements.length; i++) {
    if (ts.isImportDeclaration(updatedStatements[i])) {
      lastImportIndex = i;
    }
  }
  if (lastImportIndex === -1) {
    return [...prelude, ...updatedStatements];
  }
  return [
    ...updatedStatements.slice(0, lastImportIndex + 1),
    ...prelude,
    ...updatedStatements.slice(lastImportIndex + 1),
  ];
}

function collectUsedIdentifiers(statements: ts.Statement[]): Set<string> {
  let used = new Set<string>();
  function walk(node: ts.Node) {
    if (ts.isImportDeclaration(node)) {
      return;
    }
    if (ts.isIdentifier(node)) {
      used.add(node.text);
    }
    ts.forEachChild(node, walk);
  }
  for (let statement of statements) {
    walk(statement);
  }
  return used;
}

function pruneUnusedPathLikeImports(
  statements: ts.Statement[],
): ts.Statement[] {
  let used = collectUsedIdentifiers(statements);
  return statements.flatMap((statement) => {
    if (!ts.isImportDeclaration(statement)) {
      return [statement];
    }
    if (!ts.isStringLiteral(statement.moduleSpecifier)) {
      return [statement];
    }
    let moduleName = statement.moduleSpecifier.text;
    if (moduleName !== 'path' && moduleName !== 'url') {
      return [statement];
    }

    let clause = statement.importClause;
    let namedBindings = clause?.namedBindings;
    if (!clause || !namedBindings || !ts.isNamedImports(namedBindings)) {
      return [statement];
    }

    let kept = namedBindings.elements.filter((specifier) => {
      return used.has(specifier.name.text);
    });

    if (kept.length === namedBindings.elements.length) {
      return [statement];
    }

    if (!kept.length && !clause.name) {
      return [];
    }

    let updatedBindings = kept.length
      ? ts.factory.updateNamedImports(namedBindings, kept)
      : undefined;
    let updatedClause = ts.factory.updateImportClause(
      clause,
      clause.isTypeOnly,
      clause.name,
      updatedBindings,
    );
    return [
      ts.factory.updateImportDeclaration(
        statement,
        statement.modifiers,
        updatedClause,
        statement.moduleSpecifier,
        statement.attributes,
      ),
    ];
  });
}

function transformQUnitToVitest(
  sourceCode: string,
  targetFile: string,
  sourceFileName: string,
): TransformResult {
  let needsVitestHookImport = false;
  let unsupportedCalls: string[] = [];

  let sourceFile = ts.createSourceFile(
    targetFile,
    sourceCode,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );

  let transformer: ts.TransformerFactory<ts.SourceFile> = (context) => {
    function isAssertAsyncCall(node: ts.Expression): boolean {
      return (
        ts.isCallExpression(node) &&
        ts.isPropertyAccessExpression(node.expression) &&
        ts.isIdentifier(node.expression.expression) &&
        node.expression.expression.text === 'assert' &&
        node.expression.name.text === 'async'
      );
    }

    function isWaitRetryTimeoutCall(stmt: ts.Statement): boolean {
      if (
        !ts.isExpressionStatement(stmt) ||
        !ts.isCallExpression(stmt.expression)
      ) {
        return false;
      }
      let call = stmt.expression;
      if (
        !ts.isIdentifier(call.expression) ||
        call.expression.text !== 'setTimeout'
      ) {
        return false;
      }
      if (call.arguments.length < 1) {
        return false;
      }
      let callback = call.arguments[0];
      if (
        !(ts.isArrowFunction(callback) || ts.isFunctionExpression(callback))
      ) {
        return false;
      }
      let bodyExpr: ts.Expression | undefined;
      if (ts.isCallExpression(callback.body)) {
        bodyExpr = callback.body;
      } else if (
        ts.isBlock(callback.body) &&
        callback.body.statements.length === 1 &&
        ts.isExpressionStatement(callback.body.statements[0]) &&
        ts.isCallExpression(callback.body.statements[0].expression)
      ) {
        bodyExpr = callback.body.statements[0].expression;
      }
      if (!bodyExpr) {
        return false;
      }
      return (
        ts.isIdentifier(bodyExpr.expression) &&
        bodyExpr.expression.text === 'waitForBillingNotification'
      );
    }

    function rewriteWaitRetryFunction(
      fn: ts.FunctionExpression | ts.ArrowFunction,
    ): ts.FunctionExpression | ts.ArrowFunction {
      if (!ts.isBlock(fn.body)) {
        return fn;
      }
      function rewriteStatement(statement: ts.Statement): ts.Statement[] {
        if (
          ts.isExpressionStatement(statement) &&
          ts.isCallExpression(statement.expression) &&
          ts.isIdentifier(statement.expression.expression) &&
          statement.expression.expression.text === 'done'
        ) {
          return [ts.factory.createReturnStatement()];
        }

        if (ts.isIfStatement(statement)) {
          let thenStatements = ts.isBlock(statement.thenStatement)
            ? statement.thenStatement.statements.flatMap(rewriteStatement)
            : rewriteStatement(statement.thenStatement);
          let rewrittenThen = ts.factory.createBlock(thenStatements, true);

          let rewrittenElse: ts.Statement | undefined;
          if (statement.elseStatement) {
            if (ts.isBlock(statement.elseStatement)) {
              let elseStatements: ts.Statement[] = [];
              for (let elseStmt of statement.elseStatement.statements) {
                if (isWaitRetryTimeoutCall(elseStmt)) {
                  elseStatements.push(
                    ts.factory.createExpressionStatement(
                      ts.factory.createAwaitExpression(
                        ts.factory.createNewExpression(
                          ts.factory.createIdentifier('Promise'),
                          [
                            ts.factory.createKeywordTypeNode(
                              ts.SyntaxKind.VoidKeyword,
                            ),
                          ],
                          [
                            ts.factory.createArrowFunction(
                              undefined,
                              undefined,
                              [
                                ts.factory.createParameterDeclaration(
                                  undefined,
                                  undefined,
                                  ts.factory.createIdentifier('resolve'),
                                  undefined,
                                  undefined,
                                  undefined,
                                ),
                              ],
                              undefined,
                              ts.factory.createToken(
                                ts.SyntaxKind.EqualsGreaterThanToken,
                              ),
                              ts.factory.createCallExpression(
                                ts.factory.createIdentifier('setTimeout'),
                                undefined,
                                [
                                  ts.factory.createIdentifier('resolve'),
                                  ts.factory.createNumericLiteral(1),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  );
                  elseStatements.push(
                    ts.factory.createReturnStatement(
                      ts.factory.createAwaitExpression(
                        ts.factory.createCallExpression(
                          ts.factory.createIdentifier(
                            'waitForBillingNotification',
                          ),
                          undefined,
                          [],
                        ),
                      ),
                    ),
                  );
                } else {
                  elseStatements.push(...rewriteStatement(elseStmt));
                }
              }
              rewrittenElse = ts.factory.createBlock(elseStatements, true);
            } else {
              let elseStatements = rewriteStatement(statement.elseStatement);
              rewrittenElse =
                elseStatements.length === 1
                  ? elseStatements[0]
                  : ts.factory.createBlock(elseStatements, true);
            }
          }

          return [
            ts.factory.updateIfStatement(
              statement,
              statement.expression,
              rewrittenThen,
              rewrittenElse,
            ),
          ];
        }

        return [statement];
      }

      let rewrittenStatements = fn.body.statements.flatMap(rewriteStatement);

      let rewrittenBody = ts.factory.updateBlock(fn.body, rewrittenStatements);
      if (ts.isFunctionExpression(fn)) {
        return ts.factory.updateFunctionExpression(
          fn,
          fn.modifiers,
          fn.asteriskToken,
          fn.name,
          fn.typeParameters,
          [],
          fn.type,
          rewrittenBody,
        );
      }
      return ts.factory.updateArrowFunction(
        fn,
        fn.modifiers,
        fn.typeParameters,
        [],
        fn.type,
        fn.equalsGreaterThanToken,
        rewrittenBody,
      );
    }

    const visit: ts.Visitor = (node) => {
      if (ts.isExpressionStatement(node)) {
        if (
          ts.isCallExpression(node.expression) &&
          ts.isIdentifier(node.expression.expression) &&
          node.expression.expression.text === 'waitForBillingNotification' &&
          node.expression.arguments.some((a) => isAssertAsyncCall(a))
        ) {
          return ts.factory.createExpressionStatement(
            ts.factory.createAwaitExpression(
              ts.factory.createCallExpression(
                ts.factory.createIdentifier('waitForBillingNotification'),
                undefined,
                [],
              ),
            ),
          );
        }
        if (
          ts.isCallExpression(node.expression) &&
          ts.isPropertyAccessExpression(node.expression.expression) &&
          ts.isIdentifier(node.expression.expression.expression) &&
          node.expression.expression.expression.text === 'assert' &&
          node.expression.expression.name.text === 'expect'
        ) {
          return ts.factory.createEmptyStatement();
        }
      }

      if (ts.isCallExpression(node)) {
        let visitedNode = ts.visitEachChild(
          node,
          visit,
          context,
        ) as ts.CallExpression;

        if (
          ts.isPropertyAccessExpression(visitedNode.expression) &&
          ts.isIdentifier(visitedNode.expression.expression) &&
          visitedNode.expression.expression.text === 'assert'
        ) {
          let method = visitedNode.expression.name.text;
          let converted = convertAssertCall(method, visitedNode);
          if (converted) {
            return converted;
          }

          if (
            method !== 'beforeEach' &&
            method !== 'afterEach' &&
            method !== 'before' &&
            method !== 'after' &&
            method !== 'expect'
          ) {
            unsupportedCalls.push(callText(node, sourceFile));
          }
        }

        if (
          ts.isIdentifier(visitedNode.expression) &&
          (visitedNode.expression.text === 'module' ||
            visitedNode.expression.text === 'test')
        ) {
          let replacementName =
            visitedNode.expression.text === 'module' ? 'describe' : 'it';
          let updatedArgs = [...visitedNode.arguments];

          if (
            visitedNode.expression.text === 'module' &&
            updatedArgs.length >= 1
          ) {
            updatedArgs[0] = replaceBasenameFilenameArg(
              updatedArgs[0],
              sourceFileName,
            );
          }

          if (
            visitedNode.expression.text === 'module' &&
            updatedArgs.length >= 2
          ) {
            let callback = updatedArgs[1];
            if (
              (ts.isFunctionExpression(callback) ||
                ts.isArrowFunction(callback)) &&
              callback.parameters.length === 1 &&
              ts.isBlock(callback.body) &&
              ts.isIdentifier(callback.parameters[0].name)
            ) {
              let paramName = callback.parameters[0].name.text;
              needsVitestHookImport = true;
              let hooksDecl = ts.factory.createVariableStatement(
                undefined,
                ts.factory.createVariableDeclarationList(
                  [
                    ts.factory.createVariableDeclaration(
                      ts.factory.createIdentifier(paramName),
                      undefined,
                      undefined,
                      ts.factory.createObjectLiteralExpression(
                        [
                          ts.factory.createPropertyAssignment(
                            ts.factory.createIdentifier('before'),
                            ts.factory.createIdentifier('beforeAll'),
                          ),
                          ts.factory.createPropertyAssignment(
                            ts.factory.createIdentifier('after'),
                            ts.factory.createIdentifier('afterAll'),
                          ),
                          ts.factory.createShorthandPropertyAssignment(
                            ts.factory.createIdentifier('beforeEach'),
                            undefined,
                          ),
                          ts.factory.createShorthandPropertyAssignment(
                            ts.factory.createIdentifier('afterEach'),
                            undefined,
                          ),
                        ],
                        true,
                      ),
                    ),
                  ],
                  ts.NodeFlags.Const,
                ),
              );
              let updatedBody = ts.factory.updateBlock(callback.body, [
                hooksDecl,
                ...callback.body.statements,
              ]);

              if (ts.isFunctionExpression(callback)) {
                updatedArgs[1] = ts.factory.updateFunctionExpression(
                  callback,
                  callback.modifiers,
                  callback.asteriskToken,
                  callback.name,
                  callback.typeParameters,
                  [],
                  callback.type,
                  updatedBody,
                );
              } else {
                updatedArgs[1] = ts.factory.updateArrowFunction(
                  callback,
                  callback.modifiers,
                  callback.typeParameters,
                  [],
                  callback.type,
                  callback.equalsGreaterThanToken,
                  updatedBody,
                );
              }
            }
          }

          if (
            visitedNode.expression.text === 'test' &&
            updatedArgs.length >= 2
          ) {
            let callback = updatedArgs[1];
            if (
              (ts.isFunctionExpression(callback) ||
                ts.isArrowFunction(callback)) &&
              callback.parameters.length === 1 &&
              ts.isIdentifier(callback.parameters[0].name) &&
              callback.parameters[0].name.text === 'assert'
            ) {
              if (ts.isFunctionExpression(callback)) {
                updatedArgs[1] = ts.factory.updateFunctionExpression(
                  callback,
                  callback.modifiers,
                  callback.asteriskToken,
                  callback.name,
                  callback.typeParameters,
                  [],
                  callback.type,
                  callback.body,
                );
              } else {
                updatedArgs[1] = ts.factory.updateArrowFunction(
                  callback,
                  callback.modifiers,
                  callback.typeParameters,
                  [],
                  callback.type,
                  callback.equalsGreaterThanToken,
                  callback.body,
                );
              }
            }
          }

          return ts.factory.updateCallExpression(
            visitedNode,
            ts.factory.createIdentifier(replacementName),
            visitedNode.typeArguments,
            updatedArgs,
          );
        }

        return visitedNode;
      }

      if (ts.isVariableDeclaration(node)) {
        if (
          ts.isIdentifier(node.name) &&
          node.name.text === 'waitForBillingNotification' &&
          node.initializer &&
          (ts.isFunctionExpression(node.initializer) ||
            ts.isArrowFunction(node.initializer)) &&
          node.initializer.parameters.length >= 2 &&
          ts.isIdentifier(node.initializer.parameters[0].name) &&
          node.initializer.parameters[0].name.text === 'assert' &&
          ts.isIdentifier(node.initializer.parameters[1].name) &&
          node.initializer.parameters[1].name.text === 'done'
        ) {
          let rewritten = rewriteWaitRetryFunction(node.initializer);
          let visitedRewritten = ts.visitEachChild(
            rewritten,
            visit,
            context,
          ) as ts.FunctionExpression | ts.ArrowFunction;
          return ts.factory.updateVariableDeclaration(
            node,
            node.name,
            node.exclamationToken,
            node.type,
            visitedRewritten,
          );
        }
      }

      return ts.visitEachChild(node, visit, context);
    };

    return (node) => ts.visitNode(node, visit) as ts.SourceFile;
  };

  let transformed = ts.transform(sourceFile, [transformer]).transformed[0];
  let statements = [...transformed.statements].filter((s) => {
    return !(
      ts.isImportDeclaration(s) &&
      ts.isStringLiteral(s.moduleSpecifier) &&
      s.moduleSpecifier.text === 'qunit'
    );
  });

  statements = ensureVitestImport(
    statements,
    needsVitestHookImport
      ? ['beforeAll', 'beforeEach', 'afterAll', 'afterEach']
      : [],
  );

  let usedBeforePrelude = collectUsedIdentifiers(statements);
  let needsFilenamePolyfill = usedBeforePrelude.has('__filename');
  let needsDirnamePolyfill = usedBeforePrelude.has('__dirname');
  if (needsDirnamePolyfill) {
    needsFilenamePolyfill = true;
  }
  statements = ensureFilenameDirnamePrelude(
    statements,
    needsFilenamePolyfill,
    needsDirnamePolyfill,
  );
  statements = pruneUnusedPathLikeImports(statements);

  let updatedSourceFile = ts.factory.updateSourceFile(transformed, statements);
  let printer = ts.createPrinter({
    newLine: ts.NewLineKind.LineFeed,
    removeComments: false,
  });
  let printed = printer.printFile(updatedSourceFile).trimEnd() + '\n';
  printed = printed.replace(/(['"`])\.\.\/tests\//g, '$1./');

  return {
    code: `${generatedHeader}${printed}`,
    needsVitestHookImport,
    needsDirnamePolyfill,
    needsFilenamePolyfill,
    unsupportedCalls: [...new Set(unsupportedCalls)].sort(),
  };
}

function isTestFile(relPath: string): boolean {
  return relPath.endsWith('-test.ts');
}

function targetPathForTest(relPath: string): string {
  return join(targetRoot, relPath.replace(/-test\.ts$/, '.test.ts'));
}

function copySupportFiles(allFiles: string[]): number {
  let copied = 0;
  for (let absPath of allFiles) {
    let relPath = relative(sourceRoot, absPath);
    if (isTestFile(relPath)) {
      continue;
    }
    let outPath = join(targetRoot, relPath);
    ensureDirSync(dirname(outPath));
    copyFileSync(absPath, outPath);
    copied++;
  }
  return copied;
}

function run() {
  let allFiles = glob.sync('**/*', {
    cwd: sourceRoot,
    absolute: true,
    nodir: true,
    dot: true,
  });

  ensureDirSync(targetRoot);

  let copied = copySupportFiles(allFiles);
  let transformedCount = 0;
  let unsupportedByFile = new Map<string, string[]>();

  for (let absPath of allFiles) {
    let relPath = relative(sourceRoot, absPath);
    if (!isTestFile(relPath)) {
      continue;
    }
    let sourceCode = readFileSync(absPath, 'utf8');
    let outPath = targetPathForTest(relPath);
    let result = transformQUnitToVitest(sourceCode, outPath, basename(relPath));

    ensureDirSync(dirname(outPath));
    writeFileSync(outPath, result.code, 'utf8');
    transformedCount++;

    if (result.unsupportedCalls.length) {
      unsupportedByFile.set(relPath, result.unsupportedCalls);
    }
  }

  console.log(
    `QUnit -> Vitest codemod complete: transformed ${transformedCount} test files, copied ${copied} support files.`,
  );
  if (unsupportedByFile.size) {
    console.log('Files with unsupported assert calls (manual follow-up):');
    for (let [file, calls] of unsupportedByFile.entries()) {
      console.log(`- ${file}`);
      for (let call of calls) {
        console.log(`  - ${call}`);
      }
    }
  }
}

run();
