name: Build host with ember

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: build-host-${{ inputs.environment }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Init
        uses: ./.github/actions/init

      - name: Set up env
        run: cat packages/host/config/${{ inputs.environment }}.env >> $GITHUB_ENV

      - name: Restore boxel-icons build cache
        id: icons-cache
        uses: ./.github/actions/restore-icons-cache
      - name: Build boxel-icons and boxel-ui
        run: mise run build:ui
        env:
          SKIP_ICONS_BUILD: ${{ steps.icons-cache.outputs.cache-hit }}

      - name: Build host
        run: pnpm deploy:boxel-host build-only --verbose

      - name: Save dist
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # 4.6.1
        with:
          name: host-dist
          path: packages/host/tmp/deploy-dist
