name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  id-token: write
  pull-requests: write

jobs:
  matrix-client-test:
    name: Matrix Client Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1]
        shardTotal: [1]
    concurrency:
      group: matrix-client-test-${{ matrix.shardIndex }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: packages/matrix
      - name: Build boxel-icons
        run: pnpm build
        working-directory: packages/boxel-icons
      - name: Serve boxel-icons
        run: pnpm serve &
        working-directory: packages/boxel-icons
      - name: Build boxel-ui
        run: pnpm build
        working-directory: packages/boxel-ui/addon
      - name: Build boxel-motion
        run: pnpm build
        working-directory: packages/boxel-motion/addon
      - name: Start host to serve assets for fastboot
        run: pnpm start &
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        working-directory: packages/host
      - name: Wait for ember-cli to be ready
        run: pnpm npx wait-for-localhost 4200
        working-directory: packages/host
      - name: Start realm servers
        run: MATRIX_REGISTRATION_SHARED_SECRET='xxxx' pnpm start:services-for-matrix-tests &> /tmp/server.log &
        working-directory: packages/realm-server
      - name: Run Playwright tests
        run: pnpm test:group ${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        working-directory: packages/matrix
      - name: Upload realm server log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: matrix-test-realm-server-log-${{ matrix.shardIndex }}
          path: /tmp/server.log
          retention-days: 30

      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: packages/matrix/blob-report
          retention-days: 1

      - name: Upload Playwright traces
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces-${{ matrix.shardIndex }}
          path: packages/matrix/test-results/**/trace.zip
          retention-days: 30
          if-no-files-found: ignore
