name: Deploy boxel-ui with ember

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy-ui-${{ inputs.environment }}-${{ github.head_ref || github.run_id }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Init
        uses: ./.github/actions/init

      - name: Set up env
        env:
          INPUT_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          if [ "$INPUT_ENVIRONMENT" = "staging" ]; then
            echo "AWS_ROLE_ARN=arn:aws:iam::680542703984:role/boxel-ui" >> $GITHUB_ENV
            echo "AWS_S3_BUCKET=cardstack-boxel-ui-staging" >> $GITHUB_ENV
            echo "AWS_CLOUDFRONT_DISTRIBUTION=E3UUDP4PEB5IDV" >> $GITHUB_ENV
          else
            echo "unrecognized environment"
            exit 1;
          fi
      - name: Build boxel-ui addon
        run: pnpm build
        working-directory: packages/boxel-ui/addon

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # 4.1.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy
        run: pnpm deploy:boxel-ui ${{ inputs.environment }} --verbose

      - name: Send notification to Discord
        uses: cardstack/gh-actions/discord-notification-deploy@main
        with:
          app: "boxel-ui"
          status: ${{ job.status }}
          environment: ${{ inputs.environment }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
