name: CI AI Bot

on:
  pull_request:
    paths:
      - "packages/ai-bot/**"
      - "packages/billing/**"
      - "packages/postgres/**"
      - "packages/runtime-common/**"
      - ".github/workflows/pr-ai-bot.yml"
      - "package.json"
      - "pnpm-lock.yaml"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  id-token: write
  statuses: write

jobs:
  ai-bot-test:
    name: AI bot Tests
    runs-on: ubuntu-latest
    concurrency:
      group: ai-bot-test-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: ./.github/actions/init
      - name: AI Bot test suite
        run: pnpm test
        working-directory: packages/ai-bot
