name: YAML Lint

on:
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # 3.1.1
        with:
          config_file: ".github/.yamllint.yml"
          file_or_dir: ".github"
          strict: true
